[{"classified_as": "bug", "text": "When I go to database settings page in studio, my browser automatically fill fields \"username\" and \"password\". Maybe you can add attribute autocomplete=\"off\" in these fields?\n\n![2016-01-31 22 35 48](https://cloud.githubusercontent.com/assets/557190/12704394/1df1d3d4-c86b-11e5-9c47-39efc962d7dd.png)\n\nBrowser: Google Chrome, Mac OS.\n"}, {"classified_as": "enhancement", "text": "Affects P5 but also drakengard 3 and project diva. \r\n\r\nCan be temporarily fixed by unplugging my speakers and plugging them back in, after a period of intense crackling it goes away for a short time (a few minutes at least.) \r\n\r\nprobably partly pulse's fault but only rpcs3 is having this issue for me. "}, {"classified_as": "enhancement", "text": "It looks like the tap method is flaky, or at least the test for it is.\r\n\r\nhttps://travis-ci.org/GoogleChrome/puppeteer/jobs/271528560"}, {"classified_as": "enhancement", "text": "Since #6336 there's an issue where metadata gets doubled if a recalculation is deemed necessary. The reason is that we will have loaded the existing metadata, then do a recalc by adding all files without clearing it first."}, {"classified_as": "bug", "text": "![image](https://user-images.githubusercontent.com/7580792/37825461-da7940b0-2eca-11e8-8777-b8f78ef9886c.png)\r\n"}, {"classified_as": "bug", "text": "In a regular EditTextPreference, you can have four properties which are displayed in different areas:\n\n\n <EditTextPreference\n        android:key=\"key1\"\n        android:title=\"aaa\"\n        android:summary=\"bbb\"\n        android:dialogTitle=\"ccc\"\n        android:dialogMessage=\"ddd\"\n        android:defaultValue=\"lorem ipsum\"\n        />\n\n\nSo the preference appears like so (title, summary)\n\n![image](https://cloud.githubusercontent.com/assets/746276/6379308/21d0b46e-bd29-11e4-90c1-2bc33a9ec85e.png)\n\nAnd on clicking the preference, the dialog appears like so (dialogTitle, dialogMessage)\n\n![image](https://cloud.githubusercontent.com/assets/746276/6379298/107b6a92-bd29-11e4-9b5f-17b47a97c39d.png)\n\nCurrently the MaterialEditTextPreference does not show dialogMessage property when the dialog opens.\n\n![image](https://cloud.githubusercontent.com/assets/746276/6379729/49161df4-bd2c-11e4-8d93-3c31efdf7df9.png)\n\nTHanks for all your work on this library, it has made life so much better. \n"}, {"classified_as": "bug", "text": "Per the [package.json file](https://github.com/GoogleChrome/puppeteer/blob/master/package.json), it looks like puppeteer only works on Node versions >=7.10.0. Would you be willing to maintain this package on the Node 6 release line, since it is the current LTS version?"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nThe default _limit for the find() is currently fixed to 100. I can't understand why the team picked it is 100? why wouldn't be 10 or 50?.\r\n\r\nIf some one needed to fetch default 50 records for all end point of find(), at-least he have to edit all request URL or needed to override the current find() handle.\r\n\r\nThis may not be a bug for the team, but for best framework we need to control constant values at configuration level.\r\n\r\n**Steps to reproduce the behavior**\r\n1. Start strapi app\r\n2. create product collection\r\n3. goto http://localhost:1337/products\r\n4. you can see the limitation of 100 products when there are more than 100 products\r\n\r\n**Expected behavior**\r\nThe configuration must be present.\r\n\r\n**System**\r\n- Node.js version: v12.13.0\r\n- NPM version: 6.12.0\r\n- Strapi version: v3.0.0-beta.18.4\r\n- Database: MongoDB\r\n- Operating system: Windows\r\n"}, {"classified_as": "enhancement", "text": "https://github.com/polkadot-js/api/tree/master/docs/examples/promise#development-accounts"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nSince updating to version *v3.0.0-beta.16.4* I somehow expirience an issue where the different Icons in front of the Content-Type name are not aligned perfectly centered. This is a totally astethic issue and does not effect functionality in any way, matter of fact it's unpleasant.\r\n\r\n**Steps to reproduce the behavior**\r\n1. Update to version v3.0.0-beta.16.4 or higher.\r\n2. Take a look at the side-nav.\r\n\r\n**Expected behavior**\r\nThe icons should be centered like in previous versions.\r\n\r\n**Screenshots**\r\n\r\n![sidenav-strapi](https://user-images.githubusercontent.com/36916632/65301250-e9675d00-db76-11e9-8e08-45183d60015e.PNG)\r\n\r\n**Code snippets**\r\nNot applicable.\r\n\r\n**System**\r\n- Node.js version: 12.10.0\r\n- NPM version: 6.11.3\r\n- Strapi version: v3.0.0-beta.16.5\r\n- Database: MongoDB\r\n- Operating system: Windows Server 2002 R2\r\n"}, {"classified_as": "bug", "text": " - Material Dialogs version: 0.9.2.3\r\n - API: 25\r\n - Device Manufacturer: Android\r\n - Device Name: Nexus 7 / Android Emulator\r\n\r\nI invoke a MaterialDialog with my custom view:\r\n\r\njava\r\n   new MaterialDialog.Builder(myActivity)\r\n   .customView(view, false)\r\n   .negativeText(R.string.dialog_user_profile_button)\r\n   .title(user.getHandle())\r\n   .show();\r\n\r\n\r\nThe problem is that the contents isn't wrapped, i.e. I the right margin is wider than the left. \r\n\r\n(This is a problem in AppCompat AlertDialog also).\r\n\r\n \r\n\r\n\r\n"}, {"classified_as": "bug", "text": "- [x] **I have created my request on the Product Board before I submitted this issue**\r\n- [x] **I have looked at all the other requests on the Product Board before I submitted this issue**\r\n\r\n**Please describe your feature request:**\r\nThe title pretty much covers it. The specific example of how I ran into this was I had a request interceptor in my front-end app that was errantly adding a \"Content-Type: application/x-www-form-urlencoded\" header to a login request, which should be \"application/json\". When this happens, Strapi responds with a generic 400 Bad Request rather than the appropriate 415."}, {"classified_as": "enhancement", "text": "On Alex -\r\n\r\n![image](https://user-images.githubusercontent.com/1424473/59966905-e088d000-9522-11e9-96a7-297ad3129d4a.png)\r\n\r\n{\"jsonrpc\":\"2.0\",\"method\":\"state_storage\",\"params\":{\"result\":{\"block\":\"0xbfb1676a357e772c854d88aaee13614a08ffe67bf4b59160481828e03982dbf7\",\"changes\":[[\"0x107e8d8b935b2cfcd4b80ed517149a49\",\"0x210100000000000000000000000000000000000000000000000000000000000000000000000000000000011b4d03dd8c01f1049143cf9c4c817e4b167f1d1b83e5c6f0f10d89ba1e7bce\"]]},\"subscription\":145305}}\r\n\r\nWith an Option<...> type the length is added by the Rust side, but not by the JS side. So, without looking at the code, it seems with Option, we just call the toHex() of the containing class when isSome. Rather what should happen is to call toU8a() of the containing class and then u8aToHex that.\r\n\r\nOr rather ... it could be our convert-to-bytes and then convert-to-whatever converter in storage. Either way, we are not doing what is expected."}, {"classified_as": "bug", "text": "Font spacing seems to be inconsistent between headless and non headless mode.\r\nThis is likely a Chromium bug for Puppeteer versions 1.2.0 and above.\r\n\r\n### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: 1.2\r\n* Platform / OS version: Linux\r\n* URLs (if applicable):\r\n* Node.js version: 8.6.0\r\n\r\n**What steps will reproduce the problem?**\r\n\r\n1. screenshot.js\r\n\r\n'use strict';\r\n\r\nconst puppeteer = require('puppeteer');\r\n\r\n(async() => {\r\n  const browser = await puppeteer.launch({ headless: true }); // toggle to false\r\n  const page = await browser.newPage();\r\n  await page.goto('file:///tmp/test.html');\r\n  await page.waitFor(5000);\r\n  await page.screenshot({path: '/tmp/screenshot.png'});\r\n  await browser.close();\r\n})();\r\n\r\n2. test.html\r\n\r\n<html>\r\n  <head>\r\n    <link rel=\"stylesheet\"\r\n          href=\"https://fonts.googleapis.com/css?family=Lato\">\r\n    <style>\r\n      body {\r\n        font-family: 'Lato', serif;\r\n        font-size: 15px;\r\n      }\r\n      div.a {\r\n        line-height: 0.5;\r\n      }\r\n    </style>\r\n  </head>\r\n  <body>\r\n    <div class=\"a\">\r\n      <div>aaaaa..............................................................................|111</div><br>\r\n      <div>qwertyasdfzxcvyuiohjklbnm................................|222</div><br>\r\n      <div>longlonglonglonglonglonglonglongshorty......|333</div>\r\n    </div>\r\n  </body>\r\n</html>\r\n\r\n3. node /tmp/screenshot.js, then repeat with headless: false \r\n\r\n**What is the expected result?**\r\nText is correctly aligned and looks the same as opening the HTML in browser. headless: false\r\n\r\n![headless_false](https://user-images.githubusercontent.com/1380839/38925691-f36ba690-4332-11e8-96b4-a1cc0e784e60.png)\r\n\r\n**What happens instead?**\r\nText is misaligned with headless: true\r\n\r\n![headless_true](https://user-images.githubusercontent.com/1380839/38925690-f33bcfce-4332-11e8-9a19-0ef463f032e9.png)"}, {"classified_as": "enhancement", "text": "In Silent Hill 3 RSX uses some 1280x720 texture with 12 mipmaps. log2(1280) is 11 so there is a mipmap level that shouldn't be here.\n\nIt looks like DX12 doesn't mind, I'm not sure about Vulkan. However in GL this leads to invalid texture. Capping mipmap level fixes the issue.\n\nAll backend are affected since they use rsx::texture::mipmap() to get mipmap count.\n"}, {"classified_as": "enhancement", "text": "\r\nActually the code returned problem with VK_FORMAT_B8G8R8A8_SRGB that does not match the format of VK_FORMAT_R5G6B5_UNORM_PACK16\r\n\r\n>RSX: ERROR: [DS] Code 155191008 : vkCreateFramebuffer(): VkFramebufferCreateInfo attachment #0 has format of VK_FORMAT_B8G8R8A8_SRGB that does not match the format of VK_FORMAT_R5G6B5_UNORM_PACK16 used by the corresponding attachment for renderPass (0x53). The spec valid usage text states 'Any given element of pAttachments must have been created with an VkFormat value that matches the VkFormat specified by the corresponding VkAttachmentDescription in renderPass' (https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#VUID-VkFramebufferCreateInfo-pAttachments-00880)\r\n\r\nNeeded rewrite this part for the work \r\nRegards\r\nMrc."}, {"classified_as": "enhancement", "text": "While sending, status from extrinsic submission -\r\n\r\n<img width=\"495\" alt=\"Polkadot:Substrate Portal 2019-03-16 17-48-45\" src=\"https://user-images.githubusercontent.com/1424473/54478564-d9f80780-4813-11e9-99ca-7ffde3d32b86.png\">\r\n"}, {"classified_as": "bug", "text": "Option<T>, Result<T,E> and Vec<T> (Vec<T> not listed below, but has the same form as Option<T>)\r\n\r\nExample ABI: (@jacogr & @robbepop has the WASM for this)\r\n\r\njs\r\n{\r\n    \"name\": \"SharedVec\",\r\n    \"deploy\": {\r\n        \"args\": []\r\n    },\r\n    \"messages\": [\r\n        {\r\n            \"name\": \"push\",\r\n            \"selector\": 865577567,\r\n            \"mutates\": true,\r\n            \"args\": [\r\n                {\r\n                    \"name\": \"value\",\r\n                    \"type\": \"i32\"\r\n                }\r\n            ],\r\n            \"return_type\": {\r\n                \"Result<T,E>\": {\r\n                    \"T\": [],\r\n                    \"E\": \"u32\"\r\n                }\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"register\",\r\n            \"selector\": 572030971,\r\n            \"mutates\": true,\r\n            \"args\": [\r\n                {\r\n                    \"name\": \"mutator\",\r\n                    \"type\": \"AccountId\"\r\n                },\r\n                {\r\n                    \"name\": \"begin\",\r\n                    \"type\": {\r\n                        \"Option<T>\": {\r\n                            \"T\": \"u32\"\r\n                        }\r\n                    }\r\n                },\r\n                {\r\n                    \"name\": \"end\",\r\n                    \"type\": {\r\n                        \"Option<T>\": {\r\n                            \"T\": \"u32\"\r\n                        }\r\n                    }\r\n                }\r\n            ],\r\n            \"return_type\": {\r\n                \"Result<T,E>\": {\r\n                    \"T\": [],\r\n                    \"E\": \"u32\"\r\n                }\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"set\",\r\n            \"selector\": 2028185770,\r\n            \"mutates\": true,\r\n            \"args\": [\r\n                {\r\n                    \"name\": \"at\",\r\n                    \"type\": \"u32\"\r\n                },\r\n                {\r\n                    \"name\": \"to\",\r\n                    \"type\": \"i32\"\r\n                }\r\n            ],\r\n            \"return_type\": {\r\n                \"Result<T,E>\": {\r\n                    \"T\": \"i32\",\r\n                    \"E\": \"u32\"\r\n                }\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"get\",\r\n            \"selector\": 4266279973,\r\n            \"mutates\": false,\r\n            \"args\": [\r\n                {\r\n                    \"name\": \"at\",\r\n                    \"type\": \"u32\"\r\n                }\r\n            ],\r\n            \"return_type\": {\r\n                \"Option<T>\": {\r\n                    \"T\": \"i32\"\r\n                }\r\n            }\r\n        },\r\n        {\r\n            \"name\": \"len\",\r\n            \"selector\": 1403873684,\r\n            \"mutates\": false,\r\n            \"args\": [],\r\n            \"return_type\": \"u32\"\r\n        }\r\n    ]\r\n}\r\n"}, {"classified_as": "bug", "text": "Have you ever considered adding a q tag CSS definition in Bootstrap? Here's the one I've been using:\r\n\r\n// HT: Disgruntled Goat\r\n// http://stackoverflow.com/users/37947/disgruntledgoat\r\nq:before { content: \"\\201c\"; }\r\nq:after { content: \"\\201d\"; }\r\nq q:before { content: \"\\2018\"; }\r\nq q:after { content: \"\\2019\"; }\r\n"}, {"classified_as": "bug", "text": "<!--\r\nThank you for reporting a possible bug in Node.js.\r\n\r\nPlease fill in as much of the template below as you can.\r\n\r\nVersion: output of node -v\r\nPlatform: output of uname -a (UNIX), or version and 32 or 64-bit (Windows)\r\nSubsystem: if known, please specify the affected core module name\r\n\r\nIf possible, please provide code that demonstrates the problem, keeping it as\r\nsimple and free of external dependencies as you can.\r\n-->\r\n\r\n* **Version**: 12.11.1\r\n* **Platform**: Windows 10\r\n* **Subsystem**: ES modules\r\n\r\nFrom https://github.com/eslint/eslint/pull/12333\r\n\r\nRepro https://github.com/mysticatea/import-cjs-issue\r\n\r\n### Description\r\n\r\nI tried to import packages without import cache. From the document, it looks I should use query strings.\r\n\r\njs\r\n    await import(\"x-esm\") //\u2192 Found as expected\r\n    await import(\"./node_modules/x-esm/index.js?q=0\") //\u2192 Found and x-esm re-ran as expected\r\n    await import(\"./node_modules/x-esm/index.js?q=1\") //\u2192 Found and x-esm re-ran as expected\r\n\r\n\r\nx-esm is an ES module package. It worked as expected.\r\n\r\njs\r\n    const cjs = await import(\"x-cjs\") //\u2192 Found as expected\r\n    const cjs0 = await import(\"./node_modules/x-cjs/index.js?q=0\") //\u2192 Found but x-cjs didn't re-run\r\n    const cjs1 = await import(\"./node_modules/x-cjs/index.js?q=1\") //\u2192 Found but x-cjs didn't re-run\r\n    console.log(cjs === cjs0, cjs === cjs1, cjs0 === cjs1) //\u2192 all are false but x-cjs didn't run three times\r\n\r\n\r\nx-cjs is a CJS package. The result was odd. The console.log() in x-cjs package ran only one time, but the returned values are different for each query string.\r\n\r\nI found the entry of x-cjs in require.cache. However, the cache entry is odd as well. It's different from require(\"x-cjs\"), the entry doesn't have parent property and the module.children of test.js is still empty.\r\n\r\nAnyway, I tried to remove the cache entry.\r\n\r\njs\r\n    console.log(\"---- remove 'require.cache' ----\")\r\n    delete require.cache[require.resolve(\"x-cjs\")]\r\n    await import(\"x-cjs\") //\u2192 Found but x-cjs didn't re-run\r\n    await import(\"./node_modules/x-cjs/index.js?q=0\") //\u2192 Found but x-cjs didn't re-run\r\n    await import(\"./node_modules/x-cjs/index.js?q=1\") //\u2192 Found but x-cjs didn't re-run\r\n    await import(\"./node_modules/x-cjs/index.js?q=2\") //\u2192 Found and x-cjs re-ran as expected\r\n    await import(\"./node_modules/x-cjs/index.js?q=3\") //\u2192 Found but x-cjs didn't re-run\r\n\r\n\r\nCryptic. I guess this behavior is:\r\n\r\n- import(cjs) has cache apart from require.cache.\r\n- The import(cjs) cache is created from require.cache.\r\n- It runs CJS package only if require.cache entry was not found.\r\n- The import(cjs) cache is not removed even if require.cache entry deleted.\r\n\r\nTherefore, I have to do the following steps if I want to import packages without cache.\r\n\r\n1. Find the main file of the package because I cannot put query strings to the package name.\r\n   js\r\n   const url = \"file:\" + require.resolve(packageName) + uniqueQueryString;\r\n   \r\n1. Import it.\r\n   js\r\n   const ret = await import(url);\r\n   \r\n1. Delete require.cache entry.\r\n   js\r\n   delete require.cache[require.resolve(packageName)];\r\n   \r\n\r\n### Questions\r\n\r\n1. Is it intentional behavior that import(cjs) creates incomplete require.cache entries?\r\n1. If yes, is it intentional behavior that import(cjs) with query strings returns different objects for the same CJS package?\r\n\r\nI'm guessing that import(cjs) should not create any require.cache entries, and import(cjs) with query strings re-runs CJS packages as same as ES packages."}, {"classified_as": "bug", "text": "In current implementation, RDBStorage is incompatible with multi-thread mode. This is because db object cannot be share among multi-threads, in some RDB backends. E.g., sqlite3 raises the following error when a session is used in different threads:\r\n\r\n\r\n(sqlite3.ProgrammingError) SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 140736163832640 and this is thread id 123145433608192 \r\n \r\n\r\nThough we've decided not to support this combination for now, we could revisit this issue after wrapping up multi-node/multi-process mode."}, {"classified_as": "enhancement", "text": "This is very low importance, it just came up with a recent report of connection issues:\r\n\r\nLogging like l.Infoln(err) leads to errors like \r\n\r\n\r\n[NPNSQ] 22:22:01 INFO: set tcp 192.168.178.24:6736->192.168.178.20:22000: protocol not available\r\n\r\n\r\nwhose origin and context are not immediately clear. As this is user facing information, it should contain a minimum of information. In the example of the tcp listener this could be in line with existing logging:\r\n\r\n\r\n\t\t\tl.Infoln(\"Listen (BEP/tcp): failed to set options:\", err)\r\n\r\n\r\nThe alternative is to downgrade it to debug logging level, where the context is evident from file names and line numbers. In the case of the tcp listener, [similar failures are on different levels](https://github.com/syncthing/syncthing/blob/master/lib/connections/tcp_listen.go#L105). Is this on purpose or should all of them be either debug or info level?\r\n"}, {"classified_as": "enhancement", "text": "**Describe the bug**\r\nWhen opening the admin the landing page always shows the same welcome message prompting you to create your first content-type, even if you already have content-types created\r\n\r\n**Steps to reproduce the behavior**\r\nopen the admin page\r\n\r\n**Expected behavior**\r\ndifferent messaging should be displayed here\r\nthe button to prompt creating content-types shouldn't be allowed on production either since the module is disabled\r\n\r\n**Code snippets**\r\nhttps://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-admin/admin/src/containers/HomePage/index.js#L64-L67\r\nhasAlreadyCreatedContentTypes uses leftMenuLinks property to decide what message to show. \r\n\r\nin pull request merge #6965 from strapi/features/rbac\r\nleftMenuLinks was removed from the content-manager plugin\r\nhttps://github.com/strapi/strapi/blob/b39709a6edee136047260aefca34069e4cf8b0f8/packages/strapi-plugin-content-manager/admin/src/index.js#L20-L45\r\n\r\nSorry I can't quite track down the fix, I'm not familiar with the roadmap enough  "}, {"classified_as": "bug", "text": "**Describe the bug**\r\nIt appears the [index.html](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/public/index.html) [still?] references assets on strapi.io. It also appears this asset is blocked due to a referral policy.\r\n\r\n**Steps to reproduce the behavior**\r\n\r\n1. npx strapi create strapi --quickstart\r\n2. visit http://localhost:1337/\r\n3. Observe logo missing\r\n\r\n**Expected behavior**\r\nLogo should be present.\r\n\r\n**Screenshots**\r\n![2020-05-20 14_50_04-Welcome to your Strapi app](https://user-images.githubusercontent.com/10567322/82485421-64d43200-9aa9-11ea-8604-31db51f29e2f.png)\r\n\r\n**System**\r\n\r\n- strapi/strapi:3.0.0-beta.20.3 docker image\r\n- Node.js version: v12.13.0\r\n- Database: mongo\r\n"}, {"classified_as": "bug", "text": "http://www.google.com/design/spec/components/dialogs.html\n"}, {"classified_as": "enhancement", "text": "If syncthing encounters a fatal error during startup (for example it cannot listen on the API/GUI port) it should exit. Currently it does not, and also it cannot be made to exit after this point, ignoring Ctrl-C. It requires a hard kill to get rid of the process."}, {"classified_as": "enhancement", "text": "When we\u2019re setting docExpansion: 'none' in configuration, then giving someone a permalink to a particular endpoint inside a tag, and them clicking it doesn\u2019t do anything for them.\r\n\r\nAfter the page opens for them, all endpoints are still *not expanded*, as if there was no /#/permalink/part in the URL."}, {"classified_as": "bug", "text": "My application spring boot to develop and use docker image openjdk:11-jdk to build image\r\npreviously I use alpine version of the image and ran into problem which sometimes the pod is not able to connect to k8s dns\r\nafter changing back to base openjdk:11-jdk version, the dns discovery is resolved, yet sometimes, every 10-20, it takes so long about 14-16 seconds to reach destination (other service within the cluster)"}, {"classified_as": "enhancement", "text": "Running through the Vue tutorial in the playground, lesson 3 step 7 says drag a TabView from the component selector on the left. But there's no TabView component in the selector. I can only find a Tabs navigation component. Has something changed here, or am I missing something obvious..?\r\n\r\n"}, {"classified_as": "enhancement", "text": "I've been having issues trying to hover an svg element using elementHandle.hover(), now using page.evaluate(element => element.getBoundingClientRect(), elementHandle) works so I'm not sure why it throws an error for .hover().\r\n\r\nHere's a minimal example that causes it:\r\n\r\n[puppeteer-svg-hover-test.zip](https://github.com/GoogleChrome/puppeteer/files/1436011/puppeteer-svg-hover-test.zip)"}, {"classified_as": "bug", "text": "As you can see in the following image, axis labels overlap when parameter names are too long. I think we can solve this issue if we limit the maximum length of the labels and/or tilt the labels.\r\n\r\n![newplot (39)](https://user-images.githubusercontent.com/3255979/66977250-19efd780-f0e0-11e9-87ba-a6616083da31.png)\r\n\r\n**Conditions**\r\n- Optuna version: 0.17.1\r\n- Python version: 3.7.2\r\n- OS: macOS 10.13\r\n\r\n**Code to reproduce**\r\n\r\npython\r\nimport optuna\r\n\r\ndef objective(trial):\r\n    x = trial.suggest_uniform('x' * 100, -10, 10)\r\n    y = trial.suggest_uniform('y' * 100, -10, 10)\r\n    return x - y\r\n\r\nstudy = optuna.create_study()\r\nstudy.optimize(objective, n_trials=20)\r\n\r\noptuna.visualization.plot_parallel_coordinate(study)\r\n"}, {"classified_as": "enhancement", "text": "I have that message on all available Macs although all of them are configured to use IPv6.\n\nWhile debugging iOS version, I've found that IPv6 multicasting on iOS requires to configure IPV6_MULTICAST_IF and IPV6_ADD_MEMBERSHIP with an exact interface index set, i.e. passing 0 will not work.\n\nI think that should do the trick on OS X too.\n"}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\nIf you try to override the count callback in the controller as described [in the documentation](https://strapi.io/documentation/3.0.0-beta.x/concepts/controllers.html#core-controllers), the callback gets called fine via REST but will not get called via GraphQL. Unless you override the GraphQL Aggregator resolver to call the controller (see additional info). I'm thinking this caused by [this](https://github.com/strapi/strapi/blob/master/packages/strapi-plugin-graphql/services/Aggregator.js#L356)\r\n\r\n**Steps to reproduce the behavior**\r\n1. Override count callback in the controller\r\njs\r\nmodule.exports = {\r\n    count(ctx) {\r\n        console.log(\"Ad controller: count\");\r\n        if (ctx.query._q) {\r\n            return strapi.services.ad.countSearch(ctx.query);\r\n        }\r\n        return strapi.services.ad.count(ctx.query);\r\n    },\r\n};\r\n\r\n2. Test the controller via REST [http://localhost:1337/ads/count](http://localhost:1337/ads/count)\r\n3. Test the controller via GraphQL\r\ngraphql\r\nquery {\r\n  adsConnection {\r\n    aggregate {\r\n      count\r\n    }\r\n  }\r\n}\r\n\r\n4. See the log\r\n\r\n**Expected behavior**\r\ncount callback should still be called via GraphQL.\r\n\r\n**Screenshots**\r\nLog via REST\r\n![image](https://user-images.githubusercontent.com/32438205/74593674-53215f80-5060-11ea-8089-881db23b0b8e.png)\r\nLog via GraphQL\r\n![image](https://user-images.githubusercontent.com/32438205/74593688-74824b80-5060-11ea-95b1-5439ef5a9f4e.png)\r\n\r\n**Additional info**\r\nHow do I manually override GraphQL Aggregator resolver:\r\njs\r\nmodule.exports = {\r\n  resolver: {\r\n    AdAggregator: {\r\n      count(args) {\r\n        return strapi.controllers.ad.count({\r\n          query: args.where || {}\r\n        });\r\n      }\r\n    }\r\n  }\r\n};\r\n\r\n\r\n**System**\r\n- Node.js version: v10.16.0\r\n- Yarn version: 1.21.1\r\n- Strapi version:  Strapi v3.0.0-beta.18.7\r\n- Database: MongoDB\r\n- Operating system: Windows 10\r\n"}, {"classified_as": "enhancement", "text": "**Environment**\r\n- 6.1.0 running on both platforms but focusing on iOS \r\n- Angular 8.2.0\r\n- tns-ios: 6.1.0\r\n- tns-android 6.1.2\r\n\r\n**Describe the bug**\r\nI have been stuck at this issue for a while now and I'm starting to think it's a bug in NativeScript implementation. So any feedback would be appreciated.\r\n\r\nSo I have this page which seems pretty standard. It has an ActionBar at the top, scrollable content in the form of messages and then at the bottom a sticky input with a button.\r\n\r\nWhat I would like to achieve is the following behaviour present in many other apps:\r\n\r\nWhen I click in the TextView the focus goes on the whole area (the whole formGroup)\r\nWhen I start typing, the view would remains focused (currently removing the ScrollView #pageScrollView or disabling scroll will make the page jump as soon as you start typing)\r\nScrolling should be only available in the messages so you should never be able to hide the formGroup\r\n\r\n\r\n<ScrollView #pageScrollView>\r\n  <GridLayout rows=\"*, auto, auto\" class=\"page-conversation\" width=\"100%\" height=\"100%\">\r\n\r\n    <ScrollView\r\n      orientation=\"vertical\"\r\n      #messagesScrollView\r\n    >    \r\n      <StackLayout class=\"messages\">\r\n        <StackLayout\r\n          orientation=\"vertical\"\r\n          *ngFor=\"let message of messages\"\r\n          class=\"message\"\r\n          [ngClass]=\"{\r\n            'message--received': message.reply,\r\n            'message--sent': !message.reply\r\n          }\"\r\n        >\r\n          <Label class=\"message-content\" textWrap=\"true\" [text]=\"message['content']\"></Label>\r\n          <Label class=\"message-timestamp\" [text]=\"message['timestamp'] | date:'dd.MM.yy, hh:mm'\"></Label>\r\n        </StackLayout>\r\n      </StackLayout>\r\n    </ScrollView>\r\n\r\n    <GridLayout\r\n      rows=\"auto, 50\"\r\n      columns=\"*, *, *, auto\"\r\n      row=\"1\"\r\n      class=\"compose\"\r\n    >\r\n      <StackLayout row=\"0\" rowSpan=\"1\" col=\"0\" colSpan=\"4\" [formGroup]=\"form\">\r\n        <TextView\r\n          hint=\"Enter message\" \r\n          #newMessage\r\n          formControlName=\"newMessage\"\r\n          [text]=\"\"\r\n          required\r\n          (focus)=\"onFocus($event)\"\r\n          (blur)=\"onBlur($event)\"\r\n          [autocorrect]=\"false\"\r\n          class=\"textarea\"\r\n          autocapitalizationType=\"none\"\r\n        ></TextView>\r\n      </StackLayout>\r\n      <StackLayout row=\"1\" col=\"0\" class=\"option\">\r\n        <Label text=\"test\"></Label>\r\n      </StackLayout>\r\n      <StackLayout row=\"1\" col=\"1\" class=\"option\">\r\n        <Label text=\"test\"></Label>\r\n      </StackLayout>\r\n      <StackLayout row=\"1\" col=\"2\" class=\"option\">\r\n        <Label text=\"test\"></Label>\r\n      </StackLayout>\r\n      <StackLayout row=\"1\" col=\"3\" class=\"option\">\r\n        <Button\r\n          #composeArea\r\n          text=\"Send msg\"\r\n          class=\"send-button\"\r\n        ></Button>\r\n      </StackLayout>\r\n    </GridLayout>\r\n\r\n  </GridLayout>\r\n</ScrollView>\r\n\r\n\r\nSo I think the main point of concern here would be the behaviour of ScrollView and/or TextView."}, {"classified_as": "bug", "text": "It would be nice if ECMAScript shebang files with no extension\r\na. worked :)\r\nb. were assumed to be modules for Node.js current+\r\n\r\nEspecially for server people that have lots of command-line scripts\r\n\r\nAnd I think we should plan for a future without require\r\n\r\nexhibit:\r\n<pre><strong>\r\nnode --print '\"#!/usr/bin/env node\\n// node --experimental-modules e\\nimport {inspect} from QutilQ\\nconsole.log(${inspect(QabcQ)})\".replace(/Q/g, String.fromCharCode(39))' >e && chmod +x e\r\n./e</strong>\r\n(node:38910) Warning: To load an ES module, set \"type\": \"module\" in the package.json or use the .mjs extension.\r\n/opt/foxyboy/sw/pri/subtree/ecmascript2049/packages/e:3\r\nimport {inspect} from 'util'\r\n^^^^^^\r\n\r\nSyntaxError: Cannot use import statement outside a module\r\n    at wrapSafe (internal/modules/cjs/loader.js:1063:16)\r\n    at Module._compile (internal/modules/cjs/loader.js:1111:27)\r\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)\r\n    at Module.load (internal/modules/cjs/loader.js:996:32)\r\n    at Function.Module._load (internal/modules/cjs/loader.js:896:14)\r\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\r\n    at internal/main/run_main_module.js:17:47\r\n<strong>$ cat e</strong>\r\n#!/usr/bin/env node\r\n// node --experimental-modules e\r\nimport {inspect} from 'util'\r\nconsole.log(${inspect('abc')})\r\n</pre>\r\n\r\nThis shebang no work either:\r\n#!/usr/local/bin/node --experimental-modules\r\n\r\nThe solutions at present is to:\r\n1. use .mjs extension\r\n2. symlink to a file that has .mjs extension. Not portable, I suppose, on certain file systems from up north and Applish implementations of WebDAV\r\n3. have a package.json in the same or superior directory. May cause unforeseen troubles\r\n4. symlink to a directory with a package.json. Possibly not portable\r\n\r\n**node -v && uname -a**\r\nv13.11.0\r\nDarwin c87m1.local 19.3.0 Darwin Kernel Version 19.3.0: Thu Jan  9 20:58:23 PST 2020; root:xnu-6153.81.5~1/RELEASE_X86_64 x86_64\r\n\r\nA related trouble is if you happen to have a native-code dependency. requires node_modules and such"}, {"classified_as": "enhancement", "text": "In resogun, OpenGL shows some corruption where the bottom half of the screen is green. This is because the video player uploads the component textures separately, but 2 of the 3 channels have the wrong pitch encoded in the rsx::texture object. The textures in question are 8-bit single channel textures, but two of them give pitch() as double the width which makes no sense. Of course, setting the unpack settings to use the given width instead of pitch fixes this but I feel this is hacky.\n\n![resogun_good1](https://cloud.githubusercontent.com/assets/15904127/12962004/7f4d5586-d054-11e5-8bb6-28d1734247fc.PNG)\n"}, {"classified_as": "bug", "text": "**What is the current behavior?**\r\nLoading too slow\r\nScreen unresponsive\r\n\r\n**Steps to reproduce the problem**\r\n- Create 2 content types\r\n- Create relation between content types ( has many )\r\n- Seed with some items ( i'm trying with 10.000)\r\n- Navigate in content manager, select an item, wait for the results.\r\n\r\n**What is the expected behavior?**\r\nExpected a fast loading of the section, in fact the query is loading all documents. Too long, 2-3 minutes.\r\n\r\n**Suggested solutions**\r\nChecked: content-manager/explorer/{content-type}/{id}?source=content-manager\r\nIt is loading all documents from db, why is needed ?\r\n\r\n**Tested on**\r\nNode: 10.13.0\r\nStrapi: 3.0.0-alpha.14.5,15,16\r\nMongo: 3.6.3\r\nGoogle Chrome: 70.0.3538.110"}, {"classified_as": "bug", "text": "#### Steps to reproduce\r\n1. On a Jetpack site, install a plugin via zip (e.g. the Jetpack Beta Tester plugin).\r\n2. View Activity Log\r\n\r\n#### What I expected\r\nOne or two entries (e.g. Plugin Installed and Plugin Activated).\r\n\r\n\r\n#### What happened instead\r\nThe upload and deletion of the ZIP file are recorded.\r\n\r\n\r\n#### Browser / OS version\r\nJetpack 7.8 (master)\r\n\r\n#### Screenshot / Video\r\n![2019-09-18 at 14 27](https://user-images.githubusercontent.com/88897/65179442-6a601080-da20-11e9-865e-1657cca73212.jpg)\r\n\r\n\r\n\r\n#### Context / Source\r\n#reallife #dogfooding"}, {"classified_as": "bug", "text": "If you search for an empty string using contains, _all_ results should be returned, not none. That way this acts as a reductive filter:\r\n\r\nNULL = All results (50 results)\r\nD = Results with \"D\" (15 results)\r\nDi = Results with \"Di\" (3 results)\r\nDir = Results with \"Dir\" (1 result)"}, {"classified_as": "enhancement", "text": "My app hosted on NodeChef allows users to log in using Facebook through Parse however it sends a verification email with a link that does not work. Firstly, it should not be sending a verification email as they have logged in using Facebook. Can you please explain why this happens?\n- **Server**\n  NodeChef\n- **Database**\n  MongoDB on NodeChef\n"}, {"classified_as": "enhancement", "text": "The documented oauth2RedirectUrl option in swaggerUI doesn't actually get used in the /auth calls to the oauth2 provider.\n"}, {"classified_as": "enhancement", "text": "Repro:\r\n- replace this line https://github.com/polkadot-js/api/blob/master/packages/api/src/promise/types.d.ts#L10\r\nwith import { Codec } from '@polkadot/types/codec';\r\n- tsc --noEmit\r\n\r\nExpected:\r\nCompiler should throw, because the import does not exist.\r\n\r\nActual:\r\nIt passes."}, {"classified_as": "bug", "text": "In the WebSocket-Node\r\n\r\nhttps://github.com/frozeman/WebSocket-Node/blob/master/lib/WebSocketFrame.js#L256\r\n\r\nmaskKey = nullMask ? 0 : (Math.random()*0xFFFFFFFF) | 0;\r\n\r\nTo above out of range,change to\r\nmaskKey = nullMask ? 0 : ((Math.random() * 0xFFFFFFFF) >>> 0);\r\nor Update WebSocket-Node to the latest version?\r\n\r\nThx"}, {"classified_as": "enhancement", "text": "Currently the code relies on the class name\r\n\r\nhttps://github.com/polkadot-js/api/blob/90a2e26540b9800325e207c91b0b8d2556900fb4/packages/types/src/codec/EnumType.ts#L67\r\n\r\nHowever create-react-app prod build minifies the js code and mangle the class name (most of them end up been t), and breaks EnumType\r\n\r\n"}, {"classified_as": "enhancement", "text": "Almost all textures are black now.\n"}, {"classified_as": "bug", "text": "To reproduce:\r\n- open https://vuejs.org/v2/guide/forms.html#Multiline-text with IE 11.0 (Edge) on Windows 7\r\n- type some text in the textarea\r\n- move the cursor at the beginning of the text (press the Home key)\r\n- quickly type random chars\r\n=> the cursor jumps to the end\r\n\r\nsame issue with input type=text (https://vuejs.org/v2/guide/forms.html#Text)\r\n"}, {"classified_as": "enhancement", "text": "I paused this thing way back and it just keeps on syncing. New connections are prevented but existing ones are not terminated.\r\n\r\n<img width=\"571\" alt=\"Screenshot 2019-07-19 at 12 07 44\" src=\"https://user-images.githubusercontent.com/125426/61527971-f607f180-aa1d-11e9-8eca-37b996c8298a.png\">\r\n"}, {"classified_as": "enhancement", "text": "- swagger-ui version: v3.0.21\r\n\r\n\r\nswagger: '2.0'\r\ninfo:\r\n  version: \"1.0.0-alpha\"\r\n  title: Answer to life\r\n  description: |\r\n\r\n      # Documentation\r\n\r\n      This endpoint can solve the problems of the world:\r\n      [look at its specification](#/WorldEndpoint)\r\n\r\npaths:\r\n  #  endpoints\r\n  /:\r\n    get:\r\n      summary: the answer is 42\r\n      description: |\r\n        # Information\r\n          for understanding this endpoint you have to have a look at the\r\n          [Documentation](#/Documentation)\r\n      operationId: getanswer\r\n      tags:\r\n        - WorldEndpoint\r\n      responses:\r\n        200:\r\n          description: The api information is returned. \r\n\r\n\r\n\r\n\r\nUsing this example is impossible to have a normal navigation between the two generated paragraph.\r\n\r\nThe link from the \"Documentation\" section open a new tab/window.\r\nThe link from the endpoint it isn't referring the paragraph.\r\n\r\nAs a solution I would like to suggest these two things:\r\n\r\n- intercept the default href behaviour and add the \"preventdefault\" and the call to the \"scrolltosource\" (into the Markdown provider)\r\n- add ids to the h1 - h3 header in order to use the solution mentioned above.\r\n\r\nthe problem has been tested here: http://editor.swagger.io/#/"}, {"classified_as": "bug", "text": "A bare-bones Directus 8 project's GraphQL output looks fine in a viewer like iGraphQL, but throws all sorts of errors during compilation when importing the data into Gatsby via the gatsby-source-graphql plugin, as shown here:  \r\n\r\nError: Interface field Directus_Node.id expected but Directus_DirectusActivity does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusFileThumbnailItem does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_Metadata does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusCollection does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusCollectionItem does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusFieldItem does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusCollectionPreset does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusField does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusFile does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusFolder does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusPermission does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusRelation does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusRevision does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusRole does not provide it.  \r\nInterface field Directus_Node.id expected but Directus_DirectusSetting does not provide it.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_eq\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_neq\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_contains\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_ncontains\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_rlike\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_nrlike\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_empty\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_nempty\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_null\" does not.  \r\nNames must match /^[_a-zA-Z][_a-zA-Z0-9]*$/ but \"2fa_secret_nnull\" does not.  \r\nInterface field Directus_Node.id expected but Directus_DirectusUser does not provide it.  \r\n\r\nFor reference, in the gatsby plugin config I'm using a typeName of Directus and a fieldName of directus.\r\n\r\nHonestly, I don't know if this is a Directus issue or a Gatsby issue, although the GraphQL spec says that names shouldn't start with a number, hence all the 2fa errors above. I suspect that Gatsby requires a particular edge - node hierarchy that the GraphQL spec doesn't require and Directus doesn't provide, but that's just a guess.\r\n\r\n"}, {"classified_as": "bug", "text": "I am using Material Dialogs with RecyclerView and it got super weird on top and bottom. Check below comparison between before and now.\r\n\r\nMost of the code is really standard and [my app is open source](https://github.com/bernaferrari/ChangeDetection) (but I still haven't pushed the changes).\r\n\r\nxml\r\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n<android.support.v7.widget.RecyclerView xmlns:android=\"http://schemas.android.com/apk/res/android\"\r\n    xmlns:app=\"http://schemas.android.com/apk/res-auto\"\r\n    android:id=\"@+id/defaultRecycler\"\r\n    android:layout_width=\"match_parent\"\r\n    android:layout_height=\"match_parent\"\r\n    android:background=\"@color/windowBackground\"\r\n    app:layoutManager=\"android.support.v7.widget.LinearLayoutManager\" />\r\n\r\n\r\nkotlin\r\nval materialDialog = MaterialDialog(activity)\r\n            .customView(R.layout.recyclerview)\r\n            .noAutoDismiss()\r\n            .negativeButton(R.string.cancel) { it.dismiss() }\r\n            .positiveButton(R.string.save) { dialog ->\r\n                ...\r\n            }\r\n\r\n        materialDialog.getCustomView()?.findViewById<RecyclerView>(R.id.defaultRecycler)?.apply {\r\n            this.overScrollMode = View.OVER_SCROLL_NEVER\r\n            this.layoutManager = LinearLayoutManager(this.context)\r\n            this.adapter = GroupAdapter<ViewHolder>().apply {\r\n                add(dialogItemTitle)\r\n                add(Section(listOfItems))\r\n                add(dialogItemColorPicker)\r\n            }\r\n        }\r\n\r\n        materialDialog.show()\r\n\r\n0.96\r\n![screenshot_20180914-205837_change detection](https://user-images.githubusercontent.com/351125/45900425-23602080-bdb6-11e8-8af2-d5493fa0c86b.jpg)\r\n\r\n2.0\r\n![screenshot_20180921-154421_change detection](https://user-images.githubusercontent.com/351125/45900420-20fdc680-bdb6-11e8-9852-ce54cd5c27fd.jpg)\r\n"}, {"classified_as": "enhancement", "text": "Colons should not be encoded in URL path segments, according to https://tools.ietf.org/html/rfc3986#section-3.3"}, {"classified_as": "enhancement", "text": "I believe this issue has been there since the very early stage and not a regression from any recent PR.\r\nI also believe the same issue also occurs on ToCS1. \r\n\r\nIn some scenes, some of the objects (e.g. rooftops, the top of a train, top of a crate box) having abnormally high brightness. \r\nBelow is an example of those, where some carpets in the room are very bright (as if the sun was shining at it).\r\n![1](https://user-images.githubusercontent.com/6214348/59938317-3ad45300-9487-11e9-9ab0-55375f4ce15b.PNG)\r\n\r\nSince it doesn't really affect the gameplay and only cause very minor graphic issue, I didn't bother to raise it previously.\r\n\r\nEDIT: Let me know what is needed for debugging. Logs? renderdoc? "}, {"classified_as": "bug", "text": "console\r\n$ pwn checksec ./node/node-v12.16.3-linux-x64/bin/node\r\n[*] '/home/pdxjohnny/Downloads/node/node-v12.16.3-linux-x64/bin/node'\r\n    Arch:     amd64-64-little\r\n    RELRO:    Full RELRO\r\n    Stack:    Canary found\r\n    NX:       NX enabled\r\n    PIE:      No PIE (0x400000)  # <---- ASLR disabled\r\n\r\n\r\nI see there was some discussion on this back in 2016, but I couldn't really follow, it also looks like -pie still exists in some of the build files. Just wanted to report in case it's off by mistake."}, {"classified_as": "enhancement", "text": "I am not convinced this is correct - \r\n\r\nhttps://github.com/polkadot-js/api/blob/master/packages/types/src/codec/Enum.ts#L215-L225\r\n\r\nBasically, to determine equality, surely the index should match as well?  (At the very least when comparing 2 Enums, i.e. typeof Enum - which is actually missing here, unlike others)\r\n\r\nWe should also be able to compare 2 and enum against the JSON value\r\n\r\njs\r\nconst TEST_A = { a: 'test };\r\nconst TEST_B = { b: 'test };\r\n\r\nconst testA = new Enum({ a: Text, b: Text }, TEST_A);\r\nconst testB = new Enum({ a: Text, b: Text }, TEST_B);\r\n\r\nconsole.log(testA.eq(TEST_A)) // should be true\r\nconsole.log(testB.eq(TEST_A)) // should be false\r\nconsole.log(testA.eq(testB)) // should be false\r\nconsole.log(testA.eq('test')) // probably true as per current\r\n\r\n"}, {"classified_as": "bug", "text": "I use websocket (ws) coneection to Infura node \r\n\r\nweb3 = new Web3(new Web3.providers.WebsocketProvider(\"wss://ropsten.infura.io/ws\"));\r\n\r\nsometimes it's works fine or sometimes it give error on console : \r\n\r\nError: CONNECTION ERROR: Couldn't connect to node on WS.\r\n\r\nUncaught (in promise) Error: CONNECTION ERROR: Couldn't connect to node on WS.\r\n\r\nI am not getting why its happening.\r\n"}, {"classified_as": "bug", "text": "# Bug Report\r\n\r\nIf I send 1995-12-29T08:00+02:00 to the api, it saves 1995-12-29 08:00 disregarding the timezone."}, {"classified_as": "bug", "text": "<!--  If you do not respect this template your issue will be closed. -->\r\n\r\n<!--  Before writing your issue make sure you are using:-->\r\n<!-- Node 9.x.x -->\r\n<!-- npm 5.x.x -->\r\n<!-- The latest version of Strapi. -->\r\n\r\n**Informations**\r\n- **Node.js version**: 8\r\n- **npm version**: 5.8.0\r\n- **Strapi version**: 3.0.0-alpha.12\r\n- **Database**: mongo\r\n- **Operating system**: osx\r\n\r\n\r\n**What is the current behavior?**\r\n\r\nStrapi requires unstable versions of node.  Strapi should support the Long Term Support versions of nodejs.  Not the versions where bugs will never be fixed.  Until node 10 is LTS, you should support node 8.  \r\n\r\n**Steps to reproduce the problem**\r\n\r\nClose strapi cd admin npm i with node 8\r\n\r\n\r\n**What is the expected behavior?**\r\n\r\nLong term supported node should be supported, not experimental versions.\r\n\r\n\r\n**Suggested solutions**\r\n\r\nMake strapi accept node 8 since it is LTS. \r\n\r\n\r\n<!--  Make sure to browse the opened and closed issues before submit your issue. -->\r\n"}, {"classified_as": "bug", "text": "I'm trying to connect to my unsynced node with api 1.0.0-beta.17 \r\n\r\ntarget=#750431 (25 peers), best: #520014\r\n\r\nI'm getting \r\n![Screen Shot 2020-01-23 at 16 42 13](https://user-images.githubusercontent.com/3409250/72999295-74938080-3dff-11ea-9667-bd96dcc9c5bd.png)\r\n\r\nwhich is uncatchable with both of these\r\n\r\njavascript \r\ntry {\r\n  let api = await ApiPromise.create().catch(e => {})\r\n} catch (e) {}\r\n\r\n\r\nIt also doesn't emit error on \r\njavascript\r\nprovider.on('error',(e)=>{})\r\n\r\n\r\nIt results in stuck application since I can't react on anything that happened here. It also happens when you get error while connecting to wsprovider but it can be handled by wrapping api creation inside another promise, which I can reject. It is not ideal, but it works.\r\n\r\nWhen trying to connect to wss://cc3-5.kusama.network/ I get this on the other hand\r\n\r\n![Screen Shot 2020-01-23 at 16 41 42](https://user-images.githubusercontent.com/3409250/72999309-79583480-3dff-11ea-839f-8dc55b605d44.png)\r\n"}, {"classified_as": "bug", "text": "When writing Perl, I almost always fatalize warnings in the \"uninitialized\" category. Consider the following:\r\n\r\n\r\n$ perl -Mwarnings -e 'sub f { my %p = @_; \"$p{wrong_key}\"; }; f()'\r\nUse of uninitialized value $p{\"wrong_key\"} in string at -e line 1.\r\n\r\n\r\nThis is a good warning. Now, consider the following:\r\n\r\n\r\n$ perl -Mwarnings -e 'sub f { my %p = @_; map { \"$p{$_}\" } qw/wrong_key/; }; f()'\r\nUse of uninitialized value within %p in string at -e line 1.\r\n\r\n\r\nThis is a poor warning because it does not reveal the value of the key that was used to resolve the undefined value.\r\n\r\nNote that this ambiguity only arises where the key does not exist.\r\n\r\n\r\n$ perl -Mwarnings -e 'sub f { my %p = @_; map { \"$p{$_}\" } qw/key_for_undef/; }; f(key_for_undef => undef)'\r\nUse of uninitialized value $p{\"key_for_undef\"} in string at -e line 1.\r\n\r\n\r\nMy wish is that the offending key is reported in all cases."}, {"classified_as": "bug", "text": "subscribeNewHeads only works when the node runtime provides the session module. If this is not the case (when using Aura consensus for example) the method throws an error that api.query.session is undefined. "}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n#### Describe the bug\r\n\r\nAs my project has grown, I have seen the administration panel become slower and slower. Today I found one of the reasons: The auto population.\r\n\r\nFor example, if I have a Post model with an authors field.\r\nAnd this authors field is a relationship with the User model.\r\nWhen I create a new post, and search users in the authors dropdown, the query get **all** the user information, with their auto populated relations. And this is crazy! \ud83d\ude05 \r\n\r\nAnd it gets worse now when my User model has more than 10 relationships.\r\n\r\n#### Expected behavior\r\n\r\nJust request the minimum information: they key to show in the dropdown selector.\r\n\r\n#### System\r\n- Node.js version: v12\r\n- NPM version: v6\r\n- Strapi version: v3.0.0-beta.18.2\r\n- Database: MongoDB\r\n- Operating system: macOS\r\n"}, {"classified_as": "enhancement", "text": "rel/details: https://github.com/playproject-io/datdot-substrate/issues/18\r\n\r\nWhen we make the same extrinsic call using multiple accounts (calling signAndSend on the same extrinsic using multiple pairs) practically simultaneously, the callback object appears to return the same events for every call - when each call should in reality return unique events.\r\n\r\nHere is the exact code where this occurs:\r\n\r\nhttps://github.com/joshua-mir/datdot-service/blob/e5ee50b3b5080c9cafaae71cae9deff2e6ec249b/index.js#L175-L228\r\n\r\nI have confirmed that we see every expected event separately in the UI - so this appears to be an issue specific to events in callbacks."}, {"classified_as": "enhancement", "text": "When running discosrv and syncthing on the same machine the source address seen by discosrv for announcements is typically ::1 or 127.0.0.1. These addresses have zero chance of being useful to anyone else and should be filtered out. (In contrast this setup *could* work if the Syncthing device also announces a valid, static IP.)"}, {"classified_as": "enhancement", "text": "Firefox is resized to half of 1920x1080 screen.\n\n![screenshot](https://cloud.githubusercontent.com/assets/12888718/8152406/d0021866-1346-11e5-8b66-d77024557b9a.png)\n\nI suggest change overrides.css:248\n@media (max-width: 767px) {\nto\n@media (max-width: 1000px) {\n"}, {"classified_as": "bug", "text": "@afollestad \r\nIs there a problem with the latest build tools version, or did you just forget to update it? I noticed that our builds are still requiring the older version of build tools despite updating to latest material dialogs."}, {"classified_as": "enhancement", "text": "**Informations**\r\n- **Node.js version**: 10.9.0\r\n- **npm version**: 6.4.1\r\n- **Strapi version**: 3.0.0-alpha.14.5\r\n- **Database**: MongoDB v4.0.4\r\n- **Operating system**: Fedora 29\r\n\r\n\r\n**What is the current behavior?**\r\nThe UI shows a bad value for this parameter that the user has to add to the provider app setup: .../auth/twitter/callback. If the user add this one the process fails.\r\n![bad](https://user-images.githubusercontent.com/2753855/48787281-c7981200-ece8-11e8-9321-429929918a7a.png)\r\n\r\n**Steps to reproduce the problem**\r\nFollow the documentation to setup Twitter provider.\r\n\r\n\r\n**What is the expected behavior?**\r\nThe UI should should the correct value for this parameter: .../connect/twitter/callback\r\n![good](https://user-images.githubusercontent.com/2753855/48787376-ed251b80-ece8-11e8-8923-39244c2fc288.png)\r\n\r\nMoreover, this would be consistent with the URI provided by the rest of the providers.\r\n![google](https://user-images.githubusercontent.com/2753855/48787428-04fc9f80-ece9-11e8-8418-f1701721eefe.png)\r\n![fb](https://user-images.githubusercontent.com/2753855/48787434-0928bd00-ece9-11e8-8060-22174cfa5ab4.png)\r\n![discord](https://user-images.githubusercontent.com/2753855/48787444-0ded7100-ece9-11e8-9291-f80104a66295.png)\r\n\r\n**Suggested solutions**\r\nTo add a new case to cover Twitter in this switch statement: https://github.com/strapi/strapi/blob/17e2063943f5410fc014f6a95dfba30ec3ae8a93/packages/strapi-plugin-users-permissions/admin/src/components/PopUpForm/index.js#L45\r\n\r\nI'm sending a PR."}, {"classified_as": "enhancement", "text": "Got a javascript error that refreshNeed doesn't exist - cause is clearly #6452 thus it's RC material (forgot to take a screenshot, but it's trivial really)."}, {"classified_as": "enhancement", "text": "In SwaggerUIBundle,validatorUrl set it to false will disable validation is right.\r\n\r\nversion:3.0.6\r\n\r\n"}, {"classified_as": "enhancement", "text": "* **Version**: v11.15.0\r\n* **Platform**: Linux\r\n\r\nRun the following script with node --inspect script.js, connect a debugger with Google Chrome and instruct it to do a heap snapshot.\r\n\r\n**Edit:** See my comment below for a better snippet.\r\n\r\njs\r\nfunction memoryLeak() {\r\n    return new Promise(() => {});\r\n}\r\n\r\nfunction loop() {\r\n    for (let i = 0; i < 10000; i++) {\r\n        memoryLeak();\r\n    }\r\n\r\n    setTimeout(loop, 0);\r\n}\r\n\r\nloop();\r\n\r\n\r\nRoughly half of the time node will crash with \"pure virtual method called\".\r\n\r\nThat code actually causes a [memory leak](https://github.com/nodejs/node/issues/28787), but it will likely be annoying to debug if this isn't fixed first."}, {"classified_as": "enhancement", "text": "Hi,\r\n\r\nWhen creating PDFs from a responsive web page, lets say the page has a css rule to show a narrower version below 1024 pixels screen width and we supply width: \"1024px\" to pdf function. The rule should not apply on this case however it does and the layout changes in generated pdf. \r\n\r\nOnly when the width parameter is **4/3** of the actual width of viewport, then the pdf has exact same layout of given viewport width. This seems to be something related to an inches / points confusion somewhere (96 pixels per inch, 72 pixels per point. 96/72 = 4/3)\r\n\r\nSo, when I provide 1365px as pdf width I get the exact representation of the page at 1024px viewport width. Anything below 1365px, page acts like the viewport is below 1024px and applies the appropriate responsive css rules.\r\n\r\nI'm not sure if this is an upstream bug or something else though. Margins are set to 0 btw. \r\n\r\nAny ideas?"}, {"classified_as": "bug", "text": "There are 3 CI jobs marked continue-on-error which always pass. \r\n\r\nWould be nice if there was an additional cue in the UI about whether they failed or not."}, {"classified_as": "enhancement", "text": "When set page size in css using @page like\r\n\r\n  @page {\r\n    size: 50mm 50mm;\r\n  }\r\n\r\n page.pdf still output default A4 size pdf"}, {"classified_as": "enhancement", "text": "\r\nHello,\r\n\r\nIs there a REST endpoint for resending verification of emails?  I don't see anything in the documentation.\r\n\r\nThanks."}, {"classified_as": "bug", "text": "We should update our importing tests to not log URLs used in tests, as they are skewing our reporting.\r\n"}, {"classified_as": "enhancement", "text": "I had some things that could not be scanned (permission denied). I fixed those permissions and want to rescan. I cannot, manually:\r\n\r\n<img width=\"570\" alt=\"Screen Shot 2019-06-10 at 09 38 55\" src=\"https://user-images.githubusercontent.com/125426/59179891-b834c500-8b63-11e9-9b04-f93abd4a79ad.png\">\r\n\r\n(The Rescan button is disabled, presumably because the folder is not in one of the pre-approved scannable states?)\r\n"}, {"classified_as": "enhancement", "text": "This project needs a robust testing framework\n"}, {"classified_as": "bug", "text": "I have upgraded to 1.0.0-beta.49 in package.json ( \"web3\": \"1.0.0-beta.49\" )\r\n\r\nThe file node_modules/web3/dist/web3.cjs.js contains:\r\n\r\n...\r\nvar version = \"1.0.0-beta.48\";\r\n...\r\n\r\nSo when a create a provider, the version is 1.0.0-beta48. "}, {"classified_as": "bug", "text": "**Node.js version**: 8.9.0\r\n**npm version**: 5.5.1\r\n**Strapi version**: 3.0.0-alpha.8.3\r\n**Operating system**: Windows 7 (Enterprise)\r\n\r\nAfter creating my first content type, the homepage still displays the below message.\r\n\r\n![image](https://user-images.githubusercontent.com/1525669/35304968-7c01bf8a-008f-11e8-9a00-0c04ccf1b0c2.png)\r\n\r\n"}, {"classified_as": "enhancement", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\n\r\nReference from https://github.com/strapi/strapi/issues/4280#issuecomment-561102731\r\n\r\n**Steps to reproduce the behavior**\r\n\r\nCheck this queries. Whitespace issue?\r\n\r\n<img width=\"1215\" alt=\"Screenshot 2019-12-03 at 11 24 52\" src=\"https://user-images.githubusercontent.com/1007051/70042759-bb16ec80-15bf-11ea-8add-284442923e46.png\">\r\n<img width=\"1215\" alt=\"Screenshot 2019-12-03 at 11 26 50\" src=\"https://user-images.githubusercontent.com/1007051/70042820-d5e96100-15bf-11ea-92fd-f6893eed33e6.png\">\r\n<img width=\"1215\" alt=\"Screenshot 2019-12-03 at 11 25 29\" src=\"https://user-images.githubusercontent.com/1007051/70042761-bbaf8300-15bf-11ea-8f15-8e26153b3f1b.png\">\r\n\r\n**System**\r\n- Node.js version: v10\r\n- NPM version: v6\r\n- Strapi version: v3.0.0-beta.17.8\r\n- Database: MongoDB\r\n- Operating system: macOS\r\n"}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\n\ud83e\udd1e I'm not missing something but it looks like the current /change-password REST and/or the\r\nchangePassword GraphQL mutation actually is handling the **reset password** logic. \r\n\r\nTo fix this I'm proposing two things:\r\n1. rename current change-password logic to reset-password\r\n2. implement a new change-password mutation, for which I have a proposed PR, which I will reference in the comments shortly.\r\n\r\n**Expected behavior**\r\nFor the global self-isolation to end soon.\r\n\r\n**Proposed solution**\r\n**Follow the progress:** https://github.com/strapi/strapi/pull/5655\r\n\r\n**Inpired by**\r\nThe awesome PR https://github.com/strapi/strapi/pull/5580/ by @roelbeerens"}, {"classified_as": "enhancement", "text": "Hi there,\r\n\r\nit seems that RPCS3 seems to have a lot of problems with file paths when I try to use RetroArch PS3 on the emulator. RetroArch PS3 was made with the real PS3 SDK instead of PSL1GHT. \r\n\r\nVersion of RPCS3 used: **v0.0.4-6209-d8ae94df Alpha**\r\n\r\nFurther information provided - I use PSGL for graphics, I use stb_font for rendering the font glyphs, and I am using the runtime Cg compiler to load shaders on the fly from source.\r\n\r\nHere is a log file -\r\n\r\nhttps://hastebin.com/bosotizeca.js\r\n\r\nGraphics problems:\r\n* The icons don't show up, presumably because all the file system accesses are failing.\r\n* The font seems to be corrupted.\r\n\r\nThis is what it looks like right now -\r\n\r\n<img width=\"955\" alt=\"retroarchps3\" src=\"https://user-images.githubusercontent.com/1075274/33661579-d3e234be-da88-11e7-8856-b00478b683c7.png\">\r\n\r\nThis is how it should look like instead (screenshot taken on PC with Cg shader backend) -\r\n\r\n<img width=\"576\" alt=\"retroarchps3-pc\" src=\"https://user-images.githubusercontent.com/1075274/33661973-6405041c-da8a-11e7-85c6-eeeff2129dd7.png\">\r\n\r\n**How to test this**\r\n\r\nDownload the latest version of RetroArch for PS3 here -\r\n\r\nhttps://buildbot.libretro.com/stable/1.6.9/playstation/ps3/\r\n\r\nhttps://buildbot.libretro.com/stable/1.6.9/playstation/ps3/RetroArch.PS3.CEX.PS3.pkg\r\n\r\nNOTE - It seems RPCS3 isn't yet capable of dealing with DEX debug SELFs. Tried using it but I couldn't get it to boot up so I had to resort to the CEX build instead.\r\n\r\nInstall the pkg in RPCS3. Start it up. It should auto default to one core out of the package.\r\n\r\n**Source**\r\n\r\nAll of our source code for the PS3 port is publicly available on our repository -\r\n\r\nhttps://github.com/libretro/RetroArch\r\n\r\nLet me help you further along and point you to some of the PS3-specific code (beyond these files, all the normal codepaths that would normally get used on PC are used too here) -\r\n\r\n**File I/O code specific to PS3 **\r\n\r\nhttps://github.com/libretro/RetroArch/blob/master/frontend/drivers/platform_ps3.c\r\n\r\nThis file sets up all the filesystem paths - say, where to get the assets directory from, where to get the cores from, etc.\r\n\r\nhttps://github.com/libretro/RetroArch/blob/master/libretro-common/file/retro_dirent.c\r\n\r\nThis file has some PS3-specific code for iterating over files.\r\n\r\n**Graphics code specific to PS3 **\r\n\r\nhttps://github.com/libretro/RetroArch/blob/master/gfx/drivers/gl.c\r\n\r\nBasically the PS3 reuses the same GL driver as on PC. The only differences is that HAVE_PSGL, HAVE_OPENGLES are defined, so it employs some of the PSGL-optimized codepaths. For instance, it uses texture references which is some special construct available only in PSGL.\r\n\r\nMore PS3-specific code can be found in the renderchain file here -\r\n\r\nhttps://github.com/libretro/RetroArch/blob/master/gfx/drivers_renderchain/gl2_renderchain.c\r\n\r\nHopefully this information was helpful, and hopefully it will help make RPCS3 an even better PS3 emulator! I'd be very glad if we could start using RPCS3 as a debugger for our PS3 port personally."}, {"classified_as": "enhancement", "text": "Using the v0.0.6-7790 (19ff95da) Linux AppImage, RPCS3 hangs after printing the help or version information instead of exiting.\r\n\r\n\r\n$ ./rpcs3-v0.0.6-7790-19ff95da_linux64.AppImage --help\r\nUsage: rpcs3 [options] (S)ELF [Args...]\r\nWelcome to RPCS3 command line.\r\n\r\nOptions:\r\n  -h, --help     Displays this help.\r\n  -v, --version  Displays version information.\r\n\r\nArguments:\r\n  (S)ELF         Path for directly executing a (S)ELF\r\n  [Args...]      Optional args for the executable\r\n\r\n...\r\n*hangs forever*\r\n\r\n"}, {"classified_as": "enhancement", "text": "Wherever we build glob patterns based on existing file names we need to take care of the fact that they can contain things like [-] which gets interpreted as a broken character range.\n\nProbably we need a well tested utility function to build these patterns, or use something other than globbing.\n"}, {"classified_as": "bug", "text": "Currently, if CmaEsSampler is used with categorical variables, it throws this error\r\n\r\nThe parameter 'x' in trial#1 is sampled independently by using RandomSampler instead of CmaEsSampler (optimization performance may be degraded). You can suppress this warning by setting warn_independent_sampling to False in the constructor of CmaEsSampler, if this independent sampling is intended behavior.\r\n\r\nAs somebody who isn't familiar with the details of CmaEsSampler, I was not aware that it didn't work with categorical variables, and thought it was an issue with how I was setting the parameter ranges\r\n\r\nIf the CmaEsSampler is called with categorical variables, it should probably throw an error/warning upfront explaining the issue."}, {"classified_as": "enhancement", "text": "Hi,\n\nI took update of Swagger-UI today and found that I do not have Parameters section to give input values for GET resources.\n\nDo I need to change something to get this section back?\n\nThanks,\nKunjan\n"}, {"classified_as": "bug", "text": "**Node.js version**: 8.9\r\n\r\n**npm version**: 5.5\r\n\r\n**Strapi version**: 3.0.0-alpha.11.1\r\n\r\n**Operating system**: CentOS 7\r\n\r\nWhy Node 8.9 LTS is not compatible? Why you choose a non LTS version for the minimum requirement?\r\n\r\nThere are any known issues related to use strapi in node 8.9?\r\n"}, {"classified_as": "enhancement", "text": "if using ApiPromise, it can be easily reproduced by executing await api.derive.chain.bestNumber() and (await api.rpc.chain.getHeader()).blockNumber repeatedly.\r\n\r\nI think the current cache solution works only for rxjs because an observable is a stream, you still can get latest from it even you hold a cached one. but for promise it's one shot thing.\r\n\r\nwhen the observable is toPromised, it will be terminated after first result, makes caching it meaningless."}, {"classified_as": "bug", "text": "<!--\r\nThank you for reporting a possible bug in Node.js.\r\n\r\nPlease fill in as much of the template below as you can.\r\n\r\nVersion: output of node -v\r\nPlatform: output of uname -a (UNIX), or version and 32 or 64-bit (Windows)\r\nSubsystem: if known, please specify the affected core module name\r\n\r\nIf possible, please provide code that demonstrates the problem, keeping it as\r\nsimple and free of external dependencies as you can.\r\n-->\r\n\r\n* **Version**:\r\n\r\n13.3.0\r\n\r\n* **Platform**:\r\n\r\nLinux\r\n\r\n* **Subsystem**:\r\n\r\nDebian\r\n\r\n<!-- Please provide more details below this comment. -->\r\n\r\nIf I were to create a \"server\" for IPC using a named pipe like:\r\n\r\n\r\nconst ipc_server = net.createServer((c) => {\r\n        // 'connection' listener.\r\n        console.log('ipc client connected');\r\n        c.on('end', () => {\r\n                console.log('ipc client disconnected');\r\n        });\r\n        c.write('hello\\r\\n');\r\n        c.pipe(c);\r\n});\r\n\r\nipc_server.listen('/tmp/collect.sock', () => {\r\n        console.log('ipc connected at /tmp/pipe_name.sock');\r\n});\r\n\r\n\r\nThere are permission issues if I am accessing that named pipe from a process which has a different linux profile permission mask than the user which started the server.\r\n\r\nIt would be really nice to just have the ability to set the permissions on the named pipe file when creating the server with net.createServer().\r\n\r\nYou get something like this when trying to connect to the named pipe in a process ran by a user with different permissions on his account.\r\n\r\n\r\nipc client error { Error: connect EACCES /tmp/pipe_name.sock\r\n    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)\r\n  errno: 'EACCES',\r\n  code: 'EACCES',\r\n  syscall: 'connect',\r\n  address: '/tmp/pipe_name.sock' }\r\n"}, {"classified_as": "bug", "text": "We have a runtime method with the following signature:\r\n\r\n\r\nfn validate_mint(origin, anchor_id: T::Hash, deposit_address: [u8; 20], pfs: Vec<proofs::Proof>, static_proofs: [[u8;32];3]) -> Result {\r\n\r\n\r\nIt works well in unit tests, but polkadot-js seems to not like the type of static_proofs. The error I'm seeing when instanciating the API is:\r\n\r\n\r\n2019-12-19 20:08:22   API/DECORATOR: Error: FATAL: Unable to initialize the API: Expected '[' closing with ']'\r\n    at EventEmitter.Init._onProviderConnect (/Users/philipstanislaus/go/src/github.com/centrifuge/centrifuge-chain-functional-test/node_modules/@polkadot/api/base/Init.js:55:23)\r\n    at processTicksAndRejections (internal/process/task_queues.js:85:5)\r\n\r\n\r\nA workaround is to use \r\n\r\n\r\nInner: \u2018[u8;32]\u2019\r\nOuter: \u2018[Inner;3]\u2019\r\n"}, {"classified_as": "enhancement", "text": "This page I found on twitter does not work and returns 502\r\nhttps://blog.strapi.io/content-internationalization-with-strapi/\r\n\r\nTwitter link:\r\nhttps://twitter.com/strapijs/status/1041613814209421313?lang=en\r\n\r\nScreenshot:\r\n![image](https://user-images.githubusercontent.com/3635348/90511259-1a1f9000-e154-11ea-952d-b674a36ff5de.png)\r\n\r\n"}, {"classified_as": "bug", "text": "via V8 error definitions introduced in https://github.com/polkadot-js/api/pull/1441"}, {"classified_as": "enhancement", "text": "@polkadot/type-extrinsic: static.d.ts\r\n\r\nimport(\"../../types/src/primitive/Method\").ModulesWithMethods;\r\n\r\n\r\n@polkadot/api-derive: util/cached.d.ts:\r\n\r\nexport declare const cache: (fn: Function, map?: WeakMap<object, any>) => (api: import(\"../../../api/src/types\").ApiInterface$Decorated<import(\"rxjs\").Observable<import(\"../../../types/src/types\").Codec>, import(\"rxjs\").Observable<import(\"../../../types/src/types\").Codec>>) => any;\r\n"}, {"classified_as": "enhancement", "text": "Minor cosmetic bug: \r\nThere used to be a notification box to inform user that Syncthing has been shutdown. \r\nSince v1.2.0 it is gone and GUI looks like Syncthing still active.\r\n\r\nSteps to recreate: click shutdown in GUI"}, {"classified_as": "bug", "text": "![image](https://user-images.githubusercontent.com/14265482/44673665-d4f77600-a9f1-11e8-8db5-5bfaa75fa290.png)\r\n\r\n**Expected Result**\r\nThe console should log the dialog's message and type (in this case: the \"print screen\" dialog). I wanted to programmatically dismiss the print screen dialog.\r\n\r\n**What happens instead?**\r\nNothing happens\r\n\r\n**Environment:**\r\nPuppeteer version: 1.7.0\r\nPlatform / OS version: Mac OSX Version 10.13.6\r\nNode.js version: 10.7.0\r\n\r\n**Code** \r\npage = await browser.newPage();\r\npage.on(\"dialog\", async dialog => {\r\n   console.log(\"the dialog message is\", dialog.message());\r\n   console.log(\"the dialog type is\", dialog.type());\r\n   await dialog.dismiss();\r\n});\r\n\r\nawait page.waitFor('.print-text'); //this clicks an element and opens up the print screen in google chrome\r\nawait page.click('.print-text');\r\n\r\n\r\n\r\n"}, {"classified_as": "bug", "text": "- Fire browser.closed event when the underlying browser process gets closed / crashes\r\n- Fire page.closed event when the page gets closed / crashes\r\n\r\nThis will help to build reliable scripts that restart browser or reopen pages when they crash.\r\n"}, {"classified_as": "bug", "text": "Throw an exception when query failed due to a unique key duplication"}, {"classified_as": "enhancement", "text": "Maybe an improvement related to the swagger-ui,\nto be able to run in in IE i had to add this tag: in the index.html\n  &lt;meta http-equiv=\"X-UA-COMPATIBLE\" content=\"IE=Edge\"&gt;\n\nmaybe a small improvement?\n"}, {"classified_as": "enhancement", "text": "Hey,\r\nimage bellow for thousand words. I've listed the files manually and don't see discrepancy. Tried to restart services on both sides, to no avail.\r\n\r\nLet me know what additional information I should provide.\r\n\r\nThank you\r\n \r\n![Screenshot from 2020-04-23 08-10-21](https://user-images.githubusercontent.com/8431097/80065129-ea5fd300-8539-11ea-84ec-21eca056432f.png)\r\n\r\n\r\n"}, {"classified_as": "bug", "text": "### Description\r\n\r\nweb3.eth.ens.getContenthash does not return the decoded content as documented.\r\nNot clear if the doc or the behavior is wrong.\r\n\r\n#### Expected behavior\r\n\r\njavascript\r\nweb3.eth.ens.getContenthash('pac-txt.eth').then((result) => {\r\n    console.log(result);\r\n});\r\n> 'QmdTEBPdNxJFFsH1wRE3YeWHREWDiSex8xhgTnqknyxWgu'\r\n\r\n\r\n#### Actual behavior\r\n\r\njavascript\r\nweb3.eth.ens.getContenthash('pac-txt.eth').then((result) => {\r\n    console.log(result);\r\n});\r\n> '0xe30101701220e08ea2458249e8f26aee72b95b39c33849a992a3eff40bd06d26c12197adef16'\r\n\r\n"}, {"classified_as": "bug", "text": "**Possible improvement:**\r\n\r\nFirst: const signedTransaction = await web3.eth.accounts.signTransaction(tx, account.privateKey)\r\n\r\nThen doing the following does not work:\r\n\r\n  const receipt = await web3.eth.sendSignedTransaction(signedTransaction)\r\n\r\nThrows: Error: Returned error: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.\r\n\r\nThis works:\r\n\r\n  const receipt = await web3.eth.sendSignedTransaction(signedTransaction.rawTransaction)\r\n\r\n\r\nSeems a bit weird that you can't pass a signTransaction object to the sendSignedTransaction() method?\r\n\r\ncheers\r\n"}, {"classified_as": "enhancement", "text": "We're not using the API key properly or something;\r\n\r\n<img width=\"1814\" alt=\"screen shot 2018-10-30 at 05 30 34\" src=\"https://user-images.githubusercontent.com/125426/47696000-0284b980-dc05-11e8-8472-3f8c4b7661dd.png\">\r\n"}, {"classified_as": "enhancement", "text": "If we fail to rename a file (the last step when pulling it), the temp file is removed. It should instead be kept around as usual so we can reuse it.\n"}, {"classified_as": "bug", "text": "**Tell us about your environment:**\r\n\r\n* Puppeteer version: 1.0.0\r\n* Platform / OS version: Ubuntu 16.04\r\n* URLs (if applicable):\r\n* Node.js version: 6.12.3\r\n\r\n**What steps will reproduce the problem?**\r\n\r\n\r\nawait page.pdf({\r\n    headerTemplate: '',\r\n    footerTemplate: '',\r\n});\r\n\r\n\r\n**What is the expected result?**\r\n\r\nThe header and footer should be blank.\r\n\r\n**What happens instead?**\r\n\r\nThe default header and footer are still shown.\r\n\r\nIt seems that passing any falsey value results in the default template being used instead. I would suggest that only undefined should cause it to use the default template. Empty string, null, false and 0 should all override the default template.\r\n\r\nThanks.\r\n"}, {"classified_as": "enhancement", "text": "Cgo strictness is increased, resulting in Zillode/notify#9. Needs to be fixed for Go 1.10 release, preferably sooner rather than later."}, {"classified_as": "enhancement", "text": "We process incoming index updates according to the ignore patterns, to filter out unwanted entries. When ignore patterns changed to allow files that were previously filtered out things would be OK on the next index exchange / reconnect. Currently, there is no new index exchange so the new ignore patterns don't get matched against the remote index data.\n\nWe need to either save all the data and process it differently, or as a workaround drop the delta index data when ignore patterns change.\n"}, {"classified_as": "bug", "text": "<!-- BUG REPORT TEMPLATE -->\r\n### Vue.js version\r\n1.0.28\r\n\r\n### Reproduction Link\r\n<!-- A minimal JSBin, JSFiddle, Codepen, or a GitHub repository that can reproduce the bug. -->\r\n<!-- You could start with this template: http://jsfiddle.net/df4Lnuw6/ -->\r\nI've identified what is needed to fix the bug and I think, by inspection, it is the right thing to do.  Producing a fiddle to reproduce this is somewhat complex and seems out of proportion to the fix, however if I absolutely have to then I will.\r\n\r\n### Steps to reproduce\r\nWhere there is an app with dynamic elements with transitions defined with callback hooks on the transitions, open it in IE (tested in 11 and 9,10 through emulation.  No problem in other browsers)\r\n\r\n### What is Expected?\r\nThe transition completes with the hooks called at the right times.\r\n\r\n### What is actually happening?\r\nThe transition does not complete and an error is thrown in Vue: \"Invalid calling object\" on this code (which starts on line 37 src/transition.js, the error is thrown on line 40):\r\n\r\n\r\nconst raf = inBrowser && window.requestAnimationFrame\r\nconst waitForTransitionStart = raf\r\n  /* istanbul ignore next */\r\n  ? function (fn) { raf(function () { raf(fn) }) } //<-- error thrown here!\r\n  : function (fn) { setTimeout(fn, 50) }\r\n\r\n\r\nThe error seems to be because the requestAnimationFrame method of the window object is being called without its parent object.  \r\n\r\n### What seems to fix it?\r\nBy changing line 37 to\r\n\r\nconst raf = inBrowser && window.requestAnimationFrame.bind(window)\r\n\r\nthe error goes away.  Using bind seems, to me, obviously correct.  Clealy in other browsers because the default this is the window object anyway it should not matter, however IE seems to take a dislike to this approach and throw the error.  Binding window to the method would seem harmless otherwise.\r\n\r\nI'm an old-hand at coding but new to github (and relatively new to JS and vue) - The fix works but I don't really know if there are other reasons why this is not a good idea so I'm cautious about just closing it.\r\n"}, {"classified_as": "enhancement", "text": "Having error TS4020: 'extends' clause of exported class '...' has or is using private name 'EnumConstructor'. when i tried to create a class via extends Enum.with(...)\r\n\r\nexport EnumConstructor should solve my problem.\r\n"}, {"classified_as": "bug", "text": "It should save with type REVERT"}, {"classified_as": "enhancement", "text": "As discussed in the forums (https://forum.syncthing.net/t/security-warning/13843/):\r\n\r\nSince v1.3.0 the remote access warning considers the 'effective GUI listen address' to determine whether a warning should be shown.\r\n\r\nAs of now, this check only considers IP addresses 127./8, [::1] and unix sockets as local. Domain names/hostnames resolving to localhost such as 'localhost' are not considered local.\r\n\r\n>  https://forum.syncthing.net/t/security-warning/13843/8, calmh said:\r\n\r\n> Prior to 1.3.0 the warning was just based on the config value, even if overridden externally. In 1.3.0 it\u2019s based on the config or the overridden value but the logic is unchanged. The logic never accounted for names like \"localhost\".\r\n**What we should do is just get the address from the GUI listener, so we get in IP form whatever it actually ended up listening to.**\r\n\r\n### Version Information\r\n\r\nSyncthing Version: v1.3.0\r\n\r\nPS: I'm not really happy with the issue title, if somebody has a better wording please change.\r\n\r\n"}, {"classified_as": "bug", "text": "http://imgur.com/PzU7JZX\n\nToo much space?\n"}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\nWhen editing content of an entry through the Admin panel, if the user **accidentally** navigates to another page without saving the change, there is no prompt to warn them that the unsaved change will be lost. \r\n\r\n**Accidentally navigating to another page can easily happen, and it would be disappointing if a user has entered a lot of content, and losing them by this simple mistake.**\r\n\r\n**Steps to reproduce the behavior**\r\n1. Assuming the content type Restaurant exists, with a field called description for rich text description\r\n2. On the Admin Panel, navigate to \"Create an Entry\" for Restaurant\r\n3. Enter text to the description field, but **without clicking on the \"Save\" button**\r\n4. Navigate to another page within the Admin Panel, such as browsing to another content type through the sidebar. \r\n5. Observe that no warning or prompt is shown, but when coming back to \"Create an (restaurant) Entry\", the previously entered description is lost. \r\n\r\n**Expected behavior**\r\nA prompt is shown, such as \"Your unsaved content will be lost.\" With option to 1) \"Discard un-saved change\" (and proceed to where the user intended to go) or 2) \"Stay on the page\".\r\n\r\n**Screenshots**\r\nN/A.\r\n\r\n**Code snippets**\r\nN/A\r\n\r\n**System**\r\nDocker for Mac, Docker version 19.03.1, build 74b1e89\r\n\r\n**Additional context**\r\nN/A\r\n"}, {"classified_as": "enhancement", "text": "\n\u00b7! LDR: Title: flOw\n\u00b7! LDR: Serial: NPEA00021\n\nvm::g_base_addr = 000000007FFF0000\nvm::g_priv_addr = 000000017FFF0000\n\n\n\n\u00b7! LDR: Title: PIYOTAMA\u2122\n\u00b7! LDR: Serial: NPEA00065\n\nvm::g_base_addr = 000000007FFF0000\nvm::g_priv_addr = 000000017FFF0000\n\n\nBoth these games' render windows open with OpenGL.\nTrying to start them (and I believe it happens with a lot more games) with Vulkan crashes RPCS3 with an Unhandled exception.\nI wasn't able to catch any stack trace.\n"}, {"classified_as": "enhancement", "text": "I am using v0.11.2 on OSX. I was transferring a file of 25GB size, and the transfer had started during the creation of the file. The file size of the original file as well of the transferred file are identical, but the content has another md5 sum. How can this happen? Is there any way of how to prevent this?\nThanks!\n"}, {"classified_as": "bug", "text": "<!-- Please only use this template for submitting enhancement requests -->\r\n\r\n**What would you like to be added**:\r\n\r\nRemove/replace the \"kube-proxy-mode-detector\" mechanism used in the e2e test.\r\n\r\nhttps://github.com/kubernetes/kubernetes/blob/a017253ace9017bb8716b2d46b57467b2c73af29/test/e2e/network/service.go#L3679\r\n\r\n**Why is this needed**:\r\n\r\nThis is being used by some tests to detect the kube-proxy mode\r\n\r\nhttps://github.com/kubernetes/kubernetes/blob/a017253ace9017bb8716b2d46b57467b2c73af29/test/e2e/network/service.go#L976\r\n\r\nhttps://github.com/kubernetes/kubernetes/blob/a017253ace9017bb8716b2d46b57467b2c73af29/test/e2e/network/service.go#L3404\r\n\r\nIt basically creates a pod and exec a curl in a node to the http://localhost:10249/proxyMode\r\n\r\nTaken this job log as example \r\n\r\nhttps://storage.googleapis.com/kubernetes-jenkins/pr-logs/pull/91748/pull-kubernetes-e2e-gce/1270263772719616001/build-log.txt\r\n\r\n\r\n0609 08:31:38.940] [It] should preserve source pod IP for traffic thru service cluster IP [LinuxOnly]\r\nI0609 08:31:38.940]   test/e2e/network/service.go:976\r\nI0609 08:31:38.940] Jun  9 08:30:58.952: INFO: Running '/go/src/k8s.io/kubernetes/kubernetes/platforms/linux/amd64/kubectl --server=https://34.105.100.87 --kubeconfig=/workspace/.kube/config exec --namespace=services-5059 kube-proxy-mode-detector -- /bin/sh -x -c curl -q -s --connect-timeout 1 http://localhost:10249/proxyMode'\r\nI0609 08:31:38.941] Jun  9 08:31:02.417: INFO: stderr: \"+ curl -q -s --connect-timeout 1 http://localhost:10249/proxyMode\\n\"\r\nI0609 08:31:38.941] Jun  9 08:31:02.417: INFO: stdout: \"iptables\"\r\nI0609 08:31:38.941] Jun  9 08:31:02.417: INFO: proxyMode: iptables\r\nI0609 08:31:38.941] Jun  9 08:31:03.094: INFO: Waiting for pod kube-proxy-mode-detector to disappear\r\nI0609 08:31:38.941] Jun  9 08:31:03.440: INFO: Pod kube-proxy-mode-detector still exists\r\nI0609 08:31:38.941] Jun  9 08:31:05.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear\r\nI0609 08:31:38.942] Jun  9 08:31:06.156: INFO: Pod kube-proxy-mode-detector still exists\r\nI0609 08:31:38.942] Jun  9 08:31:07.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear\r\nI0609 08:31:38.942] Jun  9 08:31:07.706: INFO: Pod kube-proxy-mode-detector still exists\r\nI0609 08:31:38.942] Jun  9 08:31:09.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear\r\nI0609 08:31:38.942] Jun  9 08:31:09.856: INFO: Pod kube-proxy-mode-detector still exists\r\nI0609 08:31:38.943] Jun  9 08:31:11.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear\r\nI0609 08:31:38.943] Jun  9 08:31:11.934: INFO: Pod kube-proxy-mode-detector still exists\r\nI0609 08:31:38.943] Jun  9 08:31:13.440: INFO: Waiting for pod kube-proxy-mode-detector to disappear\r\nI0609 08:31:38.943] Jun  9 08:31:13.509: INFO: Pod kube-proxy-mode-detector no longer exists\r\nI0609 08:31:38.943] \u001b[1mSTEP\u001b[0m: creating a TCP service sourceip-test with type=ClusterIP in namespace services-5059\r\n\r\n\r\nIt takes about 15 seconds and it runs 3 times, so we can save some time ~45 secs"}, {"classified_as": "bug", "text": "Two days ago I spent quite some time debugging this code:\r\n\r\nperl\r\n# a lot of code\r\n\r\nmy $num = 0;\r\n\r\n# more code\r\n\r\nsub test {\r\n    # complex function\r\n\r\n    return (my $num = shift) ? $num : 0;\r\n}\r\n\r\n# ...\r\n\r\nsay test 4;  # 0\r\n\r\n# ...\r\n\r\n\r\nWhen I found the bug I initially thought that the issue was related to the ternary operator. But after creating an issue (#17795) I learned that you cannot use variables on the same expression they are declared, excerpt shared by @Grinnz from the [documentation](https://perldoc.perl.org/perlsub.html#Private-Variables-via-my()):\r\n> The declared variable is not introduced (is not visible) until after the current statement.\r\n\r\nCurrently these will generate a compilation error under strict (Global symbol \"$n\" requires explicit package name) and a warning under warnings (Name \"main::n\" used only once: possible typo):\r\n\r\nperl\r\n(my $n = shift) ? $n : 0; \r\n\r\nif ((my $n) || !!$n) { $n } else { 0 }\r\n\r\n\r\nBut this will only generate a compilation error under strict (nothing with warnings):\r\n\r\nperl\r\n((my $n) || !!$n) ? $n : 0;  # Perl thinks it's fine when not using strict\r\n\r\n\r\nAnyways, if you do something like the code I showed on the first example, Perl won't warn you nor generate a compilation error and will probably do what you did not mean to do:\r\n\r\nperl\r\nmy $num = 0;\r\n{\r\n    local @_ = 10;\r\n    (my $num = shift) ? $num : 0;                         # 0\r\n}\r\n{\r\n    local @_ = 10;\r\n    if ((my $num = shift) && !!$num){ $num } else { 0 };  # 0\r\n}\r\n\r\n\r\nand I can say first hand that finding this bug is something really time-consuming with no pragma nor Deparse to help you.\r\n\r\nI'd like to see a warning here saying that you are using a variable on the same statement you are lexically masking it.\r\n\r\nThough I see that this warning would also appear on the likely more common case:\r\n\r\nperl\r\nlocal @_ = @_;\r\nlocal $_ = $_;\r\n# and so\r\n"}, {"classified_as": "bug", "text": "![image](https://user-images.githubusercontent.com/9141017/42243637-46c632e0-7f12-11e8-88f2-4069469289e2.png)\r\n"}, {"classified_as": "enhancement", "text": "Not able to decode DigestItem that returned from RPC\r\n\r\nRelated: https://github.com/paritytech/substrate/pull/1478\r\n\r\nI think the JSON codec needs some better thoughts to avoid those breaking changes"}, {"classified_as": "enhancement", "text": "Since samba does not support fsync on directories the syncthing daemon gives a lot of \"invalid argument\" error. It would be great if fsync could be disabled/ignored for directories. \r\nI think this behaviour is already the default case for windows (5ec1490), but I would like to use it on Linux.\r\n\r\nSyncthing Version: v0.14.39\r\nOS Version: Linux / Ubuntu 17.04\r\n"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nIm adding content to the strapi server and its getting really slow. \r\ni do have 67 elements and the api response time is about 9-12 seconds\r\n\r\nthe content type does not have any relational content. is like this:\r\n- 1 enum\r\n- 2 booleans\r\n- image\r\n- repeatable content with 2 images. (usually 10-15 components each)\r\n\r\nIm just trying to get all the content in the api call.\r\n\r\n**Expected behavior**\r\nNot to take seconds on the api response\r\n\r\n**Screenshots**\r\nN/A\r\n**Code snippets**\r\nN/A\r\n\r\n\r\n**System**\r\n- Node.js version: 12.14.1\r\n- NPM version: 6.13.4\r\n- Strapi version: v3.0.0-beta.18.7\r\n- Database: mongodb\r\n- Operating system: ubuntu 18.04\r\n\r\nWhen the Strapi admin panel list the items its also slow, probably the same time (9-12 seconds)\r\n\r\n"}, {"classified_as": "bug", "text": "Hi,\r\nI'm creating an extension class which will be called from Directus hook. Some code logic is omitted for simplicity.\r\npublic/extensions/custom/hooks/presentations/AfterCreatePresentation.php \r\nphp\r\n<?php\r\n\r\nnamespace Directus\\Custom\\Hooks\\Presentations;\r\n\r\nuse Directus\\Application\\Application;\r\nuse Directus\\Mail\\Message;\r\nuse function Directus\\send_mail_with_layout;\r\nuse Directus\\Services\\UsersService;\r\n\r\nclass AfterCreatePresentation\r\n{\r\n    protected $container = null;\r\n\r\n    public function __invoke($data = null)\r\n    {\r\n        $this->container = Application::getInstance()->getContainer();\r\n        $userService = new UsersService($this->container);\r\n        $users = $userService->findAll();\r\n\r\n        foreach ($users['data'] as $user) {\r\n            if ($user['email_notifications'] == true){\r\n                send_mail_with_layout(\r\n                  ...\r\n                );\r\n            }\r\n        }\r\n    }\r\n}\r\n\r\n\r\nAnd the hook is registered in config/api.php as:\r\nphp\r\n...\r\n    'hooks' => [\r\n        'actions' => [\r\n            'item.create.presentations' => new \\Directus\\Custom\\Hooks\\Presentations\\AfterCreatePresentation()\r\n        ],\r\n        'filters' => [],\r\n    ],\r\n...\r\n\r\nHowever the following error is being thrown:\r\n\r\n2018/12/20 14:32:07 [error] 10498#10498: *123657 FastCGI sent in stderr: \"PHP message: PHP Fatal error:  Uncaught Error: Class 'Directus\\Custom\\Hooks\\Presentations\\AfterCreatePresentation' not found in /var/www/api.elisiondesign.cz/config/api.php:114\r\nStack trace:\r\n#0 /var/www/api.elisiondesign.cz/src/web.php(43): require()\r\n#1 /var/www/api.elisiondesign.cz/public/index.php(3): require('/var/www/api.el...')\r\n#2 {main}\r\n  thrown in /var/www/api.elisiondesign.cz/config/api.php on line 114\" while reading response header from upstream, client: 89.102.32.192, server: api.elisiondesign.cz, request: \"GET /server/ping HTTP/1.1\", upstream: \"fastcgi://unix:/run/php/php7.0-fpm.sock:\", host: \"api.elisiondesign.cz\", referrer: \"https://app.elisiondesign.cz/\"\r\n\r\n**It works perfectly on my system MacOS**, but when deployed to production (Ubuntu) it throws the error.  I was tying to figure out some differences between the system and the most important is that Ubuntu is **case-sensitive** system, while MacOs is not. This would explain the not found problem.  So I've tried to put the file in the folders named with uppercase /Custom/Hooks/Presentations to help the autoloader find the class in the namespace, but with no effect. \r\n\r\n**NOTE:** The example hook for 'products' throws the same error when enabled.\r\n\r\n- OS: [Ubuntu 16.04]\r\n- Web Server: [nginx/1.14.1 ]\r\n- PHP Version: [ 7.0.32]\r\n- Database: [ MySQL 5.7.24]\r\n- API [2.0.12]\r\n"}, {"classified_as": "bug", "text": "Create GET /debug endpoint which returns the below info.\r\n\r\n1. Server OS and version\r\n2. PHP version\r\n3. MySQL version\r\n4. PHP extension (pdo, mysql, curl, gd, fileinfo, libapache2-mod-php and mbstring)\r\n5. if applicable, mod_rewrite enable.\r\n5. Public directory permission\r\n6. Log directory permission\r\n7. /public/uploads directory permission\r\n8. API version\r\n9. APP version\r\n10. Max file upload size\r\n11. Browser OS (Either server will try to detect from header or App will add in additional of the server response)\r\n12. Cache driver, if Cache enable\r\n13. Storage driver\r\n14. Log path\r\n15. App environment "}, {"classified_as": "enhancement", "text": "Hi,\n\n**Question:** Is Syncthing using a proper address for IPv6 mulitcast?\n\n**Background:**\nI'm working with @dapperstout on the Swift implementation of syncthing. Because I'm having trouble getting IPv6 multicast to work, I posted a question about it on stack overflow: http://stackoverflow.com/questions/31574247/gcdasyncudpsocket-cannot-get-udp-multicast-over-ipv6-to-work?noredirect=1#comment51108878_31574247. I don't know too much about IPv6 yet, but on stack overflow it is claimed that the Syncthing multicast address (ff32::5222), as specified in https://github.com/syncthing/specs/blob/master/DISCOVERYv2.md, is reserved for future use (referring to http://www.iana.org/assignments/ipv6-multicast-addresses/ipv6-multicast-addresses.xhtml#unicast-multicast-group-ids). \n\nCould someone with enough knowledge on this have a look at it? If this is a bug in the specification, it would be good to fix it.\n"}, {"classified_as": "enhancement", "text": "Tracker for any regressions introduced after merging https://github.com/RPCS3/rpcs3/pull/3458\r\n\r\n- [x] Strict rendering mode causes hangs\r\n- [x] Vulkan leaks memory when running Trails Of Cold Steel 2\r\n- [x] Poor performance in some games"}, {"classified_as": "enhancement", "text": "\r\n# Error\r\n\r\nI went to go bump substrate-api-sidecar's @polkadot/api from 1.29.1 to 1.30.0-beta.6 and started encountering errors starting with createType(SignedBlock) on older Kusama blocks that do not occur when I go back to 1.29.1.\r\n\r\nlocalhost:8080/block/900 -> createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Maximum call stack size exceeded\r\n\r\nAnd in the terminal Sidecar logs: 2020-08-23 16:16:32        RPC-CORE: getBlock(hash?: BlockHash): SignedBlock:: createType(SignedBlock):: Struct: failed on 'block':: Struct: failed on 'extrinsics':: createType(ExtrinsicV4):: createType(ExtrinsicSignatureV4):: Maximum call stack size exceeded.\r\n\r\nI think the error originates from this call to getBlock: https://github.com/paritytech/substrate-api-sidecar/blob/master/src/services/blocks/BlocksService.ts#L42\r\n\r\n# How to produce error\r\n\r\nTo recreate the error (you will have to install wasm-pack if you don't already have it):\r\n\r\ngit clone https://github.com/paritytech/substrate-api-sidecar.git\r\ngit checkout zeke-1-3-b # commit e0402f1\r\nyarn\r\nSAS_SUBSTRATE_WS_URL=wss://kusama-rpc.polkadot.io yarn start\r\n\r\nand then curl localhost:8080/block/900 or any other lower number block to get the above errors.\r\n\r\n# How to produce expected behavior\r\n\r\nTo get the expected behavior\r\n\r\ngit checkout master # commit c354be3\r\nyarn\r\nSAS_SUBSTRATE_WS_URL=wss://kusama-rpc.polkadot.io yarn start\r\n\r\nand then curl localhost:8080/block/900 or any other valid block number to get a 200 response.\r\n\r\n### Other notes\r\n\r\n- I get the same errors with wss://cc3-5.kusama.network\r\n- I don't get the error with curl localhost:8080/block/0, presumably because it has no extrinsics\r\n- I don't get similar errors with wss://rpc.polkadot.io"}, {"classified_as": "enhancement", "text": "Affected games - Bayonetta (BLES00599) and Hyperdimension Neptunia (BLUS30701). Before PR #1415 changes there was appears assertion failures (line 108 in D3D12Texture.cpp, and line 103 in D3D12MemoryHelpers.h), but it was possible to skip them and get further. Now renderer window just silently hangs without any messages, and both games got regressions. In Bayonetta it's no longer possible to get into menu (and ingame using save from PS3), Hyperdimension Neptunia hangs in the middle of dialog scene.\n"}, {"classified_as": "enhancement", "text": "Making a PUT request to our goal class https://ourparse/classes/Goal/<goalid> with the following data:\n\n js\n{\n    \"name\":\"lol\",\n    \"startTime\":{\"__type\":\"Date\",\"iso\":\"2016-06-06T07:00:45.653Z\"},\n    \"group\":{\"__type\":\"Pointer\",\"className\":\"Group\",\"objectId\":\"LhQclT1kTc\"},\n    \"type\":\"event\",\n    \"externals\":[]\n}\n\n\nReturns this:\n\n\n{\n  \"code\": 111,\n  \"error\": \"schema mismatch for Goal.updatedAt; expected Date but got String\"\n}\n\n\nWe should look into why that might be the case.\n"}, {"classified_as": "bug", "text": "#### Expected behavior\r\n\r\nwallet can be encrypted to keyStore with aes-256-ctr algorithm\r\n\r\n#### Actual behavior\r\n\r\nbrowserify-cipher throw an error:\r\n\r\nbash\r\nError: Invalid key length\r\n    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)\r\n    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:115:20)\r\n    at new Cipheriv (internal/crypto/cipher.js:217:22)\r\n    at Object.createCipheriv (crypto.js:109:10)\r\n    at Accounts.encrypt (/Users/young/Documents/eth/web3.js/node_modules/web3-eth-accounts/src/index.js:406:23)\r\n    at Object.encrypt (/Users/young/Documents/eth/web3.js/node_modules/web3-eth-accounts/src/index.js:112:22)\r\n\r\n\r\n#### Steps to reproduce the behavior\r\n\r\nwith the code \r\n\r\njavascript\r\nconst Web3 = require('web3');\r\nconst web3 = new Web3(Web3.givenProvider || \"ws://localhost:8545\");\r\nconst wallet = web3.eth.accounts.create();\r\nwallet.encrypt('12345678', {cipher: 'aes-256-ctr'})\r\n\r\n\r\n#### Logs\r\n\r\n#### Versions\r\nNode: 10.16.0\r\nSystem: macos\r\n![image](https://user-images.githubusercontent.com/52150262/72801091-c31c1000-3c83-11ea-8f29-b8642043df17.png)\r\n\r\n#### Reasons\r\n1. in this [file](https://github.com/ethereum/web3.js/blob/1.x/packages/web3-eth-accounts/src/index.js#L414), the cipher key length has been limited in 16, it should be 32 if cipher is aes-256-ctr\r\n"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nOn the Media Library plugin, when you start typing the search criteria into the \"Search for an asset\" field, the search is triggered after just one character, and the page refreshes, making the field to lose focus. This is very annoying behavior.\r\n\r\n**Steps to reproduce the behavior**\r\n\r\n1. Go to Media Library.\r\n2. Click on \"Search for an asset\".\r\n3. Start typing the search criteria.\r\n4. The page reloads after each typed character, and the field loses focus.\r\n\r\n**Expected behavior**\r\nThe \"Search for an asset\" field should keep focus.\r\n\r\n**Screenshots**\r\nN/A.\r\n\r\n**Code snippets**\r\nN/A.\r\n\r\n**System**\r\n\r\n- Node.js version: v12\r\n- NPM version: N/A\r\n- Strapi version: 3.0.1\r\n- Database: Postgres\r\n- Operating system: Linux\r\n\r\n**Additional context**\r\nN/A.\r\n"}, {"classified_as": "bug", "text": "**Description**\r\n\r\nThe perlop docs describe the current behavior, so this doesn't contradict anything.\r\n\r\nA chained comparison in 5.31.10 appears to evaluate the middle condition twice for a tied scalar but doesn't warn about it. Since a programmer might not realize they are using a tied variable, they might see odd behavior. \r\n\r\n**Steps to Reproduce**\r\n\r\n\tuse v5.31.10;\r\n\r\n\tpackage UnstableScalar {\r\n\t\tuse parent qw(Tie::Scalar);\r\n\t\tsub TIESCALAR { bless {}, $_[0] }\r\n\t\tsub FETCH {\r\n\t\t\tmy $value = int rand 10;\r\n\t\t\tsay \"Fetching scalar with $value\";\r\n\t\t\treturn $value;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\ttie my $unstable, 'UnstableScalar';\r\n\r\n\tif( 5 < $unstable < 9 ) {\r\n\t\tsay \"Found a value between 5 and 9\";\r\n\t\t}\r\n\r\nThe comparison short circuits just fine, but if the first comparison is true, the tied scalar is evaluated again (so things such as Tie::Cycle will unexpectedly progress or skip values):\r\n\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 2\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 0\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 9\r\nFetching scalar with 2\r\nFound a value between 5 and 9\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 6\r\nFetching scalar with 9\r\n\r\n\r\n**Expected behavior**\r\n\r\nI expect that the scalar would only call FETCH once and reuse the result in the second comparison. perlop says this may happen, but perhaps a warning would be useful here. Ideally, tied variables would be evaluated once.\r\n\r\nIs there a chance that the internals could recognize this and use the tied object instead of the scalar itself? This works as expected:\r\n\r\n\r\n\tif( 5 < tied($unstable)->FETCH < 9 ) {\r\n\t\tsay \"Found a value between 5 and 9\";\r\n\t\t}\r\n\r\n \r\n**Perl configuration**\r\n<!-- Please paste perl -V output just below. -->\r\n\r\nSummary of my perl5 (revision 5 version 31 subversion 10) configuration:\r\n\r\n  Platform:\r\n\tosname=darwin\r\n\tosvers=19.3.0\r\n\tarchname=darwin-2level\r\n\tuname='darwin otter.local 19.3.0 darwin kernel version 19.3.0: thu jan 9 20:58:23 pst 2020; root:xnu-6153.81.5~1release_x86_64 x86_64 '\r\n\tconfig_args='-des -Dprefix=/usr/local/perls/perl-5.31.10 -Dusedevel'\r\n\thint=recommended\r\n\tuseposix=true\r\n\td_sigaction=define\r\n\tuseithreads=undef\r\n\tusemultiplicity=undef\r\n\tuse64bitint=define\r\n\tuse64bitall=define\r\n\tuselongdouble=undef\r\n\tusemymalloc=n\r\n\tdefault_inc_excludes_dot=define\r\n\tbincompat5005=undef\r\n  Compiler:\r\n\tcc='cc'\r\n\tccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.15 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'\r\n\toptimize='-O3'\r\n\tcppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.15 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'\r\n\tccversion=''\r\n\tgccversion='4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)'\r\n\tgccosandvers=''\r\n\tintsize=4\r\n\tlongsize=8\r\n\tptrsize=8\r\n\tdoublesize=8\r\n\tbyteorder=12345678\r\n\tdoublekind=3\r\n\td_longlong=define\r\n\tlonglongsize=8\r\n\td_longdbl=define\r\n\tlongdblsize=16\r\n\tlongdblkind=3\r\n\tivtype='long'\r\n\tivsize=8\r\n\tnvtype='double'\r\n\tnvsize=8\r\n\tOff_t='off_t'\r\n\tlseeksize=8\r\n\talignbytes=8\r\n\tprototype=define\r\n  Linker and Libraries:\r\n\tld='cc'\r\n\tldflags =' -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib'\r\n\tlibpth=/usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib /usr/lib\r\n\tlibs=-lpthread -ldbm -ldl -lm -lutil -lc\r\n\tperllibs=-lpthread -ldl -lm -lutil -lc\r\n\tlibc=\r\n\tso=dylib\r\n\tuseshrplib=false\r\n\tlibperl=libperl.a\r\n\tgnulibc_version=''\r\n  Dynamic Linking:\r\n\tdlsrc=dl_dlopen.xs\r\n\tdlext=bundle\r\n\td_dlsymun=undef\r\n\tccdlflags=' '\r\n\tcccdlflags=' '\r\n\tlddlflags=' -mmacosx-version-min=10.15 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'\r\n\r\n\r\nCharacteristics of this binary (from libperl): \r\n  Compile-time options:\r\n\tHAS_TIMES\r\n\tPERLIO_LAYERS\r\n\tPERL_COPY_ON_WRITE\r\n\tPERL_DONT_CREATE_GVSV\r\n\tPERL_MALLOC_WRAP\r\n\tPERL_OP_PARENT\r\n\tPERL_PRESERVE_IVUV\r\n\tPERL_USE_DEVEL\r\n\tPERL_USE_SAFE_PUTENV\r\n\tUSE_64_BIT_ALL\r\n\tUSE_64_BIT_INT\r\n\tUSE_LARGE_FILES\r\n\tUSE_LOCALE\r\n\tUSE_LOCALE_COLLATE\r\n\tUSE_LOCALE_CTYPE\r\n\tUSE_LOCALE_NUMERIC\r\n\tUSE_LOCALE_TIME\r\n\tUSE_PERLIO\r\n\tUSE_PERL_ATOF\r\n  Built under darwin\r\n  Compiled at Mar 27 2020 01:45:56\r\n  %ENV:\r\n\tPERL=\"/Users/brian/bin/perls/perl-latest\"\r\n\tPERL5_PATH=\"/Users/brian/bin/perls\"\r\n\tPERL6_PATH=\"/Users/brian/bin/perl6s:/Applications/Rakudo/bin:/Applications/Rakudo/share/perl6/site/bin\"\r\n\tPERLDOTCOM_AUTHOR=\"brian d foy\"\r\n  @INC:\r\n\t/usr/local/perls/perl-5.31.10/lib/site_perl/5.31.10/darwin-2level\r\n\t/usr/local/perls/perl-5.31.10/lib/site_perl/5.31.10\r\n\t/usr/local/perls/perl-5.31.10/lib/5.31.10/darwin-2level\r\n\t/usr/local/perls/perl-5.31.10/lib/5.31.10\r\n\r\n"}, {"classified_as": "enhancement", "text": "I have several operations defined in my api's with an httpMethod of POST, and in my index.html the supportedSubmitMethods array does contain 'post', however when I attempt to test these endpoints, they are sent via a GET ajax request, not a POST.\n\nIs there any other requirements to get them to be submitted as a POST request? For instance these operations do include some \"query\" type parameters, as I want them in the query string, not the post data - but that shouldn't prevent it from being a POST request should it?\n"}, {"classified_as": "enhancement", "text": "It looks like trackStatus inside send() is being called twice. "}, {"classified_as": "enhancement", "text": "v1.0.0-rc  page.waitForNavigation()\r\n\r\nsetting timeout:0 should disable timeout according to the docs (meaning it never times out), but it seems to just actually set it to 0 seconds, and then promise reverts to null immediately everytime.\r\n"}, {"classified_as": "enhancement", "text": "The links in https://github.com/polkadot-js/api/blob/master/packages/api/README.md are broken, referencing a substrate folder that does not exist. Maybe should point to api/docs? Unsure otherwise I would've fixed it."}, {"classified_as": "bug", "text": "**Describe the bug**\r\nUsing strapi cli to generate an api with an attribute of type relation leads to an error. In https://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/lib/before.js on line 92 the attributes are insert as \"type\", but the type relation should use the keyword \"model\". Additionally, there isn't any validation on the type attribute to verify, of this type (or model) exists.\r\n\r\n**Steps to reproduce the behavior**\r\n1. strapi generate:api person name:string\r\n2. strapi generate:api location owner:person\r\n3. Go to Content Type Builder location and have a look on the field (screenshot attached) \r\n\r\n**Expected behavior**\r\nThe api location is generated with an attribute called owner of type relation to person. \r\n\r\n**Screenshots**\r\n<img width=\"1159\" alt=\"Bildschirmfoto 2019-12-10 um 12 36 09\" src=\"https://user-images.githubusercontent.com/32730503/70526348-ae5b4100-1b49-11ea-9411-0d56fc67f756.png\">\r\n\r\n\r\n**Code snippets**\r\nhttps://github.com/strapi/strapi/blob/master/packages/strapi-generate-api/lib/before.js\r\n\r\n\r\nscope.attributes = scope.args.attributes.map(attribute => {\r\n    if (_.isString(attribute)) {\r\n      const parts = attribute.split(':');\r\n\r\n      parts[1] = parts[1] || 'string';\r\n\r\n      // Handle invalid attributes.\r\n      if (!parts[1] || !parts[0]) {\r\n        invalidAttributes.push(\r\n          'Error: Invalid attribute notation ' + attribute + '.'\r\n        );\r\n        return;\r\n      }\r\n\r\n      return {\r\n        name: _.trim(_.deburr(parts[0].toLowerCase())),\r\n        params: {\r\n          type: _.trim(_.deburr(parts[1].toLowerCase())),\r\n        },\r\n      };\r\n    } else {\r\n      return _.has(attribute, 'params.type') ? attribute : undefined;\r\n    }\r\n  });\r\n\r\n\r\n**System**\r\n- Docker Image: strapi/strapi\r\n- Node.js version: v12.13.0\r\n- Strapi version: 3.0.0-beta.17.8\r\n- Database: postgres\r\n\r\n**Additional context**\r\nI'm not sure, if this is only an error or also a feature request - i would really like to use the cli for api generation including attributes of type relation to bootstrap strapi applications in microservice environments. If helpful, I could also include my init scripts for bootstraping json apis in docker containers.\r\n"}, {"classified_as": "enhancement", "text": "**Informations**\r\n- **Node.js version**: v11.6.0\r\n- **NPM version**: v6.9.0\r\n- **Strapi version**: 3.0.0-alpha.24.1\r\n- **Database**: MongoDB\r\n- **Operating system**: MacOS\r\n\r\n**What is the current behavior?**\r\nWhen I have a good number of users (let's say +6000 users) assigned to the Authenticated role I can't modify the Roles & Permissions for that specific Role due to the next error:\r\n\r\nFailed to load resource: the server responded with a status of 413 (Request Entity Too Large)\r\n\r\nAnd I suppose that this is due to the body of the request because we are sending all the users in the request:\r\n\r\n{\r\n  description: \"Default role given to authenticated user.\"\r\n  name: \"Authenticated\",\r\n  permissions: { ... },\r\n  users: [ ... ] (array with more than 6000 objects)\r\n}\r\n\r\n\r\n**Steps to reproduce the problem**\r\n- Have 6000 users assigned to Authenticated role.\r\n- Modify the permissions of Authenticated role.\r\n"}, {"classified_as": "bug", "text": "\r\n\"SQLSTATE[01000]: Warning: 1265 Data truncated for column 'official_site' at row 1\"\r\n\r\n\r\nPATCH http://localhost/api/public/_/fields/movies/official_site\r\n\r\njson\r\n{\"id\":165,\"sort\":12,\"field\":\"official_site\",\"type\":\"VARCHAR\",\"interface\":\"text-input\",\"default_value\":null,\"options\":{\"iconLeft\":\"link\"},\"readonly\":false,\"required\":false,\"unique\":false,\"note\":null,\"hidden_input\":false,\"hidden_list\":false,\"length\":100,\"validation\":null}\r\n"}, {"classified_as": "enhancement", "text": "Minified -\r\n\r\n<img width=\"184\" alt=\"polkadot apps portal 2019-01-08 12-45-17\" src=\"https://user-images.githubusercontent.com/1424473/50830049-db561100-1346-11e9-8350-701080c49713.png\">\r\n\r\nUnminified -\r\n\r\n<img width=\"218\" alt=\"polkadot apps portal 2019-01-08 12-44-56\" src=\"https://user-images.githubusercontent.com/1424473/50830065-e610a600-1346-11e9-93e9-b28834b9dc7a.png\">\r\n\r\nSimilar to https://github.com/polkadot-js/api/issues/462\r\n\r\n"}, {"classified_as": "enhancement", "text": "- 10.12.0\r\n- 6.4.1\r\n- 3.0.0-alpha.14.4.0\r\n- 5.7.23\r\n- Mojave\r\n\r\n\r\n**What is the current behavior?**\r\nNewly created types do not appear in the content types list.\r\n\r\n**Steps to reproduce the problem**\r\nJust follow the Quick Start guide\r\n\r\n**What is the expected behavior?**\r\nThey should appear. I see them in the database and in the Content Manager.\r\n\r\n**Suggested solutions**\r\n\ud83e\udd37\u200d\u2642\ufe0f"}, {"classified_as": "enhancement", "text": "When choosing xml or json response types, the options are being lost\n"}, {"classified_as": "bug", "text": "**Describe the bug**\r\ni have a many-to-many relation between doctor and meta. graphql query:\r\n doctors(limit:1}) {\r\n    id\r\n    metas{    id    }\r\n    }\r\n\r\ngenerates 3 mysql queries :\r\n1.  select doctors.* from doctors limit 1\r\n\r\n2. select distinct metas.* from metas left join doctop.doctors_metas__metas_doctors as doctors_metas__metas_doctors_1 on doctors_metas__metas_doctors_1.meta_id = metas.id left join doctop.doctors as doctors_1 on doctors_metas__metas_doctors_1.doctor_id = doctors_1.id where doctors_1.id in ('308384')\r\n\r\n3. select distinct doctors.*, doctors_metas__metas_doctors.meta_id as _pivot_meta_id, doctors_metas__metas_doctors.doctor_id as _pivot_doctor_id from doctors inner join doctors_metas__metas_doctors on doctors_metas__metas_doctors.doctor_id = doctors.id where doctors_metas__metas_doctors.meta_id in (26, 438, 872)\r\n\r\n\r\nthe third query is very time consuming. i have 1500000 doctors in my db, and system crashs with heap mempry!! i want only one doctor metas.  i dont undrestand why the third query is generated! \r\nincreaseing server memory, the heap memory error disapears. but the query runing time is 30 seconds!  and make website very slow. i even created a new strapi inctance, with doctor and meta only models. the queries is the same as my current instance!\r\n\r\n\r\n \r\n\r\n \r\n\r\n**Steps to reproduce the behavior**\r\n1. define meta, doctor models\r\n2. a many-to-many relation betwnn meta and doctor\r\n3. create 100K doctor and 100k metas\r\n4. query the doctors and metas. 3 qouries last more than 30S. low performance ....\r\n\r\n**Expected behavior**\r\n2 first qouries is enough!:\r\n1.  select doctors.* from doctors limit 1\r\n\r\n2. select distinct metas.* from metas left join doctop.doctors_metas__metas_doctors as doctors_metas__metas_doctors_1 on doctors_metas__metas_doctors_1.meta_id = metas.id left join doctop.doctors as doctors_1 on doctors_metas__metas_doctors_1.doctor_id = doctors_1.id where doctors_1.id in ('308384')\r\n\r\n \r\n**System**\r\n- Node.js version: v12.16.1\r\n- NPM version: 6.13.4\r\n- Strapi version:  v3.0.0-beta.18.8\r\n- Database: mysql\r\n- Operating system: centos\r\n \r\n\r\n"}, {"classified_as": "bug", "text": "**Information**\r\n- **Node.js version**:  v10.14.1 \r\n- **NPM version**:  v6.4.1\r\n- **Strapi version**: commit hash 2edd056\r\n- **Database**:  mongo with replicas and +srv string\r\n- **Operating system**:  Google Kubernetes Engine running linux and custom docker based on commit 2edd056 \r\n\r\n**What is the current behavior?**\r\n\r\nThere is no ENV to specify +srv\r\n\r\n**Steps to reproduce the problem**\r\n\r\nCan't setup mongo replicas without resorting to manually editing configuration database.json\r\n\r\nstrapi new appname is missing a parameter where I could specify +srv=true\r\n\r\n    strapi new <name> \\\r\n    --dbclient=<dbclient> \\\r\n    --dbhost=<dbhost> \\\r\n    --dbport=<dbport> \\\r\n    --dbname=<dbname> \\\r\n    --dbusername=<dbusername> \\\r\n    --dbpassword=<dbpassword> \\\r\n    --dbssl=<dbssl> \\\r\n    --dbauth=<dbauth>\r\n\r\nhttps://strapi.io/documentation/3.x.x/cli/CLI.html#strapi-new\r\n\r\n**What is the expected behavior?**\r\n\r\nSpecifically, the command line strapi new app should take command line params to NONINTERACTIVELY save database.json like this. \r\n\r\n    {\r\n      \"defaultConnection\": \"default\",\r\n      \"connections\": {\r\n        \"default\": {\r\n          \"connector\": \"strapi-hook-mongoose\",\r\n          \"settings\": {\r\n            \"client\": \"mongo\",\r\n            \"host\": \"some.mongodb.net\",\r\n            \"srv\": true,\r\n            \"port\": 27017,\r\n            \"database\": \"strapi\",\r\n            \"username\": \"username\",\r\n            \"password\": \"password\"\r\n          },\r\n          \"options\": {\r\n            \"authenticationDatabase\": \"admin\",\r\n            \"ssl\": true\r\n          }\r\n        }\r\n      }\r\n    }\r\nNeed ENV to set +srv connection: true (default false) that sets -> scope.database.settings.srv\r\n\r\nRelated to https://github.com/strapi/strapi-docker/issues/71 and https://github.com/strapi/strapi-docker/issues/52"}, {"classified_as": "enhancement", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n\r\nPlease ensure you have also read and understand the contributing guide.\r\n\r\nhttps://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue\r\n-->\r\n\r\n**Describe the bug**\r\n\r\nPassing callback url instead of using the default registered provider callback doesn't seems to be working. In my case I'm using SPA on many domains with one API. In this case i need the API to redirect to correct SPA instance. \r\n\r\n\r\nGET https://API.com/connect/facebook?callback=https://DOMAIN1.com/en/auth/google\r\nGET https://API.com//connect/facebook?callback=https://DOMAIN2.com/en/auth/google\r\nGET https://API.com//connect/facebook?callback=https://DOMAIN3.com/en/auth/google\r\n \r\nis not working as expected \r\n\r\n**Steps to reproduce the behavior**\r\n\r\nFollow tutorial on https://strapi.io/documentation/v3.x/plugins/users-permissions.html#providers part that says \r\n\r\n> You can also pass a custom callback url instead of using the default registered provider callback, by passing callback in the query. eg: GET /connect/facebook?callback=https://my-frontend.com/en/auth/facebook.\r\n\r\nI was testing Google OAuth. \r\n\r\n**Expected behavior**\r\n\r\nURL like http://localhost:5000/connect/google?callback=http://localhost:3001/connect/google should redirect to http://localhost:3001/connect/google after successful login. \r\n\r\nSeems like callback is not a valid name to be passed to OAuth provider and this is trimmed from actual call, so once Provider redirects back to API callback url is lost. What I have found out that state is a parameter that can be used here (https://developers.google.com/identity/protocols/oauth2/web-server) \r\n\r\n> You can use this parameter for several purposes, such as directing the user to the correct resource in your application, sending nonces, and mitigating cross-site request forgery.\r\n\r\n**Code snippets**\r\n\r\nChanging the following code seems to be fixing the issue \r\nhttps://github.com/strapi/strapi/blob/master/packages/strapi-plugin-users-permissions/controllers/Auth.js#L264\r\njs\r\n    // Ability to pass OAuth callback dynamically\r\n    grantConfig[provider].callback = _.get(ctx, 'query.callback') || _.get(ctx, 'query.state') || grantConfig[provider].callback;\r\n    grantConfig[provider].state = _.get(ctx, 'query.callback') || grantConfig[provider].callback;\r\n\r\n\r\n**System**\r\n\r\n- Node.js version: v12.16.1\r\n- NPM version: 6.13.4\r\n- Strapi version: 3.0.0\r\n- Database: sqlite\r\n- Operating system: MacOS 10.15.5\r\n\r\n**Additional context**\r\n\r\nI'm not creating a MR so far, because I'm not sure if my solution is valid, I'm not OAuth expert and I haven't tested any other providers except Google. "}, {"classified_as": "bug", "text": "Starting the API against Substrate fdac986a and other recent versions gives the error\r\n\r\n\r\n2019-10-04 10:28:30 API/DECORATOR: Error: \"FATAL: Unable to initialize the API: Unable to find plain type for {\"info\":5,\"type\":\"GroupIndex\"}\"\r\n"}, {"classified_as": "bug", "text": "If you look at this line, we trying to get referrer from extraHTTPHeaders:\r\nhttps://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L565\r\n\r\nSo, at this code example I forced to clear extra headers for proper resources loading:\r\njs\r\nawait page.setExtraHTTPHeaders({\r\n  referer: 'https://example.com/'\r\n});\r\n\r\nawait page.goto('https://github.com/');\r\n\r\nawait page.setExtraHTTPHeaders({});\r\n\r\n\r\nThis is really bad way to set referrer, because **even in CDP** referrer is specified as a parameter, not header. This is not even funny!\r\nhttps://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L601\r\n\r\nWhile I'm trying to clear headers after navigation with empty object, page will load resources (like CSS and scripts, images) with a **wrong** referrer!\r\n\r\nTry to set extra header referer on your page and load image, and you will see amazing wrong referer:\r\n\r\n![ref](https://user-images.githubusercontent.com/31924884/44154647-e0e6e5f0-a0b3-11e8-9226-e6be3911ddce.png)\r\n\r\nSo wee need smth like this:\r\n* referrer as a optional parameter at goto, in this case method will ignore headers referer check\r\n* referrer as a parameter only (best way)\r\n\r\nNow I'm forced to rewrite goto method a little, can we fix it?"}, {"classified_as": "enhancement", "text": "Commit 4599d5841353fdf8096191c30a592fedc844efce an incomplete/incorrect fix.\r\n\r\nIn IdManager.h, id_traits has its static variables assigned inline, right where they are declared.  This is incorrect unless the inline keyword is used.  I'm not a C++ expert but the current code may violate the One Definition Rule.  Without the inline keyword, the linkage works strangely, which is the source of the undefined reference error on debug builds.\r\n\r\nOne solution besides inline would be out-of line declarations of the static variables, but this is tricky because of the void_t.  Once implemented, this solution causes gcc to complain about the use of non-contexpr variables in the static_assert, so it does not work.\r\n\r\nThe best solution IMO is to replace the const keyword with constexpr for base, step, count, and invalid in both specializations of id_traits.  This makes the static_assert in the second class template valid, and it also fixes the undefined reference error.\r\n\r\nRegardless, a new local variable in the destructor of sys_vm_t is not a good fix."}, {"classified_as": "enhancement", "text": "We're trying to document an existing API by creating the JSON definition files by hand.  The resource listing file has baseUrl set to the location of the JSON files.  The API definitions files have baseUrl set to the location of the API.\n\nWith this setup, the definitions are loaded correctly, and the API samples work (if CORS headers are set up right), but nowhere in the displayed documentation tells you the base URL for the API calls - the page footer references the base URL for the JSON, which is not very helpful to the readers. :-)\n\nPS It really wasn't a good idea to have two baseUrl parameters with different meanings depending on which JSON file they appear in.\n"}, {"classified_as": "enhancement", "text": "The \"Off\" button doesn't seem to clear the OAuth token, or prevent the Authorization header from being sent.\n\nOn the Swagger [example site](http://petstore.swagger.io/#!/pet/findPetsByStatus), I went to findPetsByStatus, and clicked \"On\" to authenticate with OAuth. When I made a request to the API, it sent the Authorization header, as expected.\n\nThen I clicked \"Off\" to log out. When I made another request to the API, it still sent the Authorization header.\n"}, {"classified_as": "enhancement", "text": "https://github.com/syncthing/discosrv/issues/36\n\n@krishnact:\n\n> If we query all three servers, they return \"Seen\" differently:\n> On https://discovery-v4-1.syncthing.net Seen is 2016-02-18T05:23:23.06473Z\n> On https://discovery-v4-2.syncthing.net Seen is 2016-02-17T23:23:22.62165Z\n> On https://discovery-v4-3.syncthing.net Seen is 2016-02-17T23:23:23.494071Z\n> At the same time, each of the serves returns their Local Time (in header) in GMT (like Date : Thu, 18 Feb 2016 04:24:57 GMT).\n> This combination makes it impossible to find deterministically which record is the latest one.\n\n@calmh:\n\n> That looks like a bug. The time zone is claimed to be UTC, so it should be.\n> \n> The confusion is probably in reading the time values from the database, where we get back a nil time zone or so.\n"}, {"classified_as": "enhancement", "text": "I'm seeing this behavior on master - is it a known issue?\n\nAlso, just wondering if master is the best branch to stay up-to-date with the Swagger 2.0 dev work. Or should I use \"develop\" instead?\n"}]