[{"classified_as": "enhancement", "text": "\r\n\tif t := os.Getenv(\"STDEADLOCKTIMEOUT\"); len(t) > 0 {\r\n\t\tit, err := strconv.Atoi(t)\r\n\t\tif err == nil {\r\n\t\t\tm.StartDeadlockDetector(time.Duration(it) * time.Second)\r\n\t\t}\r\n\t} else if !IsRelease || IsBeta {\r\n\t\tm.StartDeadlockDetector(20 * time.Minute)\r\n\t}\r\n\r\nand\r\n\r\n\tuseDeadlock = os.Getenv(\"STDEADLOCKTIMEOUT\") != \"\"\r\n)\r\n\r\nfunc init() {\r\n\tl.SetDebug(\"sync\", strings.Contains(os.Getenv(\"STTRACE\"), \"sync\") || os.Getenv(\"STTRACE\") == \"all\")\r\n\r\n\tif n, err := strconv.Atoi(os.Getenv(\"STLOCKTHRESHOLD\")); err == nil {\r\n\t\tthreshold = time.Duration(n) * time.Millisecond\r\n\t}\r\n\tif n, err := strconv.Atoi(os.Getenv(\"STDEADLOCKTIMEOUT\")); err == nil {\r\n\t\tdeadlock.Opts.DeadlockTimeout = time.Duration(n) * time.Second\r\n\t}\r\n\tl.Debugf(\"Enabling lock logging at %v threshold\", threshold)\r\n}\r\n\r\n\r\nmakes it impossible to run without deadlock detector, as if you set STDEADLOCKTIMEOUT to something that's not a number, you still end up with useDeadlock=true\r\n\r\n"}, {"classified_as": "bug", "text": "**Informations**\r\n- **Node.js version**: v9.10.0\r\n- **npm version**: v5.8.0\r\n- **Strapi version**: 3.0.0-alpha.12\r\n- **Database**: MongoDB\r\n- **Operating system**: macOS\r\n\r\n**What is the current behavior?**\r\n\r\n<img width=\"545\" alt=\"screen shot 2018-04-18 at 13 39 43\" src=\"https://user-images.githubusercontent.com/1007051/38930222-6fedd93c-430f-11e8-8464-f3bd53536841.png\">\r\n\r\nMaybe related with #709, because the folder has spaces and the CLI only show the first word.\r\n\r\n**Steps to reproduce the problem**\r\n\r\nClick the download button from GraphQL plugin on /admin/install-plugin.\r\n\r\n**What is the expected behavior?**\r\n\r\nInstall the plugin.\r\n\r\n**Suggested solutions**\r\n\r\nMaybe related with #709.\r\n\r\n- \" I'm sure that this issue hasn't already been referenced\r\n"}, {"classified_as": "enhancement", "text": "Affects P5 but also drakengard 3 and project diva. \r\n\r\nCan be temporarily fixed by unplugging my speakers and plugging them back in, after a period of intense crackling it goes away for a short time (a few minutes at least.) \r\n\r\nprobably partly pulse's fault but only rpcs3 is having this issue for me. "}, {"classified_as": "bug", "text": "http://imgur.com/PzU7JZX\n\nToo much space?\n"}, {"classified_as": "enhancement", "text": "Issue description:\r\n\r\nThere is a small bug in ContractAbi -> validateMethods\r\n\r\n\r\nassert(unknownKeys.length === 0, Unknown keys ${unknownKeys.join(', ')} found in ABI args for messages.${name});\r\n\r\n\r\nUnder node or RN env,  this will throw error name is undefined\r\n\r\nSolution:\r\n\r\nChange messages.${name} to ${method.name}\r\n"}, {"classified_as": "bug", "text": "**OS:**\r\nDistributor ID: Ubuntu\r\nDescription:    Ubuntu 18.04.1 LTS\r\nRelease:        18.04\r\nCodename:       bionic\r\n\r\n**Environment config:**\r\n\r\nnodejs -v\r\nv10.9.0\r\n\r\nnpm -v\r\n6.2.0\r\n\r\nmongod --version\r\ndb version v4.0.1\r\ngit version: 54f1582fc6eb01de4d4c42f26fc133e623f065fb\r\nOpenSSL version: OpenSSL 1.1.0g  2 Nov 2017\r\nallocator: tcmalloc\r\nmodules: none\r\nbuild environment:\r\n    distmod: ubuntu1804\r\n    distarch: x86_64\r\n    target_arch: x86_64\r\n\r\n**Strapi using deprecated sprintf package:**\r\n\r\nnpm install strapi@alpha -g\r\nnpm WARN deprecated sprintf@0.1.5: The sprintf package is deprecated in favor of sprintf-js.\r\n\r\n**Comment:**\r\nCan you replace _sprintf_ package with _sprintf-js_ package? Thank you."}, {"classified_as": "bug", "text": "Not a big deal, but it was slightly odd to see the Strapi UI capitalize Every Single Word in titles, even when in English, those words should not be capitalized. For example, \"Create An Entry\" should be \"Create an entry\" (or at most \"Create an Entry\", but I don't see the point of capitalizing all nouns), because \"an\" is a preposition and those don't get capitalized when title casing.\r\n\r\n![image](https://user-images.githubusercontent.com/33569/67192567-6c1f4a00-f3b9-11e9-879f-de1f190b8ac2.png)\r\n\r\nSee https://titlecase.com/:\r\n\r\n![image](https://user-images.githubusercontent.com/33569/67192592-79d4cf80-f3b9-11e9-8bb4-24467e6265a2.png)\r\n\r\nI would suggest capitalizing only the first letter, but if the AP Style is desired, the [titlecase](https://www.npmjs.com/package/titlecase) package does the job."}, {"classified_as": "enhancement", "text": "### Introduction\r\nI create this issue to avoid other issues related to the same topic.\r\n\r\n## Description\r\nCurrently, if you are adding a min / max limit or default value,  will not be applied in the REST routes.\r\nOnly required and unique constraints work.\r\n\r\nmin / max will only be applied in the admin panel.\r\n\r\n## Contribution\r\n\r\nIf you want to work on this topic, I suggest you open an RFC on the following repo [strapi/rfcs](https://github.com/strapi/rfcs)"}, {"classified_as": "enhancement", "text": "I just want to mention something I found strange when working with the @polkadot/api and registering custom types. For some reason await ApiPromise.create({ types}) doesn\u2019t work for me instead I need to use getTypeRegistry().register(types);\r\n\r\nawait ApiPromise.create({ types}) creates the following errors in the chrome console:\r\n2019-03-13 16:39:17        RPC-CORE: getMetadata (block: Hash): Customtype:: Number can only safely store up to 53 bits\r\n2019-03-13 16:39:17   API/DECORATOR: loadMeta a: getMetadata (block: Hash): Customtype:: Number can only safely store up to 53 bits"}, {"classified_as": "enhancement", "text": "If the function of your Substrate extrinsic contains usize arguments, the API seems to throw InvalidSignature(0) errors. Changing these to u32 fixes the issue.\r\n\r\nNonetheless, these errors are caught at the API level before the extrinsics with usize function arguments ever touch the chain. Therefore, my intuition is the API cannot parse or serialize usize arguments."}, {"classified_as": "enhancement", "text": "Hello,\r\n\r\nThe following may not be a bug, I have done my best to follow the available documentation, but if there is a correct way to do this then please let me know.\r\n\r\nI am trying to use the[ login example](https://github.com/strapi/strapi-examples/tree/master/login-react) with Strapi deployed to Heroku (as this is how I need to use Strapi in production) rather than localhost.  The example works fine for me locally.\r\n\r\nHowever, in order to get it to work I have to edit the the file in plugins/users-permissions/config/functions/bootstrap.js to include the following\r\n\r\n**UPDATE:**  This is now happening in config/functions/bootstrap.js, since the plugins have been moved to dependencies in the latest beta version.  However, apart from this minor difference, nothing else has been fixed.\r\n\r\n\r\n{\r\n...\r\nredirect_uri: \"https://...herokuapp.com/connect/google/callback\r\n}\r\n\r\n\r\nBefore doing this I also tried editing the file config/environments/production/server.js to specify the host and port (it was not clear from the documentation that this would be required either -- the front-end shows the heroku host in the provider settings dialog regardless)\r\n\r\n\r\n{\r\n...\r\n\"host\": \"https://...herokuapp.com\",\r\n\"port\": \"${process.env.PORT || 1337}\"\r\n}\r\n\r\n\r\nHowever, this does not work, since Heroku will use a different port each time, so while Strapi then correctly uses the right host it also attaches the port, so the redirect becomes \"https://...herokuapp.com:PORT/connect/google/callback\", which fails because this isn't an approved url (it is also not possible to allow wildcards in the list of approved urls).  Even if wildcards were allowed, going to https://...herokuapp.com:PORT also doesn't even work, since Heroku doesn't actually expose this port number.\r\n\r\nHaving to directly edit bootstrap.js feels like a hack.  It also introduces strange behavior in the Strapi front end.  Please see the image below.\r\n\r\n![screenshot](https://user-images.githubusercontent.com/16106511/58759439-1a972f80-857e-11e9-9f51-58cc7cf8985c.PNG)\r\n\r\nIn summary\r\n\r\n- have to edit bootstrap.js to get Facebook and Google login\r\n- the providers setting dialog in the screenshot now includes a duplicate field.\r\n- The last field \"The redirect URL to add in your Facebook application configurations\" doesn't actually represent the redirect address that is used (even if you don't update the deployed host in server.json, it will still show the heroku host but will actually redirect to localhost).\r\n\r\nAny help or suggestions for how to resolve this would be very much appreciated."}, {"classified_as": "enhancement", "text": "From Riot -\r\n\r\nI'm using the polkadot-js/api to build an API. When I consume a Struct type that has an Option.with(BlockNumber) field, and then try to call .toString() on it, I get the error: \"Number can only safely store up to 53 bits\". Any idea why this might be/how to fix?"}, {"classified_as": "bug", "text": "**Describe the bug**\r\n\r\nGraphQL Authentication confusing error message: should be just \"Forbidden\"\r\n\r\n**Steps to reproduce the behavior**\r\n1. Set DB to MongoDB\r\n2. Run any authenticated GraphQL query with Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkN2RjY2Y4NzQyODEzNDJhNDliZmQ0ZCIsImlhdCI6MTU2ODUyNjgwMSwiZXhwIjoxNTcxMTE4ODAxfQ.VZGU5Nb91Ac-lF16XeqcbopM3HawTMcVGY61QcwJ8go\r\n\r\n3. Error:\r\n\r\n\r\n[GraphQL error]: Message: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"UsersPermissionsUser\", Location: [object Object], Path: projects\r\nGraphQL error occurred [getDataFromTree] { Error: GraphQL error: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"UsersPermissionsUser\"\r\n    at new ApolloError (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:92:26)\r\n    at d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:1587:34\r\n    at d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:2007:15\r\n    at Set.forEach (<anonymous>)\r\n    at d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:2005:26\r\n    at Map.forEach (<anonymous>)\r\n    at QueryManager.broadcastQueries (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:2003:20)\r\n    at d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:2130:19\r\n    at Object.next (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\zen-observable\\lib\\Observable.js:308:23)\r\n    at notifySubscription (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\zen-observable\\lib\\Observable.js:130:18)\r\n    at onNotify (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\zen-observable\\lib\\Observable.js:165:3)\r\n    at SubscriptionObserver.next (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\zen-observable\\lib\\Observable.js:219:7)\r\n    at d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:1101:36\r\n    at Set.forEach (<anonymous>)\r\n    at Object.next (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\apollo-client\\bundle.umd.js:1100:21)\r\n    at notifySubscription (d:\\project_amanah\\soluvas\\appstudio\\node_modules\\zen-observable\\lib\\Observable.js:130:18)\r\n  graphQLErrors:\r\n   [ { message:\r\n        'Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"UsersPermissionsUser\"',\r\n       locations: [Array],\r\n       path: [Array],\r\n       extensions: [Object] } ],\r\n  networkError: null,\r\n  message:\r\n   'GraphQL error: Cast to ObjectId failed for value \"1\" at path \"_id\" for model \"UsersPermissionsUser\"',\r\n  extraInfo: undefined }\r\n\r\n\r\n**Expected behavior**\r\n\r\nIf JWT sub and User ID in database doesn't match type, simply give Forbidden error.\r\n\r\n**System**\r\n- Node.js version: 10.16.3\r\n- NPM version: 6.11.3\r\n- Strapi version: 3.0.0-beta.16.3\r\n- Database: MongoDB\r\n- Operating system: Windows 10 1903\r\n"}, {"classified_as": "bug", "text": "<!--  If you do not respect this template your issue will be closed. -->\r\n\r\n<!--  Before writing your issue make sure you are using:-->\r\n<!-- Node 9.x.x -->\r\n<!-- npm 5.x.x -->\r\n<!-- The latest version of Strapi. -->\r\n\r\n**Informations**\r\n- **Node.js version**: v10.4.1\r\n- **npm version**: 6.1.0\r\n- **Strapi version**: 3.0.0-alpha.12.4\r\n- **Database**: N/A\r\n- **Operating system**: N/A\r\n\r\n\r\n**What is the current behavior?**\r\n\r\nusing the following command strapi generate:api blah test:string generates some of the base API structure in /api but a few of the new bits are missing in the sub files or just are not up to date with recent changes.\r\n\r\n**Steps to reproduce the problem**\r\n\r\nCreate two models, one using the AdminUI blah1 (Set an example field like string -> test1) and one using the strapi generate:api blah2\r\n\r\nThen run 4 diffs between them:\r\ndiff api/blah1/config/routes.json api/blah2/config/routes.json\r\n\r\ndiff api/blah1/controllers/Blah1.js api/blah2/controllers/Blah2.js\r\n\r\ndiff api/blah1/models/Blah1.settings.json api/blah2/models/.settings.json\r\n\r\ndiff api/blah1/services/Blah1.js api/blah2/services/Blah2.js\r\n\r\nYou should notice quite a few differences between them (with the exception of the change in model name of course)\r\n\r\n**What is the expected behavior?**\r\n\r\nstrapi-cli generate commands should mirror the adminUI functionality\r\n\r\n**Suggested solutions**\r\n\r\nModify the strapi-cli to better reflect recent changes.\r\n\r\n<!--  Make sure to browse the opened and closed issues before submitting your issue. -->\r\n"}, {"classified_as": "enhancement", "text": "Refer to this thread https://groups.google.com/forum/#!topic/swagger-swaggersocket/akJxBdyqJNg\n\nCurrently it is not possible to use the same field name in both path and formdata.\n\nIf you have different fields with the same name in path and formdata, then one will disappear.\n\nIt should be possible to do so.\n"}, {"classified_as": "enhancement", "text": "Depositing into the EVM account yields:\r\n\r\nTry again\r\nError: createType(Vec<EventRecord>):: findMetaEvent: Unable to find Event with index 0x0012/[0,18]\r\n"}, {"classified_as": "bug", "text": "When I go to database settings page in studio, my browser automatically fill fields \"username\" and \"password\". Maybe you can add attribute autocomplete=\"off\" in these fields?\n\n![2016-01-31 22 35 48](https://cloud.githubusercontent.com/assets/557190/12704394/1df1d3d4-c86b-11e5-9c47-39efc962d7dd.png)\n\nBrowser: Google Chrome, Mac OS.\n"}, {"classified_as": "enhancement", "text": "It looks like the tap method is flaky, or at least the test for it is.\r\n\r\nhttps://travis-ci.org/GoogleChrome/puppeteer/jobs/271528560"}, {"classified_as": "bug", "text": "Just leaving this here as it's not something I can get to just yet but I will be looking at it. Currently when running an individual test case on Windows (e.g. Release\\node test\\parallel\\test-whatever, if Node.js crashes during the run it just aborts with no obvious indicator of the crash. This is typical on Windows, unfortunately, when not using a debug build. Since we're wrapping the test process anyway when there are Flags: in the test file, it would make sense to also check the exit code of the child process on Windows to report if the process exited due to a fault."}, {"classified_as": "bug", "text": "Hi! I'm using ApiPromise with websocket provider as singleton like this:\r\n\r\n\r\nlet wsProvider;\r\nlet client;\r\n\r\nfunction createClientInstance() {\r\n  wsProvider = new WsProvider('wss://rpc.polkadot.io');\r\n\r\n  client = new ApiPromise({ provider: wsProvider });\r\n}\r\n\r\nasync function buildDotClient() {\r\n  try {\r\n    if (!wsProvider) {\r\n      createClientInstance();\r\n    }\r\n\r\n    await client.isReady;\r\n\r\n    return client;\r\n  } catch (e) {\r\n    throw new Error('service_unavailable');\r\n  }\r\n}\r\n\r\n\r\nAnd then use client in some script inside interval. But from time to time I get such errors:\r\nAPI-WS: disconnected from wss://rpc.polkadot.io code: '1006' reason: 'Connection dropped by remote peer.'\r\nAPI-WS: disconnected from wss://rpc.polkadot.io code: '1006' reason: 'connection failed'\r\n\r\nAnd after throwing such error from ApiPromise, script gets stuck. It's even impossible to catch for following restart.\r\nI even tried to add event emitter listenings, but still the same:\r\n\r\n    client.on('disconnected', () => {\r\n      createClientInstance();\r\n    });\r\n\r\n    client.on('error', () => {\r\n      createClientInstance();\r\n    });\r\n\r\n\r\nMaybe it is possible to restart connection manually?\r\n\r\nPackage version:\r\n\"@polkadot/api\": \"^1.30.1\""}, {"classified_as": "bug", "text": "Using the ProgressDialog on Android Lollipop with material design puts the percentage and the counter below the ProgressBar [1].\nUsing your excellent library puts them next to the ProgressBar [2].\nI like the percentage being on the right, but would like the values to be below the progress bar (closer to \"stock\" material design).\n\n[1] ![1](https://cloud.githubusercontent.com/assets/3263955/7134162/8ad2bf66-e29a-11e4-89ea-615c6710fff8.png)\n\n[2] ![2](https://cloud.githubusercontent.com/assets/3263955/7134161/8ad28eba-e29a-11e4-98d5-1f41969458a6.png)\n"}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n\r\nPlease ensure you have also read and understand the contributing guide.\r\n\r\nhttps://github.com/strapi/strapi/blob/master/CONTRIBUTING.md#reporting-an-issue\r\n-->\r\n\r\n**Describe the bug**\r\nEvery time strapi-plugin-documentation/config/functions/bootstrap.js runs, it will write to full_documentation.json even if no update is created.\r\n\r\n**Steps to reproduce the behavior**\r\n\r\n1. create a new project with users-permissions and documentation plugin installed \r\n2. start the server \r\n3. it should edit full_documentation.json but only changing thex-generation-date info\r\n\r\n**Expected behavior**\r\nIf no update has been made, it should not write to the file\r\n\r\n**Screenshots**\r\n\r\n![image](https://user-images.githubusercontent.com/20282317/89776024-a110af00-db3b-11ea-81d2-dc29ac5a0109.png)\r\n![image](https://user-images.githubusercontent.com/20282317/89776120-d3baa780-db3b-11ea-8f24-1de12a8b810d.png)\r\n\r\n**Code snippets**\r\nwhen bootstrap.js runs, it will almost always enter this condition\r\njs\r\n// strapi-plugin-documentation/config/functions/bootstrap.js: line 101\r\nif (!isMergedDocumentationExists || shouldUpdateFullDoc) {\r\n    // Create the folder\r\n    services.createDocumentationDirectory(documentationPath);\r\n    // Write the file\r\n    fs.writeFileSync(\r\n      path.resolve(documentationPath, 'full_documentation.json'),\r\n      JSON.stringify(fullDoc, null, 2),\r\n      'utf8'\r\n    );\r\n}\r\n\r\n\r\nas caused by checkIfPluginDocNeedsUpdate returning true when checking the \"users-permissions\" plugin, as it has 2 tags: UsersPermissions - User and UsersPermissions - Role\r\njs\r\n// strapi-plugin-documentation/config/functions/bootstrap.js: line 38\r\nconst needToUpdatePluginDoc = services.checkIfPluginDocNeedsUpdate(plugin);\r\n\r\n\r\nthis happens because createDocObject() uses _.merge() which doesnt work if there is a property that contains an array, as it will override the array. Thus only one tag can appear in the object. To fix that the function should be changed to mergeWith that has a customizer for array values\r\njs\r\n// strapi-plugin-documentation/services/Documentation.js\r\n// from\r\ncreateDocObject: array => {\r\n    return array.reduce((acc, curr) => _.merge(acc, curr), {});\r\n},\r\n\r\n// to \r\ncreateDocObject: array => {\r\n    function forArray(objValue, srcValue) {\r\n      if (_.isArray(objValue)) {\r\n        return objValue.concat(srcValue);\r\n      }\r\n    }\r\n    return array.reduce((acc, curr) => _.mergeWith(acc, curr,forArray), {});\r\n},\r\n\r\n\r\nhowever this raises another error in the areObjectsEquals() function as it simply does return JSON.stringify(obj1) === JSON.stringify(obj2); to check for equality and will fail if the arrays don't have the exact same order\r\n\r\n**System**\r\n- Docker image: strapi/strapi:3.1.3\r\n- Node.js version: v12\r\n- NPM version:\r\n- Strapi version: 3.1.3\r\n- Database: MongoDB\r\n- Operating system: Linux"}, {"classified_as": "enhancement", "text": "Silent Hill Downpour (BLUS30565) spanish language, everything shows correctly except for special characters, specifically accents (\u00e9, \u00e1, \u00ed, \u00f3, \u00fa) which are replaced by weird symbols, is there any way to fix this?\r\n![Captura de pantalla (3)](https://user-images.githubusercontent.com/51327725/83812813-70844300-a6bc-11ea-80fa-dd38997dac55.png)\r\n"}, {"classified_as": "bug", "text": "If you attempt to require('package-name') using v13.7.0 in the repl it will fail with a 'MODULE_NOT_FOUND' error.\r\n\r\njs\r\n// index.js\r\nconsole.log('yay')\r\n// package.json\r\n{\r\n  \"name\": \"ohno\",\r\n  \"main\": \"./index.js\"\r\n}\r\n\r\nbash\r\n$ node\r\n> require('ohno')\r\n\r\n> Uncaught Error: Cannot find module 'ohno'\r\n> Require stack:\r\n> - <repl>\r\n>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)\r\n>     at Function.Module._load (internal/modules/cjs/loader.js:862:27)\r\n>     at Module.require (internal/modules/cjs/loader.js:1040:19)\r\n>     at require (internal/modules/cjs/helpers.js:72:18) {\r\n>   code: 'MODULE_NOT_FOUND',\r\n>   requireStack: [ '<repl>' ]\r\n> }\r\n\r\nbash\r\n$ node -r ./index.js\r\nyay\r\n\r\nbash\r\n$ node -r ohno\r\n\r\n> internal/modules/cjs/loader.js:983\r\n>   throw err;\r\n>   ^\r\n> \r\n> Error: Cannot find module 'ohno'\r\n> Require stack:\r\n> - internal/preload\r\n>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)\r\n>     at Function.Module._load (internal/modules/cjs/loader.js:862:27)\r\n>     at Module.require (internal/modules/cjs/loader.js:1040:19)\r\n>     at Module._preloadModules (internal/modules/cjs/loader.js:1296:12)\r\n>     at loadPreloadModules (internal/bootstrap/pre_execution.js:435:5)\r\n>     at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:68:3)\r\n>     at internal/main/repl.js:18:1 {\r\n>   code: 'MODULE_NOT_FOUND',\r\n>   requireStack: [ 'internal/preload' ]\r\n> }"}, {"classified_as": "bug", "text": "* **Version**: v13.6.0\r\n* **Platform**: Linux 535297d0ce81 4.19.0-4-amd64 #1 SMP Debian 4.19.28-2 (2019-03-15) x86_64 GNU/Linux\r\n* **Subsystem**: stream\r\n\r\n### What steps will reproduce the bug?\r\n\r\n    const stream = require('stream');\r\n    \r\n    // two different transforms (these work)\r\n    const transform_double = new stream.Transform({\r\n        transform(chunk, encoding, callback) {\r\n            this.push(chunk);\r\n            this.push(chunk);\r\n            callback();\r\n        }\r\n    });\r\n    const transform_uppercase = new stream.Transform({\r\n        transform(chunk, encoding, callback) {\r\n            this.push(chunk.toString().toUpperCase());\r\n            callback();\r\n        }\r\n    });\r\n    \r\n    // compose the transforms\r\n    const parser = stream.pipeline(transform_double, transform_uppercase, ()=>0);\r\n    \r\n    // run stdin through it\r\n    process.stdin.pipe(parser).pipe(process.stdout);\r\n\r\nThen pipe some text to it eg: echo \"foo\" | node reproduce.js\r\n\r\n### How often does it reproduce? Is there a required condition?\r\n\r\nalways\r\n\r\n### What is the expected behavior?\r\n\r\nThe text sent in should go through both transformations, eg output \"FOOFOO\"\r\n\r\n### What do you see instead?\r\n\r\nThe text piped in is only sent to the last transformation, eg output \"FOO\"\r\n\r\n### Additional information\r\n\r\nThe docs here don't say what this function returns:\r\nhttps://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback\r\n\r\nI'm saying that it should return a duplex stream so I can read and write to the ends of the pipeline."}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\nStrapi is not using the configured host when spinning up the server\r\n\r\n**Steps to reproduce the behavior**\r\nEven the host that you want to launch your server is configurable but actually Strapi in not using it.\r\nIn [Strapi.js](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/Strapi.js#L236), Strapi launches the sever by doing this.server.listen(this.config.port, async err instead of this.server.listen(this.config.port, this.config.host, async err, which means Node will listen to 0.0.0.0 by [default](https://nodejs.org/api/net.html#net_server_listen_port_host_backlog_callback).\r\nThere was an issue #3525 opened but closed without a fix.\r\n\r\n**Expected behavior**\r\nStrapi should use the host value in config when launching the server.\r\n\r\n**Additional context**\r\nAdd any other context about the problem here.\r\n"}, {"classified_as": "enhancement", "text": "As noted in #2598. Setting the required percentage to zero disables the percentage check. But we also check for each file that there is space for the temp file. But if the temp file already exists this can fail. We should either skip if the temp file already exists or, at the very least, skip the check if the required space is set to zero.\n\n(Apart from this scenario, there may be valid cases where the disk space check just plain doesn't give accurate results and we should let the user override it.)\n"}, {"classified_as": "enhancement", "text": "There are a lot of line breaks after the small icons in the GUI nowadays:\r\n\r\n<img width=\"569\" alt=\"Screen Shot 2019-10-03 at 19 47 32\" src=\"https://user-images.githubusercontent.com/125426/66151014-bc0abc80-e616-11e9-9a03-9e2997756aa7.png\">\r\n\r\nEven when it seems like no line break ought to be necessary at all:\r\n\r\n<img width=\"564\" alt=\"Screen Shot 2019-10-03 at 19 47 43\" src=\"https://user-images.githubusercontent.com/125426/66151065-d349aa00-e616-11e9-928f-3fac9cee1e05.png\">\r\n"}, {"classified_as": "bug", "text": "via V8 error definitions introduced in https://github.com/polkadot-js/api/pull/1441"}, {"classified_as": "enhancement", "text": "The api object has a memory leak. This is consistent across many versions.\r\n\r\nHere you see the memory consumption. The consumption consistently drops when disconnecting and reconnecting.\r\n\r\n![image](https://user-images.githubusercontent.com/5869273/85206318-cffe6780-b2e6-11ea-86c7-5bc5df1deccc.png)\r\n\r\nIs there a clean up we are missing somewhere?\r\n"}, {"classified_as": "bug", "text": "Let me know if I'm doing something wrong, but I'm unable to get the web3js solidity compiler to work, whereas I am able to use the solc npm package to compile. \n\nThis works: \n\n\nvar solc = require('solc');\nvar input = \"contract test {function multiply(uint a) returns(uint d) {return a * 7;}};\"\nvar output = solc.compile(input, 0); // this works \n\n\nThis returns an error: \n\n\nvar Web3 = require('web3');\nweb3 = new Web3(new Web3.providers.HttpProvider(\"http://localhost:8545\"));\nvar input = \"contract test {function multiply(uint a) returns(uint d) {return a * 7;}};\"\nvar output = web3.eth.compile.solidity(input); // this prints the following output\n\n\n> Error: TypeError: Cannot read property 'split' of undefined\n>     at Compiler.compile_solidity (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/compiler.js:14:34)\n>     at Manager.eth_compileSolidity (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/manager.js:197:23)\n>     at Manager.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/manager.js:75:10)\n>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)\n>     at VmSubprovider.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/vm.js:42:12)\n>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)\n>     at GethDefaults.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/lib/gethdefaults.js:17:12)\n>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)\n>     at FilterSubprovider.handleRequest (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/subproviders/filters.js:76:7)\n>     at next (/Users/johnmardlin/.nvm/versions/node/v6.5.0/lib/node_modules/ethereumjs-testrpc/node_modules/web3-provider-engine/index.js:93:18)\n>     at Object.module.exports.InvalidResponse (/Users/johnmardlin/node_modules/web3/lib/web3/errors.js:35:16)\n>     at RequestManager.send (/Users/johnmardlin/node_modules/web3/lib/web3/requestmanager.js:61:22)\n>     at Object.send [as solidity](/Users/johnmardlin/node_modules/web3/lib/web3/method.js:145:58)\n>     at Object.<anonymous> (/Users/johnmardlin/Projects/eth-play/eth-arbitrary/myFlow/myFlow.js:12:31)\n>     at Module._compile (module.js:410:26)\n>     at Object.Module._extensions..js (module.js:417:10)\n>     at Module.load (module.js:344:32)\n>     at Function.Module._load (module.js:301:12)\n>     at Function.Module.runMain (module.js:442:10)\n>     at startup (node.js:136:18)\n> [Finished in 2.1s with exit code 7]\n\nOther functions of web3js are working fine.\n"}, {"classified_as": "enhancement", "text": "If you hit the close button instead of the save button, it still saves every change you made.\n"}, {"classified_as": "enhancement", "text": "Currently, a warning is shown if the admin interface is listening on a unix socket and no authentication is configured:\r\n> The Syncthing admin interface is configured to allow remote access without a password.\r\n\r\nThe warning is not shown if the admin interface is listening on IPv4 or IPv6 localhost. I expect no warning in case of the unix socket, because unix sockets are less open than IPv4 or IPv6 localhost."}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\n\r\nThe browser autofill the username and password when create a new user:\r\n\r\n<img width=\"925\" alt=\"Screenshot 2020-01-22 at 11 59 45\" src=\"https://user-images.githubusercontent.com/1007051/72888972-f788de00-3d0e-11ea-9218-37729e6f0c2a.png\">\r\n\r\n\r\n**Steps to reproduce the behavior**\r\n1. Go to Users content type\r\n2. Click on Add new User\r\n3. The browser autofill the username and password  \r\n\r\n**Expected behavior**\r\n\r\nThe browser not autofill the username and password.\r\n\r\n**System**\r\n- Node.js version: v12\r\n- NPM version: v6\r\n- Strapi version: v3.0.0-beta.18.5\r\n- Database: MongoDB\r\n- Operating system: macOS\r\n"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nIt appears the [index.html](https://github.com/strapi/strapi/blob/master/packages/strapi/lib/middlewares/public/index.html) [still?] references assets on strapi.io. It also appears this asset is blocked due to a referral policy.\r\n\r\n**Steps to reproduce the behavior**\r\n\r\n1. npx strapi create strapi --quickstart\r\n2. visit http://localhost:1337/\r\n3. Observe logo missing\r\n\r\n**Expected behavior**\r\nLogo should be present.\r\n\r\n**Screenshots**\r\n![2020-05-20 14_50_04-Welcome to your Strapi app](https://user-images.githubusercontent.com/10567322/82485421-64d43200-9aa9-11ea-8604-31db51f29e2f.png)\r\n\r\n**System**\r\n\r\n- strapi/strapi:3.0.0-beta.20.3 docker image\r\n- Node.js version: v12.13.0\r\n- Database: mongo\r\n"}, {"classified_as": "enhancement", "text": "i think it would be nice if the option to stop or resume emulation shortcuts were awailable again, for me it was convenient and i dont know why it got rid of it (it was ctrl + s/ctrl + e for stop and continue)\n"}, {"classified_as": "enhancement", "text": "If a spec is invalid (for example, reference an external file that does not exist), we end up rendering the spec but we produce error in the console and some of the functionality of the UI doesn't work (expanding operations).\r\n\r\nWe need to figure out a better way to handle these cases."}, {"classified_as": "bug", "text": "\r\n\r\n**Informations**\r\n- **Node.js version**: 9.9.0\r\n- **npm version**: 5.6.0\r\n- **Strapi version**: 3.0.0-alpha.12.2\r\n- **Database**: MongoDB\r\n- **Operating system**: Windows 10\r\n\r\n\r\n**What is the current behavior?**\r\n\r\nI'm calling a custom API route called /client/categories/:code ,that should return the categories column based on the entered \":code\" passed. In service:\r\n\r\n\r\nfindCategoriesUser: (params) => {\r\n        var query = Client.findOne({'access_code': params.code});\r\n        query.select({  \"_id\":0, \"avatar_image\":0, \"id\":0, \"access_code\":0, \"createdAt\":0, \"updatedAt\":0, \"__v\":0, \"products\":0});\r\n        return query.exec();\r\n    },\r\n\r\n\r\nThe API call works but for some reason, the payload returned still includes the fields \"avatar_image\", \"products\" and \"id\", on top of the categories field:\r\n\r\n\r\n{\r\n    \"categories\": [\r\n        \"5b0412434af3412c685af19e\"\r\n    ],\r\n    \"products\": null,\r\n    \"avatar_image\": null,\r\n    \"id\": null\r\n}\r\n\r\n\r\n**Steps to reproduce the problem**\r\n\r\nmake custom routing for calling the service and set all columns except the 'categories' column to 0. \r\n\r\n**What is the expected behavior?**\r\n\r\nAPI result should not include \"avatar_image\", \"products\" and \"id\"\r\n\r\n**Suggested solutions**\r\n\r\nI'm guessing there is a faulty hook somewhere that causes this\r\n"}, {"classified_as": "bug", "text": "### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: 1.6.0\r\n* Platform / OS version: Linux henrique-Latitude-5480 4.15.0-23-generic #25-Ubuntu SMP Wed May 23 18:02:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux\r\n* URLs (if applicable):  http://home.ubalt.edu/abento/frames/myframe.html\r\n* Node.js version: v8.11.3\r\n\r\n**What steps will reproduce the problem?**\r\n\r\njs\r\n(async () => {\r\n\r\nconst puppeteer = await require('puppeteer');\r\n\r\nconst browser = await puppeteer.launch({headless:false,/* slowMo: 50*/});\r\nconst incognitoContext = await browser.createIncognitoBrowserContext();\r\nconst page = await incognitoContext.newPage();\r\npage.on('dialog', async dialog => {\r\n    await console.log('MESSAGE \"%s\": \"%s\"',dialog.type(),dialog.message());\r\n    await dialog.dismiss();\r\n});\r\nawait page.setCacheEnabled(false);\r\n\r\nawait page.goto('http://home.ubalt.edu/abento/frames/myframe.html', {waitUntil: ['load','domcontentloaded','networkidle0']});\r\n\r\nconst leftFrame = await page.frames().filter( el => el.name() == 'left')[0]\r\nconst rightFrame = await page.frames().filter( el => el.name() == 'right')[0]\r\nawait console.log('URLS: MAIN FRAME: %s ; RIGHT FRAME: %s ; LEFT FRAME: %s ', page.url(), rightFrame.url(), leftFrame.url());\r\nconst navigationPromise = page.waitForNavigation();\r\nawait leftFrame.click('a[href=\"option2.html\"]');\r\nawait console.log('URLS: MAIN FRAME: %s ; RIGHT FRAME: %s ; LEFT FRAME: %s ', page.url(), rightFrame.url(), leftFrame.url());\r\nawait page.waitFor(5000);\r\nawait console.log('URLS: MAIN FRAME: %s ; RIGHT FRAME: %s ; LEFT FRAME: %s ', page.url(), rightFrame.url(), leftFrame.url()); // DISPLAY OTHER URL FOR rightFrame\r\nawait navigationPromise;\r\nawait console.log('URLS: MAIN FRAME: %s ; RIGHT FRAME: %s ; LEFT FRAME: %s ', page.url(), rightFrame.url(), leftFrame.url()); // NOT DISPLAYED, navigationPromise ERROR\r\nawait browser.close();\r\n    \r\n})();\r\n\r\n\r\n**What is the expected result?**\r\nI was expecting navigationPromise to be resolved, but it doesn't.\r\n\r\n**What happens instead?**\r\n\r\nnavigationPromise isn't resolved. Is it the expected behavior? Is it possible to add a frame.waitForNavigation() function?\r\n\r\nScreenshot:\r\n\r\n![image](https://user-images.githubusercontent.com/19354250/42958092-fdac0fda-8b5a-11e8-8896-ab7ab65fb4fe.png)\r\n\r\n\r\nThanks\r\n\r\nPS: I've also tried with the code below, using waitForNavigation as suggested in frame.click() documentation:\r\n\r\njs\r\n\"use strict\";\r\n\r\n(async () => {\r\n\r\nconst puppeteer = await require('puppeteer');\r\n\r\nconst browser = await puppeteer.launch({headless:false,/* slowMo: 50*/});\r\nconst incognitoContext = await browser.createIncognitoBrowserContext();\r\nconst page = await incognitoContext.newPage();\r\npage.on('dialog', async dialog => {\r\n    await console.log('MESSAGE \"%s\": \"%s\"',dialog.type(),dialog.message());\r\n    await dialog.dismiss();\r\n});\r\nawait page.setCacheEnabled(false);\r\n\r\nawait page.goto('http://home.ubalt.edu/abento/frames/myframe.html', {waitUntil: ['load','domcontentloaded','networkidle0']});\r\n\r\nconst leftFrame = await page.frames().filter( el => el.name() == 'left')[0]\r\nconst rightFrame = await page.frames().filter( el => el.name() == 'right')[0]\r\n\r\nawait Promise.all([\r\n    page.waitForNavigation(),\r\n    leftFrame.click('a[href=\"option2.html\"]')\r\n]);\r\n\r\n})();\r\n"}, {"classified_as": "bug", "text": "![image](https://user-images.githubusercontent.com/11762429/76786579-35960180-6796-11ea-80b2-f42561f3a484.png)"}, {"classified_as": "enhancement", "text": "Current master, effectively block don't show up in the apps UI atm"}, {"classified_as": "bug", "text": "### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: 1.1.0\r\n* Platform / OS version: Mac OSX\r\n* Node.js version: 9.5.0\r\n\r\n**What steps will reproduce the problem?**\r\n\r\ndevice_test.js:\r\n\r\njs\r\nconst request = require('request');\r\nconst util = require('util');\r\nconst puppeteer = require('puppeteer');\r\n\r\nconst PORT =  process.env.PORT || 9222;\r\n\r\n(async() => {\r\n  const resp = await util.promisify(request)(http://localhost:${PORT}/json/version);\r\n  const {webSocketDebuggerUrl} = JSON.parse(resp.body);\r\n  const browser = await puppeteer.connect({browserWSEndpoint: webSocketDebuggerUrl});\r\n\r\n  const page = await browser.newPage();\r\n  await page.goto('https://example.com');\r\n\r\n  console.log(await browser.version());\r\n  console.log(await page.title());\r\n\r\n  await page.addStyleTag({content: '* {color: red;}'});\r\n\r\n  try {\r\n    // await page.close(); // causes page crash\r\n    // await browser.close(); // causes exception \r\n  } catch (err) {\r\n    console.error(err);\r\n  }\r\n\r\n  // process.exit(0); // only way to exit script.\r\n\r\n})();\r\n\r\n\r\n1. Use the task switcher to kill all instances of Chrome running on the device\r\n3. Run adb forward tcp:9222 localabstract:chrome_devtools_remote\r\n4. Run node device_test.js\r\n\r\n**What is the expected result?**\r\n\r\nCalling page.close() or browser.close() works on Chrome Andorid.\r\n\r\n**What happens instead?**\r\n\r\nCalling browser.close() causes an exception:\r\n\r\n\r\nChrome/66.0.3348.3\r\nExample Domain\r\n{ Error: Protocol error (Browser.close): 'Browser.close' wasn't found undefined\r\n    at Promise (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Connection.js:86:56)\r\n    at new Promise (<anonymous>)\r\n    at Connection.send (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/C\r\nonnection.js:85:12)\r\n    at Browser.create (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/La\r\nuncher.js:209:71)    at Browser.close (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Bro\r\nwser.js:147:31)    at /Users/ericbidelman/projects/puppeteer/puppeteer-examples/device_testing.js:25:19    at <anonymous>\r\n    at process._tickCallback (internal/process/next_tick.js:160:7)  message: 'Protocol error (Browser.close): \\'Browser.close\\' wasn\\'t found undefined' }\r\n\r\n\r\nCalling page.close() causes a page crash:\r\n\r\n\r\nericbidelman-macbookpro:puppeteer-examples ericbidelman$ node device_testing.jsChrome/66.0.3348.3\r\nExample Domain\r\n(node:15592) UnhandledPromiseRejectionWarning: Error: Page crashed!    at Page._onTargetCrashed (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer\r\n/lib/Page.js:116:24)    at CDPSession.Page.client.on.event (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules\r\n/puppeteer/lib/Page.js:104:56)    at CDPSession.emit (events.js:160:13)\r\n    at CDPSession._onMessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Connection.js:215:12)\r\n    at Connection._onMessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/puppeteer/lib/Connection.js:117:19)    at WebSocket.emit (events.js:160:13)\r\n    at Receiver._receiver.onmessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/WebSocket.js:143:47)\r\n    at Receiver.dataMessage (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/Rec\r\neiver.js:389:14)\r\n    at Receiver.getData (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/Receive\r\nr.js:330:12)\r\n    at Receiver.startLoop (/Users/ericbidelman/projects/puppeteer/puppeteer-examples/node_modules/ws/lib/Receiver.js:165:16)\r\n(node:15592) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)\r\n(node:15592) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.\r\n\r\n"}, {"classified_as": "enhancement", "text": "Other titles might be affected too. Haven't experienced it before.\nIf you run Sonic CD with ppu llvm and wait for some time and play a few levels (usually 5-7 minutes is enough) it will hang, but not completely. Sound will still be playing, although very distorted, and emu will be doing, what it seems like, some sysprx mutex stuff. But the picture will stop completely.\n"}, {"classified_as": "bug", "text": "<!--\r\nSTEP 1: Are you in the right place?\r\n\r\n- For general technical questions or \"how to\" guidance, please search StackOverflow for questions tagged \"puppeteer\" or create a new post.\r\n\r\nhttps://stackoverflow.com/questions/tagged/puppeteer\r\n\r\n- For issues or feature requests related to the DevTools Protocol (https://chromedevtools.github.io/devtools-protocol/), file an issue there:\r\n\r\nhttps://github.com/ChromeDevTools/devtools-protocol/issues/new.\r\n\r\n- Problem in Headless Chrome? File an issue against Chromium's issue tracker:\r\n\r\nhttps://bugs.chromium.org/p/chromium/issues/entry?components=Internals%3EHeadless&blocking=705916\r\n\r\nFor issues, feature requests, or setup troubles with Puppeteer, file an issue right here!\r\n-->\r\n\r\n### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: 0.12.0\r\n* Platform / OS version: MacOS\r\n* URLs (if applicable): https://h5.m.taobao.com/trip/home/index.html\r\n\r\n**What steps will reproduce the problem?**\r\n\r\n_Please include code that reproduces the issue._\r\n\r\n1. use puppeteer to capture performance for the page.\r\n\r\n\r\nconst puppeteer = require('puppeteer');\r\nconst devices = require('puppeteer/DeviceDescriptors');\r\nconst iPhone = devices['iPhone 6'];\r\nconst co = require('co');\r\nconst path = require('path');\r\nco(function* () {\r\n  const PAGE_URL = 'https://h5.m.taobao.com/trip/home/index.html';\r\n  const browser = yield puppeteer.launch({\r\n    headless: false,\r\n    ignoreHTTPSErrors: true,\r\n    args: [\r\n      '--auto-open-devtools-for-tabs'\r\n    ],\r\n    userDataDir: path.join(__dirname, 'user-dir')\r\n  });\r\n  const page = yield browser.newPage();\r\n  yield page.emulate(iPhone);\r\n\r\n  try {\r\n    yield page.goto(PAGE_URL);\r\n  } catch (e) {\r\n    console.error(>> Load page ${PAGE_URL} error encounted: );\r\n    console.error(e.stack);\r\n  }\r\n  yield page.waitForNavigation({\r\n    waitUntil: 'networkidle',\r\n    networkIdleTimeout: 2000\r\n  });\r\n  const perfEntries = yield page.evaluate(() => performance.getEntries());\r\n  console.log(perfEntries);\r\n\r\n  browser.close();\r\n\r\n  return stats;\r\n}).then((stats) => {\r\n  console.log('END');\r\n  console.log(stats);\r\n}).catch(e => {\r\n  console.error(e.stack);\r\n});\r\n\r\n\r\n2. allow geolocation permission\r\n3. set the preset geolocation in devtools/sensors:\r\n\r\n![image](https://user-images.githubusercontent.com/2196373/31699270-ab8f517c-b387-11e7-92f2-afbaf403bd8d.png)\r\n\r\n**What is the expected result?**\r\n\r\nThe Geolocation preset config is saved to user-dir, and next time chromium should use the settings here to enable geolocation mock.\r\n\r\n**What happens instead?**\r\n\r\nThe settings in devtools/sensors were not persistent, next time the code runs the geolocation settings were reset, which made the code in the page request geolocation failed.\r\n\r\nOr is there any way to set the geolocation mock by args param when chromium launch?\r\n"}, {"classified_as": "bug", "text": "After calling new Web3('ws://localhost:8545') the node.js process never ends but instead hangs forever\r\nCalling web3.currentProvider.connection.close() does not help and throws error when using with the HttpProvider.\r\n (Of course you can call process.exit(0) but it's ugly)\r\n"}, {"classified_as": "enhancement", "text": "Hi,\r\n\r\nWhilst investigating that kqueue issue (#6596) I've found an unrelated (?) test failure:\r\n\r\n\r\n=== RUN   TestWatchRename\r\n    TestWatchRename: basicfs_watch_test.go:444: Timed out before receiving all expected events\r\n--- FAIL: TestWatchRename (10.01s)\r\n\r\n\r\nThis is today's master (c20ed80dc473ae7476a9359a55f7ec2618eb62e2) on FreeBSD-12.1.\r\n\r\nAll I did was add -v and -count=1 to the test target in build.go.\r\n\r\nHappy to provide more info if you let me know how to get it :)\r\n\r\nPlease note that I'm not very familiar with FreeBSD."}, {"classified_as": "bug", "text": "**Tell us about your environment:**\r\n\r\n* Puppeteer version: 0.13.0-alpha\r\n* Platform / OS version: macos high sierra 10.13\r\n* URLs (if applicable):\r\n\r\n**What steps will reproduce the problem?**\r\n\r\n_Please include code that reproduces the issue._\r\n\r\njavascript\r\n// start.js\r\n\r\nconst puppeteer = require('puppeteer')\r\n\r\nconst run = async () => {\r\n  const browser = await puppeteer.launch({\r\n    headless: false,\r\n    slowMo: 250,\r\n    args: [\r\n      '--disable-infobars',\r\n    ],\r\n  });\r\n\r\n  const page = await browser.newPage();\r\n\r\n  await page.goto('https://www.google.com/');\r\n\r\n  await page.waitFor(60000)\r\n  await browser.close();\r\n}\r\n\r\nrun()\r\n\r\n\r\n1. node start.js\r\n\r\n**What is the expected result?**\r\n\r\n1. window inner size and viewport should be equal, all the default 800px x 600px\r\n\r\n**What happens instead?**\r\n\r\n1. window inner size is larger than the viewport size\r\n\r\n![google-puppeteer.png](https://i.loli.net/2017/10/27/59f2f0f3b461e.png)\r\n"}, {"classified_as": "bug", "text": "Hey, is it possible to launch as a new tab in an existing profile? \r\n\r\nI have an existing session with cookies and authentication bearer, problem is that puppeteer opens a dedicated chrome without the session or profile I want. \r\n\r\nheres my code:\r\njs\r\n(async () => {\r\n  const browser = await puppeteer.launch({\r\n  \theadless: false,\r\n  \texecutablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',\r\n  \targs: ['--user-data-dir']\r\n  }); \r\n  const page = await browser.newPage();\r\n})();\r\n\r\nif i don't use executablePath it opens a whole new profile and there's no error, but when I do it opens a new window at the correct profile/session yet errors with the following:\r\n\r\n(node:26977) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code."}, {"classified_as": "enhancement", "text": "Vulkan compute descriptor allocation is suboptimal, making large RSX captures impossible to replay. Either the compute-based texture decoder should be possible to disable or the allocation should be dynamic to avoid this situation."}, {"classified_as": "enhancement", "text": "With today's master:\r\njs\r\nconst assert = require('assert');\r\nconst crypto = require('crypto');\r\nfor (let bits = 3; bits <= 15; bits++) {\r\n  const p = crypto.createDiffieHellman(bits).getPrime();\r\n  assert.strictEqual(p.length, 2);\r\n  assert.strictEqual(p.readUInt16BE(0), 35963);\r\n}\r\n\r\nI'd expect the test case to fail (it should find different primes) but it returns the same prime for sizes 3 to 15. It's only at bits >= 16 that it starts to find different primes.\r\n\r\nI'm not sure if this is a Node.js or an openssl bug. log2(35963) > 15 though so it definitely seems wrong to return that prime (and only that prime) for bits <= 15."}, {"classified_as": "bug", "text": "![image](https://user-images.githubusercontent.com/9141017/42243637-46c632e0-7f12-11e8-88f2-4069469289e2.png)\r\n"}, {"classified_as": "bug", "text": "**What steps will reproduce the problem?**\r\nI'm using this code:\r\n\r\n\tasync function interceptHandler(target){\r\n\t\tconst page = await target.page();\r\n\t\tif(!page) return console.log('target opened: wasn\\'t a page');\r\n\t\tconsole.log('target opened: attaching pre-filter for page');\r\n\t\tawait page.setRequestInterception(true);\r\n\t\tpage.on('request',blockLoading);\r\n\t\t}\r\n\r\n\tconst browser=await puppeteer.launch(puppeteerOptions);\r\n\tbrowser.on('targetcreated',interceptHandler);\r\n\tconst page = await browser.newPage();\r\n\r\n**What is the expected result?**\r\nEverything blocked by my blockLoading function should end up blocked (css/images/fonts).\r\n\r\n**What happens instead?**\r\nThis works fine for my initial page -- probably since there's time to attach the handler.\r\n\r\nBut when I have a new tab opening, triggering a new target, I see several css/images loading before the intercept handler kicks in to block the rest.\r\n\r\n@JoelEinbinder said this is a known issue https://github.com/GoogleChrome/puppeteer/issues/386#issuecomment-343059315 but I couldn't find a ticket.\r\n\r\n\r\nA possible option from a user's standpoint would be to save a global handler that automatically gets attached to all new targets, so it already exists upon creation if that somehow solves a race issue.\r\n"}, {"classified_as": "enhancement", "text": "I had some things that could not be scanned (permission denied). I fixed those permissions and want to rescan. I cannot, manually:\r\n\r\n<img width=\"570\" alt=\"Screen Shot 2019-06-10 at 09 38 55\" src=\"https://user-images.githubusercontent.com/125426/59179891-b834c500-8b63-11e9-9b04-f93abd4a79ad.png\">\r\n\r\n(The Rescan button is disabled, presumably because the folder is not in one of the pre-approved scannable states?)\r\n"}, {"classified_as": "enhancement", "text": "* **Version**: v11.15.0\r\n* **Platform**: Linux\r\n\r\nRun the following script with node --inspect script.js, connect a debugger with Google Chrome and instruct it to do a heap snapshot.\r\n\r\n**Edit:** See my comment below for a better snippet.\r\n\r\njs\r\nfunction memoryLeak() {\r\n    return new Promise(() => {});\r\n}\r\n\r\nfunction loop() {\r\n    for (let i = 0; i < 10000; i++) {\r\n        memoryLeak();\r\n    }\r\n\r\n    setTimeout(loop, 0);\r\n}\r\n\r\nloop();\r\n\r\n\r\nRoughly half of the time node will crash with \"pure virtual method called\".\r\n\r\nThat code actually causes a [memory leak](https://github.com/nodejs/node/issues/28787), but it will likely be annoying to debug if this isn't fixed first."}, {"classified_as": "bug", "text": "**Library Version:**\r\n3.0.0-rc3\r\n \r\n**Affected Device(s):**\r\nAndroid 4.3\r\nAndroid >= 5.0\r\n \r\n**Describe the Bug:**\r\nAndroid 4.3: when I'm opening standard MaterialDialog, background is translucent (which is correct in my opinion):\r\n\r\n![ss](https://user-images.githubusercontent.com/30559158/59150897-0ccc2900-8a1a-11e9-9dae-38ac0f70d00b.png)\r\n\r\nBut if I'm opening BottomSheetDialog, background is fully transparent:\r\n\r\n![device-2019-06-08-200416](https://user-images.githubusercontent.com/30559158/59150901-12c20a00-8a1a-11e9-9641-47378539a5c2.png)\r\n\r\nAndroid >= 5.0: when I'm opening standard MaterialDialog, status bar is translucent:\r\n\r\n![material](https://user-images.githubusercontent.com/30559158/59150907-253c4380-8a1a-11e9-9df0-6bdee65d85d7.png)\r\n\r\nBut if I'm opening BottomSheetDialog, status bar turns to white color:\r\n\r\n![bottom](https://user-images.githubusercontent.com/30559158/59150916-41d87b80-8a1a-11e9-949f-5069ad256a54.png)\r\n\r\n(I don't change background and statusbar color in my code)\r\n\r\n**Expected Behavior:**\r\nAndroid 4.3: Background color of BottomSheetDialog should be translucent, like in MaterialDialog\r\nAndroid >= 5.0: Statusbar color should be translucent, like in MaterialDialog"}, {"classified_as": "enhancement", "text": "\r\nHello,\r\n\r\nIs there a REST endpoint for resending verification of emails?  I don't see anything in the documentation.\r\n\r\nThanks."}, {"classified_as": "enhancement", "text": "Hey,\r\nimage bellow for thousand words. I've listed the files manually and don't see discrepancy. Tried to restart services on both sides, to no avail.\r\n\r\nLet me know what additional information I should provide.\r\n\r\nThank you\r\n \r\n![Screenshot from 2020-04-23 08-10-21](https://user-images.githubusercontent.com/8431097/80065129-ea5fd300-8539-11ea-84ec-21eca056432f.png)\r\n\r\n\r\n"}, {"classified_as": "enhancement", "text": "Whether, with Xinput plugin or with the Windows keyboard, control direction (directional button and joystick) really respond very poorly.\n\nWith Xinput it will have almost, but the keyboard is a disaster, I have to press at least 10 times the key to make it work.\n"}, {"classified_as": "enhancement", "text": "Currently \"int\" data type defaults to \"0\" in Model Schema sample value while both \"long\" and \"float\" default to \"0.1\".\n\nSince both \"int\" and \"long\" data types are whole numbers, they should both default to \"0\".\nOnly \"float\" and \"double\" (floating point numbers) should default to \"0.1\".\n"}, {"classified_as": "bug", "text": "* Puppeteer version: 1.0.0-post, chromium_revision 526987\r\n* Platform / OS version: Windows 7 x64\r\n* Node.js version: 9.4.0\r\n\r\n**What steps will reproduce the problem?**\r\n\r\njs\r\n'use strict';\r\n\r\nconst puppeteer = require('puppeteer');\r\n\r\n(async function main() {\r\n  try {\r\n    const browser = await puppeteer.launch({ headless: false });\r\n    const page = await browser.newPage();\r\n\r\n    page.on('console', (msg) => { console.log(msg.text()); });\r\n    page.on('pageerror', (exceptionMessage) => { console.log(exceptionMessage); });\r\n\r\n    const result = await page.evaluate(async () => {\r\n      try {\r\n        const status = await new Promise((resolve, reject) => {\r\n          const xhr = new XMLHttpRequest();\r\n          xhr.onreadystatechange = () => {\r\n            if (xhr.readyState === 4) {\r\n              if (xhr.status === 200) resolve(good status: ${xhr.status});\r\n              else reject(bad status: ${xhr.status});\r\n            }\r\n          };\r\n          xhr.onerror = () => { reject('xhr error'); };\r\n          xhr.open('GET', 'https://example.org/');\r\n          xhr.send();\r\n        });\r\n        return status;\r\n      } catch (err) {\r\n        return err;\r\n      }\r\n    });\r\n    console.log(result);\r\n  } catch (err) {\r\n    console.error(err);\r\n  }\r\n})();\r\n\r\n\r\n**What is the expected result?**\r\n\r\nCORS error message is transferred to puppeteer\r\n\r\n**What happens instead?**\r\n\r\nOnly bad status: 0 in the Node.js console, while this error message in the browser console:\r\n\r\n![err](https://user-images.githubusercontent.com/10393198/35650346-677a22ea-06e4-11e8-9bee-c52734695b1d.png)\r\n\r\nIs there a way to catch this error message, while page.on('console') and page.on('pageerror') seem to not work here?"}, {"classified_as": "enhancement", "text": "The trophy pop up notification don't appear when in fullscreen mode. It seems the pop up notification appear on upper left corner of the gui, not on the main window.\r\nSorry for my english."}, {"classified_as": "enhancement", "text": "Hi, we have a model that starts with an envelope which has a single property which has a list as it's value. The objects that are in that list then have a property that is also a list of name value pairs (see model pasted below). I have seen the reference in the documentation that implies that this doesn't work (\"Containers must hold primitive or complex datatypes--nested containers are not supported.\") although I would argue that I am referencing a complex datatype so maybe it should work? \n\nEither way, here's what the UI wind up generating as the \"model schema\" for my POST:\n\n json\n{\n  \"events\": {\n    \"eventTypeCode\": \"int\",\n    \"eventTimestamp\": \"Date\",\n    \"attributes\": {\n      \"name\": \"string\",\n      \"value\": \"string\"\n    }\n  }\n}\n\n\nNote that it appears to have just ignored the List defined for the RawEventEnvelope entirely and just dropped the RawEvent model in their directly. Additionally, the List in the \"attributes\" property has been ignored as well.\n\nAm I doing something incorrectly, or is this actually unsupported. If it is unsupported, could you possibly point me in the right direction to add the logic to make this supported? I would be happy to look at adding the functionality since I have the need.\n\nOur Model:\n\n json\n\"models\": {\n        \"RawEvent\": {\n            \"properties\" : {\n                \"eventTypeCode\": {\n                    \"type\": \"int\"\n                },\n                \"eventTimestamp\": {\n                    \"type\": \"Date\"\n                },\n                \"attributes\": {\n                    \"type\": \"List\",\n                    \"items\":{\n                       \"$ref\":\"RawAttributeValue\"\n                    }\n                }\n\n            }\n        },\n        \"RawAttributeValue\": {\n            \"properties\" : {\n                \"name\": {\n                    \"type\": \"string\"\n                },\n                \"value\": {\n                    \"type\": \"string\"\n                }\n            }\n        },\n        \"RawEventEnvelope\": {\n            \"properties\" : {\n                \"events\":{\n                        \"type\":\"List\",\n                        \"items\":{\n                           \"$ref\":\"RawEvent\"\n                        }\n                }\n            }\n        }\n    }\n\n"}, {"classified_as": "enhancement", "text": "The \"number of items to display\" option at the foot of the pop-up page is (thankfully!) persistent, but so is the page number.  When the pop-up page is closed _(either with the \"Close\" button or by clicking on originating page \"behind\" the pop-up page)_, the page number that was being displayed is also persistent, so that on re-opening the pop-up _(which always displays page 1 of the refreshed list)_, the page number displayed is wrong - should be 1, of course.\r\n\r\n**A very, VERY minor bug in a superb package!**\r\n\r\nMay I be a nuisance and - as it's related to the same part of SyncThing - mention a preference?   It would be good if the page selector could be at the top of the pop-up as well as it would save a lot of scrolling when 50 items are being displayed.\r\n\r\n\r\n### Version Information\r\n\r\nSyncthing Version: v1.3.4 (Linux 64-bit)\r\nOS Version: Windows 7 (for SyncThing monitoring)\r\nBrowser Version: Firefox 74 (64-bit)\r\n\r\n"}, {"classified_as": "enhancement", "text": "On master\r\n\r\nCircular reference generate errors.\r\n\r\nLike \"Node\" contains a list of nodes for instance\r\n\r\n\r\nErrors\r\n\r\nResolver error\r\ntoo much recursion\r\nResolver error\r\ntoo much recursion\r\n\r\n\r\nParameters view is also broken\r\n\r\nMaybe relative to\r\nVery slow loading times #1919"}, {"classified_as": "bug", "text": "\r\n\r\n### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: v1.0.0\r\n* Platform / OS version: all\r\n* URLs (if applicable):\r\n* Node.js version: all\r\n\r\n**What steps will reproduce the problem?**\r\n\r\n_Please include code that reproduces the issue._\r\n\r\n1. open a page that opens a popup\r\n2. close the page through page.close()\r\n3. observe the browser.targets()\r\n\r\n**What is the expected result?**\r\n\r\nNo leftover targets created by the page, or at least a way of them closing automatically\r\n\r\n**What happens instead?**\r\n\r\na target for the popup stays open\r\n\r\nI'd suggest to keep track of all targets created by the page and closing them when page.close() is called. or maybe with a page.close(closeChildPages)."}, {"classified_as": "enhancement", "text": "Not able to decode DigestItem that returned from RPC\r\n\r\nRelated: https://github.com/paritytech/substrate/pull/1478\r\n\r\nI think the JSON codec needs some better thoughts to avoid those breaking changes"}, {"classified_as": "enhancement", "text": "I'm seeing this behavior on master - is it a known issue?\n\nAlso, just wondering if master is the best branch to stay up-to-date with the Swagger 2.0 dev work. Or should I use \"develop\" instead?\n"}, {"classified_as": "bug", "text": "I'm trying to connect to my unsynced node with api 1.0.0-beta.17 \r\n\r\ntarget=#750431 (25 peers), best: #520014\r\n\r\nI'm getting \r\n![Screen Shot 2020-01-23 at 16 42 13](https://user-images.githubusercontent.com/3409250/72999295-74938080-3dff-11ea-9667-bd96dcc9c5bd.png)\r\n\r\nwhich is uncatchable with both of these\r\n\r\njavascript \r\ntry {\r\n  let api = await ApiPromise.create().catch(e => {})\r\n} catch (e) {}\r\n\r\n\r\nIt also doesn't emit error on \r\njavascript\r\nprovider.on('error',(e)=>{})\r\n\r\n\r\nIt results in stuck application since I can't react on anything that happened here. It also happens when you get error while connecting to wsprovider but it can be handled by wrapping api creation inside another promise, which I can reject. It is not ideal, but it works.\r\n\r\nWhen trying to connect to wss://cc3-5.kusama.network/ I get this on the other hand\r\n\r\n![Screen Shot 2020-01-23 at 16 41 42](https://user-images.githubusercontent.com/3409250/72999309-79583480-3dff-11ea-839f-8dc55b605d44.png)\r\n"}, {"classified_as": "bug", "text": "### Steps to reproduce\r\n\r\n* Puppeteer version: 1.5.0\r\n* Platform / OS version: macOS 10.13.3\r\n* Node.js version: 10.2.1\r\n\r\n**What steps will reproduce the problem?**\r\n\r\n\r\nconst puppeteer = require('puppeteer');\r\n\r\n(async () => {\r\n  const browser = await puppeteer.launch({headless: false});\r\n  const page = await browser.newPage();\r\n  page.on('console', () => browser.close());\r\n  page.goto(data:text/html,<script>console.log(1)</script>, {timeout: 5000});\r\n})();\r\n\r\n\r\n**What is the expected result?**\r\n\r\nThe process should quit almost instantly.\r\n\r\n**What happens instead?**\r\n\r\nThe timeout inside of page.goto keeps the process running for the duration of the timeout. The problem occurs more often in windowed mode than in headless."}, {"classified_as": "enhancement", "text": "The latest published version for @polkadot/storage is 0.38.10 but for other packages are 0.38.11\r\nI am having issue that yarn cannot find @polkadot/storage 0.38.11 and have to manually pick a version as fallback.\r\n\r\nFrom version history you can also see 0.38.6 and few other versions are skipped as well. \r\n\r\nI noticed that packages/type-storage is published lastly, may have some race condition that CI process completes before the version is successfully published?\r\n\r\nhttps://www.npmjs.com/package/@polkadot/storage\r\n\r\nIt seems like yarn may fail to publish and yet still report as success https://github.com/yarnpkg/yarn/issues/5931 https://github.com/yarnpkg/yarn/issues/6200"}, {"classified_as": "bug", "text": "Uploading a file in binary (content-type: image/jpeg) results in \r\n\r\n\r\n{\r\n    \"error\": {\r\n        \"code\": 13,\r\n        \"message\": \"Invalid or Empty Payload\",\r\n        \"class\": \"Directus\\\\Exception\\\\InvalidPayloadException\",\r\n        \"file\": \"/Users/rijkvanzanten/Development/api/src/core/Directus/Application/Route.php\",\r\n...\r\n"}, {"classified_as": "bug", "text": "<!--\r\nSTEP 1: Are you in the right place?\r\n\r\n- For general technical questions or \"how to\" guidance, please search StackOverflow for questions tagged \"puppeteer\" or create a new post.\r\n\r\nhttps://stackoverflow.com/questions/tagged/puppeteer\r\n\r\n- For issues or feature requests related to the DevTools Protocol (https://chromedevtools.github.io/devtools-protocol/), file an issue there:\r\n\r\nhttps://github.com/ChromeDevTools/devtools-protocol/issues/new.\r\n\r\n- Problem in Headless Chrome? File an issue against Chromium's issue tracker:\r\n\r\nhttps://bugs.chromium.org/p/chromium/issues/entry?components=Internals%3EHeadless&blocking=705916\r\n\r\nFor issues, feature requests, or setup troubles with Puppeteer, file an issue right here!\r\n-->\r\n\r\n### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: 10.x\r\n* Platform / OS version: mac\r\n* URLs (if applicable):\r\n* Node.js version: 8.x\r\n\r\n**What steps will reproduce the problem?**\r\nUnable to save page as mhtml\r\n\r\n**What is the expected result?**\r\nneed to save page as mthml or .mht exetension\r\n\r\n**What happens instead?**\r\n\r\nnoting"}, {"classified_as": "enhancement", "text": "I just filed https://bugs.chromium.org/p/chromium/issues/detail?id=713159\r\nThis affects Syncthing, because there is a heading inside the button. This causes chrome to think that the accessibility tree should be flattened, and therefore, the accordian no longer has sections marked with headings.\r\n\r\nIt is not necessarily necessary to have a button here at all for accessibility purposes, because aria-expanded can directly be put on a heading. This will cause a screen reader to report something like \"heading level three collapsed my device 1.\" If this was a feature request in the past, or a user has requested buttons be placed on each element which is to be expanded and collapsed, it should be noted that the heading should probably be placed outside the button to prevent issues such as this. \r\nThanks"}, {"classified_as": "bug", "text": "<!--\r\nThank you for reporting a possible bug in Node.js.\r\n\r\nPlease fill in as much of the template below as you can.\r\n\r\nVersion: output of node -v\r\nPlatform: output of uname -a (UNIX), or version and 32 or 64-bit (Windows)\r\nSubsystem: if known, please specify the affected core module name\r\n\r\nIf possible, please provide code that demonstrates the problem, keeping it as\r\nsimple and free of external dependencies as you can.\r\n-->\r\n\r\n* **Version**:\r\n\r\n13.3.0\r\n\r\n* **Platform**:\r\n\r\nLinux\r\n\r\n* **Subsystem**:\r\n\r\nDebian\r\n\r\n<!-- Please provide more details below this comment. -->\r\n\r\nIf I were to create a \"server\" for IPC using a named pipe like:\r\n\r\n\r\nconst ipc_server = net.createServer((c) => {\r\n        // 'connection' listener.\r\n        console.log('ipc client connected');\r\n        c.on('end', () => {\r\n                console.log('ipc client disconnected');\r\n        });\r\n        c.write('hello\\r\\n');\r\n        c.pipe(c);\r\n});\r\n\r\nipc_server.listen('/tmp/collect.sock', () => {\r\n        console.log('ipc connected at /tmp/pipe_name.sock');\r\n});\r\n\r\n\r\nThere are permission issues if I am accessing that named pipe from a process which has a different linux profile permission mask than the user which started the server.\r\n\r\nIt would be really nice to just have the ability to set the permissions on the named pipe file when creating the server with net.createServer().\r\n\r\nYou get something like this when trying to connect to the named pipe in a process ran by a user with different permissions on his account.\r\n\r\n\r\nipc client error { Error: connect EACCES /tmp/pipe_name.sock\r\n    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1106:14)\r\n  errno: 'EACCES',\r\n  code: 'EACCES',\r\n  syscall: 'connect',\r\n  address: '/tmp/pipe_name.sock' }\r\n"}, {"classified_as": "enhancement", "text": "Serialization fails. Would normally just fix (instead of log), but need to decode the Opaque system again to see what is up here."}, {"classified_as": "enhancement", "text": "Since the new upgrade check (#6385) we're getting a significant flood of upgrade requests. The problem is that some clients are stuck in restart loops, for various reasons, and hammer the upgrade server. We can of course offload this in various ways (CDNs and whatnot) but it still seems like an oversight that we should handle better...\r\n\r\nServer side rate limiting at the HTTPS level isn't enormously useful as the main cost is in the TLS handshake to begin with."}, {"classified_as": "bug", "text": "### Source\r\nPackage.json\r\n\r\n### Found\r\neslint ./**/*.js --fix --ignore-pattern node_modules/\"\r\n\r\n### Suggested\r\n- [x] Create .eslintignore.js file. \r\n- [x] Add folders and files that will be ignored."}, {"classified_as": "enhancement", "text": "When logging into our app we're using the PFFacebookUtils method PFFacebookUtils.logInInBackgroundWithReadPermissions(self.permissions, block: {}) and that is working fine.  The first time that is ran, the callback has the user.isNew flag set to true and we go one path.\n\nHowever I'm trying to test out the workflow where the user deletes the app from their phone and Facebook account.\n\nIn this instance when I hit the other path where user.isNew is false in the callback, the new time I go to save the user after making updates to it, I get the error Facebook auth is invalid for this user..\n\nIs this by design and is there something I have to do to get this workflow working?  Or is this a bug?\n"}, {"classified_as": "enhancement", "text": "I paused this thing way back and it just keeps on syncing. New connections are prevented but existing ones are not terminated.\r\n\r\n<img width=\"571\" alt=\"Screenshot 2019-07-19 at 12 07 44\" src=\"https://user-images.githubusercontent.com/125426/61527971-f607f180-aa1d-11e9-8eca-37b996c8298a.png\">\r\n"}, {"classified_as": "bug", "text": "<!-- Note: you can also replace the whole content by the file generated by perlbug utility. -->\r\n\r\n<!--\r\nIf your bug is about a Perl core module rather than a core language\r\nfeature, please enter its name after.\r\n-->\r\nModule: none\r\n\r\n**Description**\r\n\r\nThe non-GCC SvTRUEx() macro expands like:\r\n\r\nC\r\n#  define SvTRUEx(sv)      ((PL_Sv = (sv)), SvTRUE(PL_Sv))\r\n#define SvTRUE(sv)         (LIKELY(sv) && SvTRUE_NN(sv))\r\n#define SvTRUE_NN(sv)      (SvGETMAGIC(sv), SvTRUE_nomg_NN(sv))\r\n#define SvTRUE_nomg_NN(sv) (SvTRUE_common(sv, sv_2bool_nomg(sv)))\r\n\r\n\r\nWhile this prevents the argument sv to SvTRUEx() from being evaluated multiple times, if the sv has any magic the SvGETMAGIC() call may call code that uses any of the other SvFOOx() macros that also modify PL_Sv, which is interpreter global, so the following call to SvTRUE_nomg_NN() will end up testing the wrong sv.\r\n\r\n**Expected behavior**\r\n\r\nSimilar to the other SvFOOx() macros, SvTRUEx() should leave magic to a helper function.\r\n\r\n**Perl configuration**\r\n\r\nSummary of my perl5 (revision 5 version 31 subversion 6) configuration:\r\n  Commit id: 0927980403a8984cd4df39ccb644eb53b1e6a3b2\r\n  Platform:\r\n    osname=linux\r\n    osvers=4.9.0-9-amd64\r\n    archname=x86_64-linux-thread-multi\r\n    uname='linux mars 4.9.0-9-amd64 #1 smp debian 4.9.168-1+deb9u5 (2019-08-11) x86_64 gnulinux '\r\n    config_args='-des -Dusedevel -Dusethreads -Doptimize=-O0 -g'\r\n    hint=recommended\r\n    useposix=true\r\n    d_sigaction=define\r\n    useithreads=define\r\n    usemultiplicity=define\r\n    use64bitint=define\r\n    use64bitall=define\r\n    uselongdouble=undef\r\n    usemymalloc=n\r\n    default_inc_excludes_dot=define\r\n    bincompat5005=undef\r\n  Compiler:\r\n    cc='cc'\r\n    ccflags ='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2'\r\n    optimize='-O0 -g'\r\n    cppflags='-D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'\r\n    ccversion=''\r\n    gccversion='6.3.0 20170516'\r\n    gccosandvers=''\r\n    intsize=4\r\n    longsize=8\r\n    ptrsize=8\r\n    doublesize=8\r\n    byteorder=12345678\r\n    doublekind=3\r\n    d_longlong=define\r\n    longlongsize=8\r\n    d_longdbl=define\r\n    longdblsize=16\r\n    longdblkind=3\r\n    ivtype='long'\r\n    ivsize=8\r\n    nvtype='double'\r\n    nvsize=8\r\n    Off_t='off_t'\r\n    lseeksize=8\r\n    alignbytes=8\r\n    prototype=define\r\n  Linker and Libraries:\r\n    ld='cc'\r\n    ldflags =' -fstack-protector-strong -L/usr/local/lib'\r\n    libpth=/usr/local/lib /usr/lib/gcc/x86_64-linux-gnu/6/include-fixed /usr/include/x86_64-linux-gnu /usr/lib /lib/x86_64-linux-gnu /lib/../lib /usr/lib/x86_64-linux-gnu /usr/lib/../lib /lib /lib64 /usr/lib64\r\n    libs=-lpthread -lnsl -lgdbm -ldb -ldl -lm -lcrypt -lutil -lc -lgdbm_compat\r\n    perllibs=-lpthread -lnsl -ldl -lm -lcrypt -lutil -lc\r\n    libc=libc-2.24.so\r\n    so=so\r\n    useshrplib=false\r\n    libperl=libperl.a\r\n    gnulibc_version='2.24'\r\n  Dynamic Linking:\r\n    dlsrc=dl_dlopen.xs\r\n    dlext=so\r\n    d_dlsymun=undef\r\n    ccdlflags='-Wl,-E'\r\n    cccdlflags='-fPIC'\r\n    lddlflags='-shared -O0 -g -L/usr/local/lib -fstack-protector-strong'\r\n\r\n\r\nCharacteristics of this binary (from libperl): \r\n  Compile-time options:\r\n    HAS_TIMES\r\n    MULTIPLICITY\r\n    PERLIO_LAYERS\r\n    PERL_COPY_ON_WRITE\r\n    PERL_DONT_CREATE_GVSV\r\n    PERL_IMPLICIT_CONTEXT\r\n    PERL_MALLOC_WRAP\r\n    PERL_OP_PARENT\r\n    PERL_PRESERVE_IVUV\r\n    PERL_USE_DEVEL\r\n    USE_64_BIT_ALL\r\n    USE_64_BIT_INT\r\n    USE_ITHREADS\r\n    USE_LARGE_FILES\r\n    USE_LOCALE\r\n    USE_LOCALE_COLLATE\r\n    USE_LOCALE_CTYPE\r\n    USE_LOCALE_NUMERIC\r\n    USE_LOCALE_TIME\r\n    USE_PERLIO\r\n    USE_PERL_ATOF\r\n    USE_REENTRANT_API\r\n    USE_THREAD_SAFE_LOCALE\r\n  Built under linux\r\n  Compiled at Oct 25 2019 05:31:00\r\n  %ENV:\r\n    PERLBREW_BASHRC_VERSION=\"0.43\"\r\n    PERLBREW_HOME=\"/home/tony/.perlbrew\"\r\n    PERLBREW_MANPATH=\"\"\r\n    PERLBREW_PATH=\"/home/tony/perl5/perlbrew/bin\"\r\n    PERLBREW_ROOT=\"/home/tony/perl5/perlbrew\"\r\n    PERLBREW_VERSION=\"0.67\"\r\n  @INC:\r\n    lib\r\n    /usr/local/lib/perl5/site_perl/5.31.6/x86_64-linux-thread-multi\r\n    /usr/local/lib/perl5/site_perl/5.31.6\r\n    /usr/local/lib/perl5/5.31.6/x86_64-linux-thread-multi\r\n    /usr/local/lib/perl5/5.31.6\r\n\r\n\r\n"}, {"classified_as": "enhancement", "text": "Almost all textures are black now.\n"}, {"classified_as": "enhancement", "text": "Looks like the UI is not showing the accurate reward amount for validators with a commission greater than 0.\r\n\r\nFor instance, the message for this tx https://polkascan.io/pre/kusama/transaction/0x342d516e1f99a7ce92bc5f98aa95ef4566b4f40b70d11367deb75cc9d5d2d8de was Payout rewards (0.000 KSM), the validator has set a 100% commission."}, {"classified_as": "enhancement", "text": "The reported transfer stats use the unit of \"blocks\" which made sense at the time. Now, however, a block can be any size at all between 128k and 16M, and are slowly getting bigger on average as this is rolled out. Hence the graph is mysteriously shrinking:\r\n\r\n<img width=\"1147\" alt=\"Screen Shot 2019-09-04 at 09 32 40\" src=\"https://user-images.githubusercontent.com/125426/64234819-5e8c2e80-cef7-11e9-8223-3ed1e8a966fe.png\">\r\n\r\nThe ratio between the values *might* have some validity (but I'm not 100% sure), but in general for this to be useful we need to switch to byte counts instead."}, {"classified_as": "enhancement", "text": "Using fullPage: true option with [Page.screenshot](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagescreenshotoptions) seems to be messing vw and vh CSS units, even though page size is set with [Page.setViewport](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagesetviewportviewport)."}, {"classified_as": "enhancement", "text": "In my mind, the bug is that STGUIASSETS should no longer point to the same hierachy that we compile in, and that the behavior is different when overriding vs when not. It used to be very simple (assuming $PATH has been requested):\n1. $STGUIASSETS/$PATH\n2. Compiled in asset $PATH\n\nNow we're instead looking for\n1. $STGUIASSETS/$PATH\n2. Compiled in asset $THEME/$PATH\n3. Compiled in asset default/$PATH\n\nI think it would be cleaner if we instead looked for\n1. $STGUIASSETS/$THEME/$PATH\n2. Compiled in asset $THEME/$PATH\n3. $STGUIASSETS/default/$PATH\n4. Compiled in asset default/$PATH\n\nThen we'd get back the old behavior of just being able to override the whole hierarchy and then hack on the dark theme or whatever as @lkwg82 also mentions. A (small) complication is that the theme selector would need to pick up themes present both in the compiled in assets and in the potential overridden assetsDir.\n\nFrom a development point of view, I think pointing STGUIASSETS at the gui dir in the source checkout should result in it working exactly as normal, except that anything in there can be overridden regardless of theme etc. It's just that I haven't noticed this is not the case because I haven't done nay GUI dev work lately :)\n\n(https://github.com/syncthing/docs/pull/132)\n"}, {"classified_as": "bug", "text": "<!--\r\nSTEP 1: Are you in the right place?\r\n\r\n- For general technical questions or \"how to\" guidance, please search StackOverflow for questions tagged \"puppeteer\" or create a new post.\r\n\r\nhttps://stackoverflow.com/questions/tagged/puppeteer\r\n\r\n- For issues or feature requests related to the DevTools Protocol (https://chromedevtools.github.io/devtools-protocol/), file an issue there:\r\n\r\nhttps://github.com/ChromeDevTools/devtools-protocol/issues/new.\r\n\r\n- Problem in Headless Chrome? File an issue against Chromium's issue tracker:\r\n\r\nhttps://bugs.chromium.org/p/chromium/issues/entry?components=Internals%3EHeadless&blocking=705916\r\n\r\nFor issues, feature requests, or setup troubles with Puppeteer, file an issue right here!\r\n-->\r\n\r\n### Steps to reproduce\r\n\r\n**Tell us about your environment:**\r\n\r\n* Puppeteer version: 1.2.0\r\n* Platform / OS version: Windows Server 2008\r\n* URLs (if applicable):\r\n* Node.js version: 8.9.1\r\n\r\n**What steps will reproduce the problem?**\r\nWhen printing web pages that contains hundreds of images.\r\nEven tried the \"pipe\" mode but no avail. If this is a limitation, is there a way to find the size of the write data as it is obviously printing the following statement on the console window\r\n\r\n**[0609/223146.069:ERROR:http_connection.cc(112)] Too large write data is pending: size=725124416, max_buffer_size=268435456**\r\n\r\nTried **Network.dataReceived** option to read the data lengths to get to the overall size but the data size does not match. In my case, I got the data as 521 MB but the write data says 691 MB. \r\n\r\nAttached a picture of the **Network** tab on the devTools. It says 521 MB resources which is correctly matching my reading. However, it says **252 MB** transferred. How do I get this reading? Either way, how do I get the write data size?\r\n<img width=\"529\" alt=\"Screen Shot 2019-06-10 at 9 01 44 AM\" src=\"https://user-images.githubusercontent.com/3056474/59198349-86bafa00-8b61-11e9-9969-fea6e705ebaf.png\">\r\n\r\n\r\n**What is the expected result?**\r\nSuccessfully generate the PDF irrespective of the size of the write data. Else, way to know the size of the write data so that we can document the known limitations.\r\n\r\n**What happens instead?**\r\nFails to generate the PDF when the page contains of hundreds of images. In other words, when the write data is too large."}, {"classified_as": "bug", "text": "**Describe the bug**\r\nThe default _limit for the find() is currently fixed to 100. I can't understand why the team picked it is 100? why wouldn't be 10 or 50?.\r\n\r\nIf some one needed to fetch default 50 records for all end point of find(), at-least he have to edit all request URL or needed to override the current find() handle.\r\n\r\nThis may not be a bug for the team, but for best framework we need to control constant values at configuration level.\r\n\r\n**Steps to reproduce the behavior**\r\n1. Start strapi app\r\n2. create product collection\r\n3. goto http://localhost:1337/products\r\n4. you can see the limitation of 100 products when there are more than 100 products\r\n\r\n**Expected behavior**\r\nThe configuration must be present.\r\n\r\n**System**\r\n- Node.js version: v12.13.0\r\n- NPM version: 6.12.0\r\n- Strapi version: v3.0.0-beta.18.4\r\n- Database: MongoDB\r\n- Operating system: Windows\r\n"}, {"classified_as": "bug", "text": "\r\n![screen shot 2017-09-21 at 7 37 02 pm](https://user-images.githubusercontent.com/12194969/30693950-6bde622a-9e97-11e7-8b2c-9f3ae0fd6e93.png)\r\n"}, {"classified_as": "enhancement", "text": "Commit 4599d5841353fdf8096191c30a592fedc844efce an incomplete/incorrect fix.\r\n\r\nIn IdManager.h, id_traits has its static variables assigned inline, right where they are declared.  This is incorrect unless the inline keyword is used.  I'm not a C++ expert but the current code may violate the One Definition Rule.  Without the inline keyword, the linkage works strangely, which is the source of the undefined reference error on debug builds.\r\n\r\nOne solution besides inline would be out-of line declarations of the static variables, but this is tricky because of the void_t.  Once implemented, this solution causes gcc to complain about the use of non-contexpr variables in the static_assert, so it does not work.\r\n\r\nThe best solution IMO is to replace the const keyword with constexpr for base, step, count, and invalid in both specializations of id_traits.  This makes the static_assert in the second class template valid, and it also fixes the undefined reference error.\r\n\r\nRegardless, a new local variable in the destructor of sys_vm_t is not a good fix."}, {"classified_as": "bug", "text": "<!-- Please use this template while reporting a bug and provide as much info as possible. Not doing so may result in your bug not being addressed in a timely manner. Thanks!\r\n\r\nIf the matter is security related, please disclose it privately via https://kubernetes.io/security/\r\n-->\r\n\r\n\r\n**What happened**:\r\n\r\nI want to deploy k8s with IPV4/IPv6 dual stack.\r\nBut node internal IP always only one either IPV4 or IPV6.\r\nPod IP can auto assigned IPV4,IPV6 calico,  IPv6 Service also work.\r\nBut NodeType only listener at IPV4, not IPV6.\r\n\r\nbash\r\n                \"status\": {\r\n                \"addresses\": [\r\n                    {\r\n                        \"address\": \"10.126.20.162\",\r\n                        \"type\": \"InternalIP\"\r\n                    },\r\n                    {\r\n                        \"address\": \"wxdlong\",\r\n                        \"type\": \"Hostname\"\r\n                    }\r\n                ],\r\n\r\n\r\n**What you expected to happen**:\r\n\r\nAs https://kubernetes.io/docs/tasks/network/validate-dual-stack/  said.\r\n\r\nbash\r\nkubectl get nodes k8s-linuxpool1-34450317-0 -o go-template --template='{{range .status.addresses}}{{printf \"%s: %s \\n\" .type .address}}{{end}}'\r\nHostname: k8s-linuxpool1-34450317-0\r\nInternalIP: 10.240.0.5\r\nInternalIP: 2001:1234:5678:9abc::5\r\n\r\n\r\n\r\n\r\n**How to reproduce it (as minimally and precisely as possible)**:\r\nthe init config \r\n\r\nyaml\r\n\r\napiVersion: kubeadm.k8s.io/v1beta2\r\nkind: InitConfiguration\r\nlocalAPIEndpoint:\r\n  advertiseAddress: \"10.126.20.162\"\r\n  bindPort: 6443\r\nnodeRegistration:\r\n  criSocket: /var/run/dockershim.sock\r\n  taints:\r\n    - effect: NoSchedule\r\n      key: node-role.kubernetes.io/master\r\n  kubeletExtraArgs:\r\n    node-ip: \"10.126.20.162,2001:1b74:88:9400::62:62\"\r\n\r\n\r\n**Anything else we need to know?**:\r\n\r\n**Environment**:\r\n- Kubernetes version (use kubectl version):  v1.17.4\r\n\r\nbash\r\n kubectl version\r\nClient Version: version.Info{Major:\"1\", Minor:\"17\", GitVersion:\"v1.17.4\", GitCommit:\"8d8aa39598534325ad77120c120a22b3a990b5ea\", GitTreeState:\"clean\", BuildDate:\"2020-03-12T21:03:42Z\", GoVersion:\"go1.13.8\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\nServer Version: version.Info{Major:\"1\", Minor:\"17\", GitVersion:\"v1.17.4\", GitCommit:\"8d8aa39598534325ad77120c120a22b3a990b5ea\", GitTreeState:\"clean\", BuildDate:\"2020-03-12T20:55:23Z\", GoVersion:\"go1.13.8\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\n\r\n- Cloud provider or hardware configuration:\r\n- OS (e.g: cat /etc/os-release):\r\n\r\nbash\r\n# cat /etc/os-release\r\nNAME=\"Red Hat Enterprise Linux Server\"\r\nVERSION=\"7.6 (Maipo)\"\r\nID=\"rhel\"\r\nID_LIKE=\"fedora\"\r\nVARIANT=\"Server\"\r\nVARIANT_ID=\"server\"\r\nVERSION_ID=\"7.6\"\r\nPRETTY_NAME=\"Red Hat Enterprise Linux Server 7.6 (Maipo)\"\r\nANSI_COLOR=\"0;31\"\r\nCPE_NAME=\"cpe:/o:redhat:enterprise_linux:7.6:GA:server\"\r\nHOME_URL=\"https://www.redhat.com/\"\r\nBUG_REPORT_URL=\"https://bugzilla.redhat.com/\"\r\n\r\nREDHAT_BUGZILLA_PRODUCT=\"Red Hat Enterprise Linux 7\"\r\nREDHAT_BUGZILLA_PRODUCT_VERSION=7.6\r\nREDHAT_SUPPORT_PRODUCT=\"Red Hat Enterprise Linux\"\r\nREDHAT_SUPPORT_PRODUCT_VERSION=\"7.6\"\r\n\r\n\r\n- Kernel (e.g. uname -a):\r\n\r\nbash\r\n# uname -a\r\nLinux wxdlong 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux\r\n\r\n- Install tools:\r\nbash\r\n# kubeadm version\r\nkubeadm version: &version.Info{Major:\"1\", Minor:\"17\", GitVersion:\"v1.17.4\", GitCommit:\"8d8aa39598534325ad77120c120a22b3a990b5ea\", GitTreeState:\"clean\", BuildDate:\"2020-03-12T21:01:11Z\", GoVersion:\"go1.13.8\", Compiler:\"gc\", Platform:\"linux/amd64\"}\r\n\r\n- Network plugin and version (if this is a network-related bug):\r\n  calico\r\n- Others:\r\n\r\n  May be my init config is not correct, Any one can give an full example for IPV4,IPV6 dual stack. Thanks\r\n"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nIm adding content to the strapi server and its getting really slow. \r\ni do have 67 elements and the api response time is about 9-12 seconds\r\n\r\nthe content type does not have any relational content. is like this:\r\n- 1 enum\r\n- 2 booleans\r\n- image\r\n- repeatable content with 2 images. (usually 10-15 components each)\r\n\r\nIm just trying to get all the content in the api call.\r\n\r\n**Expected behavior**\r\nNot to take seconds on the api response\r\n\r\n**Screenshots**\r\nN/A\r\n**Code snippets**\r\nN/A\r\n\r\n\r\n**System**\r\n- Node.js version: 12.14.1\r\n- NPM version: 6.13.4\r\n- Strapi version: v3.0.0-beta.18.7\r\n- Database: mongodb\r\n- Operating system: ubuntu 18.04\r\n\r\nWhen the Strapi admin panel list the items its also slow, probably the same time (9-12 seconds)\r\n\r\n"}, {"classified_as": "enhancement", "text": "- ::Proposal is returned\r\n- T :: AccountId is returned\r\n- Related https://github.com/paritytech/substrate/issues/1244"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nThere are no GraphQL Mutations for /auth/forgot-password and /auth/reset-password.\r\n\r\n**Steps to reproduce the behavior**\r\n1. Install the GraphQL plugin\r\n2. Open http://localhost:3337/graphql\r\n3. Click on *Docs*\r\n4. See that there is no mutation for those\r\n\r\n**Expected behavior**\r\nThere should be a mutation to trigger a \"forgot password\" and to \"reset password\".\r\n\r\n**Screenshots**\r\n![image](https://user-images.githubusercontent.com/7467891/76857992-718c9d80-684e-11ea-8b08-bafaaf33e6a3.png)\r\n\r\n**System**\r\n- Node.js version: v13.7.0\r\n- NPM version: 6.13.6\r\n- Strapi version: beta-19.3\r\n- Database: mongodb\r\n- Operating system: Windows"}, {"classified_as": "bug", "text": "* Puppeteer version: v1.3.0-post\r\n* Platform / OS version: Windows 7 x64\r\n* Node.js version: 10.0.0 v8-canary\r\n\r\njs\r\n(async () => {\r\n  const browser = await require('puppeteer').launch();\r\n  console.log((await browser.pages()).map(page => page.url()));\r\n  await browser.close();\r\n})();\r\n\r\njs\r\n[ 'about:blank' ]\r\n\r\njs\r\n(async () => {\r\n  const browser = await require('puppeteer').launch({ headless: false });\r\n  console.log((await browser.pages()).map(page => page.url()));\r\n  await browser.close();\r\n})();\r\n\r\njs\r\n[ 'chrome-search://local-ntp/local-ntp.html' ]\r\n\r\n\r\nWould it be more consistent, safe and performance-wise optimal to load about:blank initially in both modes?"}, {"classified_as": "enhancement", "text": "When using custom extrinsic, got an error 1010: Invalid Transaction (-20).\r\n\r\nAfter some debugging, it is because of Submittable extends original Extrinsic not the customized impl, then in Extrinsic.ts:55 where it should pass the if check it fails. (value is a Submittable)\r\n"}, {"classified_as": "bug", "text": "**Informations**\r\n- **Node.js version**: v10.8.0\r\n- **npm version**: 6.2.0\r\n- **Strapi version**: 3.0.0-alpha.13.0.1\r\n- **Database**: mongodb\r\n- **Operating system**: macOS High Sierra\r\n\r\n\r\n**What is the current behavior?**\r\nWhen entering a period in a number field inside a Content Type for any of the three available number formats, any number that was already entered is removed and replaced by a 0. The 0 cannot be removed after. It can only be changed with the up/down arrows. A coma for decimal separation seems to work which is no good for me.\r\n\r\n\r\n**Steps to reproduce the problem**\r\nCreate a Content Type, add any of the available number fields to it. Go to make a new entry in your new Content Type. Type a few numbers in a number field and then try typing a period.\r\n\r\n\r\n**What is the expected behavior?**\r\nBeing able to have a period for decimal separation. Not having to refresh to remove the 0 that gets stuck in the field.\r\n\r\n**Suggestions**\r\nMaybe remove the up down arrows? Seems pointless to me for a simple number input.\r\n"}, {"classified_as": "bug", "text": "**Describe the bug**\r\nthe floating round button with \"?\" that opens the \"GET STARTED VIDEOS\" covers the pagination arrow \r\n\r\n**Steps to reproduce the behavior**\r\n1. insert more than 20 documents in the collection\r\n2. set 20 ( or more ) entries per page\r\n3. Scroll down to the end of the table\r\n4. See the help button covering the pagination arrow and can't click on it\r\n\r\n**Expected behavior**\r\nbutton on a higher place than pagination\r\n\r\n**Screenshots**\r\n![screen](https://user-images.githubusercontent.com/16583356/88924046-f8c53580-d272-11ea-8620-3d4c5d90740a.JPG)\r\n\r\n\r\n**System**\r\n- Node.js version: 14.5.0\r\n- NPM version: 6.14.5\r\n- Strapi version: 3.1.0\r\n- Database: mongoDb\r\n- Operating system: Windows 10\r\n\r\n"}, {"classified_as": "enhancement", "text": "**Describe the bug**\r\nconnectivityManager.getActiveNetworkInfo() (https://developer.android.com/reference/android/net/ConnectivityManager#getActiveNetworkInfo()) and NetworkInfo (https://developer.android.com/reference/android/net/NetworkInfo) were deprecated in API level 29, and we use it in: https://github.com/NativeScript/NativeScript/blob/master/nativescript-core/connectivity/connectivity.android.ts\r\n\r\n**Expected behavior**\r\nI'm not sure how to get the network type but to get the SSID we should use https://developer.android.com/reference/android/net/wifi/WifiManager wifiManager.getConnectionInfo().getSSID()\r\n\r\n"}, {"classified_as": "enhancement", "text": "From https://polkadot.js.org/api/types/\r\n\r\n- Metadata (and it looks the same as others) is not creating a link\r\n- Other links (e.g. AccountId), try to load the .md file instead of the generated HTML - well, actually HTML is not generated\r\n\r\nNeed a solution that does not entail adding all these to SUMMARY.md"}, {"classified_as": "enhancement", "text": "We have not migrated and are still using a combination of development and production databases on Parse. We have an array of pointers column on our _User class. It used to be that calling Parse.addUnique(\"students\", StudentObj); would save a reference pointer to the students but now the server seems to be populating the array with the full objects of each \"student\" _User class.\n\nAdditionally, this is causing a series of problems because calling \"include\" on _User for the students array of pointers is now simply returning an assorted array with some rows only having an ObjectID and some having a full (but out of date) object. What happened to the proper reference pointer logic?\n"}, {"classified_as": "enhancement", "text": "All symlinks in our shares disappeared:\r\n\r\nhttps://gist.github.com/koma85/8901a0f56fa26196bacb5b1fed7b46ea\r\n\r\nThis happened after the automatic update as you can see from our log\r\n\r\n"}, {"classified_as": "bug", "text": "**What is the current behavior?**\r\nLoading too slow\r\nScreen unresponsive\r\n\r\n**Steps to reproduce the problem**\r\n- Create 2 content types\r\n- Create relation between content types ( has many )\r\n- Seed with some items ( i'm trying with 10.000)\r\n- Navigate in content manager, select an item, wait for the results.\r\n\r\n**What is the expected behavior?**\r\nExpected a fast loading of the section, in fact the query is loading all documents. Too long, 2-3 minutes.\r\n\r\n**Suggested solutions**\r\nChecked: content-manager/explorer/{content-type}/{id}?source=content-manager\r\nIt is loading all documents from db, why is needed ?\r\n\r\n**Tested on**\r\nNode: 10.13.0\r\nStrapi: 3.0.0-alpha.14.5,15,16\r\nMongo: 3.6.3\r\nGoogle Chrome: 70.0.3538.110"}, {"classified_as": "enhancement", "text": "For api-observable, I try  unsubscribe bestNumber, but it not send chain_unsubscribeNewHead request"}, {"classified_as": "bug", "text": "Currently the BatchRequest object has an execute function. This function will execute the batch request (presumably in order, although the documentation does not say so). The script which calls execute does not learn that execution has occurred and therefore the process will hang because you cannot call process.exit().\r\n\r\nReturning a promise would fix that."}, {"classified_as": "bug", "text": "**Description**\r\n\r\nThe perlop docs describe the current behavior, so this doesn't contradict anything.\r\n\r\nA chained comparison in 5.31.10 appears to evaluate the middle condition twice for a tied scalar but doesn't warn about it. Since a programmer might not realize they are using a tied variable, they might see odd behavior. \r\n\r\n**Steps to Reproduce**\r\n\r\n\tuse v5.31.10;\r\n\r\n\tpackage UnstableScalar {\r\n\t\tuse parent qw(Tie::Scalar);\r\n\t\tsub TIESCALAR { bless {}, $_[0] }\r\n\t\tsub FETCH {\r\n\t\t\tmy $value = int rand 10;\r\n\t\t\tsay \"Fetching scalar with $value\";\r\n\t\t\treturn $value;\r\n\t\t\t}\r\n\t\t}\r\n\r\n\ttie my $unstable, 'UnstableScalar';\r\n\r\n\tif( 5 < $unstable < 9 ) {\r\n\t\tsay \"Found a value between 5 and 9\";\r\n\t\t}\r\n\r\nThe comparison short circuits just fine, but if the first comparison is true, the tied scalar is evaluated again (so things such as Tie::Cycle will unexpectedly progress or skip values):\r\n\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 2\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 0\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 9\r\nFetching scalar with 2\r\nFound a value between 5 and 9\r\n\r\n$ perl5.31.10 ~/Desktop/test.pl\r\nFetching scalar with 6\r\nFetching scalar with 9\r\n\r\n\r\n**Expected behavior**\r\n\r\nI expect that the scalar would only call FETCH once and reuse the result in the second comparison. perlop says this may happen, but perhaps a warning would be useful here. Ideally, tied variables would be evaluated once.\r\n\r\nIs there a chance that the internals could recognize this and use the tied object instead of the scalar itself? This works as expected:\r\n\r\n\r\n\tif( 5 < tied($unstable)->FETCH < 9 ) {\r\n\t\tsay \"Found a value between 5 and 9\";\r\n\t\t}\r\n\r\n \r\n**Perl configuration**\r\n<!-- Please paste perl -V output just below. -->\r\n\r\nSummary of my perl5 (revision 5 version 31 subversion 10) configuration:\r\n\r\n  Platform:\r\n\tosname=darwin\r\n\tosvers=19.3.0\r\n\tarchname=darwin-2level\r\n\tuname='darwin otter.local 19.3.0 darwin kernel version 19.3.0: thu jan 9 20:58:23 pst 2020; root:xnu-6153.81.5~1release_x86_64 x86_64 '\r\n\tconfig_args='-des -Dprefix=/usr/local/perls/perl-5.31.10 -Dusedevel'\r\n\thint=recommended\r\n\tuseposix=true\r\n\td_sigaction=define\r\n\tuseithreads=undef\r\n\tusemultiplicity=undef\r\n\tuse64bitint=define\r\n\tuse64bitall=define\r\n\tuselongdouble=undef\r\n\tusemymalloc=n\r\n\tdefault_inc_excludes_dot=define\r\n\tbincompat5005=undef\r\n  Compiler:\r\n\tcc='cc'\r\n\tccflags ='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.15 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -DPERL_USE_SAFE_PUTENV'\r\n\toptimize='-O3'\r\n\tcppflags='-fno-common -DPERL_DARWIN -mmacosx-version-min=10.15 -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include'\r\n\tccversion=''\r\n\tgccversion='4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)'\r\n\tgccosandvers=''\r\n\tintsize=4\r\n\tlongsize=8\r\n\tptrsize=8\r\n\tdoublesize=8\r\n\tbyteorder=12345678\r\n\tdoublekind=3\r\n\td_longlong=define\r\n\tlonglongsize=8\r\n\td_longdbl=define\r\n\tlongdblsize=16\r\n\tlongdblkind=3\r\n\tivtype='long'\r\n\tivsize=8\r\n\tnvtype='double'\r\n\tnvsize=8\r\n\tOff_t='off_t'\r\n\tlseeksize=8\r\n\talignbytes=8\r\n\tprototype=define\r\n  Linker and Libraries:\r\n\tld='cc'\r\n\tldflags =' -mmacosx-version-min=10.15 -fstack-protector-strong -L/usr/local/lib'\r\n\tlibpth=/usr/local/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.0/lib /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib /usr/lib\r\n\tlibs=-lpthread -ldbm -ldl -lm -lutil -lc\r\n\tperllibs=-lpthread -ldl -lm -lutil -lc\r\n\tlibc=\r\n\tso=dylib\r\n\tuseshrplib=false\r\n\tlibperl=libperl.a\r\n\tgnulibc_version=''\r\n  Dynamic Linking:\r\n\tdlsrc=dl_dlopen.xs\r\n\tdlext=bundle\r\n\td_dlsymun=undef\r\n\tccdlflags=' '\r\n\tcccdlflags=' '\r\n\tlddlflags=' -mmacosx-version-min=10.15 -bundle -undefined dynamic_lookup -L/usr/local/lib -fstack-protector-strong'\r\n\r\n\r\nCharacteristics of this binary (from libperl): \r\n  Compile-time options:\r\n\tHAS_TIMES\r\n\tPERLIO_LAYERS\r\n\tPERL_COPY_ON_WRITE\r\n\tPERL_DONT_CREATE_GVSV\r\n\tPERL_MALLOC_WRAP\r\n\tPERL_OP_PARENT\r\n\tPERL_PRESERVE_IVUV\r\n\tPERL_USE_DEVEL\r\n\tPERL_USE_SAFE_PUTENV\r\n\tUSE_64_BIT_ALL\r\n\tUSE_64_BIT_INT\r\n\tUSE_LARGE_FILES\r\n\tUSE_LOCALE\r\n\tUSE_LOCALE_COLLATE\r\n\tUSE_LOCALE_CTYPE\r\n\tUSE_LOCALE_NUMERIC\r\n\tUSE_LOCALE_TIME\r\n\tUSE_PERLIO\r\n\tUSE_PERL_ATOF\r\n  Built under darwin\r\n  Compiled at Mar 27 2020 01:45:56\r\n  %ENV:\r\n\tPERL=\"/Users/brian/bin/perls/perl-latest\"\r\n\tPERL5_PATH=\"/Users/brian/bin/perls\"\r\n\tPERL6_PATH=\"/Users/brian/bin/perl6s:/Applications/Rakudo/bin:/Applications/Rakudo/share/perl6/site/bin\"\r\n\tPERLDOTCOM_AUTHOR=\"brian d foy\"\r\n  @INC:\r\n\t/usr/local/perls/perl-5.31.10/lib/site_perl/5.31.10/darwin-2level\r\n\t/usr/local/perls/perl-5.31.10/lib/site_perl/5.31.10\r\n\t/usr/local/perls/perl-5.31.10/lib/5.31.10/darwin-2level\r\n\t/usr/local/perls/perl-5.31.10/lib/5.31.10\r\n\r\n"}, {"classified_as": "enhancement", "text": "There seems to be something wrong with cellGameBootCheck, it cant open PARAM.SFO.\nhere is a log from retro city rampage, where this also happens\n"}, {"classified_as": "bug", "text": "e.g.\r\n\r\njs\r\n// Fill an element \r\nawait browser.fill('#username', 'myUser')\r\n\r\n// set an element's value value\r\nawait browser.setValue('#comment', 'my feelings')\r\n\r\n// Type in an element \r\nawait browser.type('#password', 'Yey!ImAPassword!')\r\n"}, {"classified_as": "enhancement", "text": "Making a PUT request to our goal class https://ourparse/classes/Goal/<goalid> with the following data:\n\n js\n{\n    \"name\":\"lol\",\n    \"startTime\":{\"__type\":\"Date\",\"iso\":\"2016-06-06T07:00:45.653Z\"},\n    \"group\":{\"__type\":\"Pointer\",\"className\":\"Group\",\"objectId\":\"LhQclT1kTc\"},\n    \"type\":\"event\",\n    \"externals\":[]\n}\n\n\nReturns this:\n\n\n{\n  \"code\": 111,\n  \"error\": \"schema mismatch for Goal.updatedAt; expected Date but got String\"\n}\n\n\nWe should look into why that might be the case.\n"}, {"classified_as": "bug", "text": "**Informations**\r\n- **Node.js version**: v11.4.0\r\n- **NPM version**:  6.6.0\r\n- **Strapi version**: 3.0.0-alpha.17 (node v11.4.0)\r\n- **Database**:  Mongo DB (v4.0.5)\r\n- **Operating system**:  Mac\r\n- **(Optional) Link to your Project**: <!-- To speedup support, if you have your project on github/gitlab you can provide a link -->\r\n\r\n\r\n**What is the current behavior?**\r\nQuery to get count having _q=some_search_term always returns 0\r\n\r\n\r\n**Steps to reproduce the problem**\r\n\r\nhit any url to calculate the count i.e pluralized_entity/count?_q=search Keyword\r\n\r\n**What is the expected behavior?**\r\nIt should give the count as it gives in content manager plugin in which countSearch implementation is there\r\n\r\n\r\n**Suggested solutions**\r\n"}, {"classified_as": "enhancement", "text": ":8ball: \n"}, {"classified_as": "enhancement", "text": "- swagger-ui version : 3.0.13 \r\n\r\nSome oAuth2 clients are registred with option **token_endpoint_auth_method = client_secret_post**. That means when they are trying to get token using **/token** endpoint they have to provide client_secret and client_id using request body instead of Authorization header.\r\nCurrent implementation supporting only clients registered with option **token_endpoint_auth_method = client_secret_basic**. \r\n\r\nMore about this here: https://tools.ietf.org/html/rfc7591#section-2\r\n\r\nIt would be nice to have way to control which method will swagger-ui use to get token. As nothing was mentioned in OpenAPI spec maybe we can just add dropdown so user can pick desired method.\r\n\r\n"}, {"classified_as": "enhancement", "text": "https://github.com/RPCS3/rpcs3/blob/87b510d5bfb3fe82e1acc74089cbb9d4a3078201/appveyor.yml#L130\r\n\r\nThis needs to be done only if build succeeds, otherwise a failed branch build may take up the master versioning for that commit and then future builds will fail to be renamed as there can't be duplicated versions."}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\nWhen adding new content, select field was incorrectly wrapped.\r\n\r\n![image](https://user-images.githubusercontent.com/8105211/74779582-c2a18400-52d8-11ea-9854-56d5a7ef87f1.png)\r\n\r\n![image](https://user-images.githubusercontent.com/8105211/74779712-fb415d80-52d8-11ea-942e-2d2357d5e0e1.png)\r\n\r\nThe select field is very short, and drop down options are all broken.\r\n\r\n![image](https://user-images.githubusercontent.com/8105211/74779806-3348a080-52d9-11ea-9473-50f6229ef09e.png)\r\n\r\nDropdown came from dynamic zone with relations child.\r\n\r\n![image](https://user-images.githubusercontent.com/8105211/74779997-a4885380-52d9-11ea-8e6c-275ad16034f2.png)\r\n\r\n**Steps to reproduce the behavior**\r\n1. Setup a new new component (eg. Pricing). Include a Relations field in this component, relating to any content type (eg. Currency)\r\n2. Update an existing content type (eg. Products) and add a new dynamic zone (Pricing). Add the newly created component to the dynamic zone.\r\n3. Go to your existing content type and create new entry\r\n\r\n**Expected behavior**\r\nThe select box should be wrapped properly like this:\r\n\r\n<img width=\"785\" alt=\"Screen Shot 2020-02-19 at 5 39 01 AM\" src=\"https://user-images.githubusercontent.com/8105211/74780254-28424000-52da-11ea-9f50-b4149d2910a4.png\">\r\n\r\n**System**\r\n- Node.js version: v13.8.0\r\n- NPM version: 6.13.6\r\n- Strapi version: Strapi v3.0.0-beta.18.7\r\n- Database: MongoDB 4.2.3 Enterprise (Atlas)\r\n- Operating system: macOS Catalina 10.15.2\r\n"}, {"classified_as": "enhancement", "text": "Since #6336 there's an issue where metadata gets doubled if a recalculation is deemed necessary. The reason is that we will have loaded the existing metadata, then do a recalc by adding all files without clearing it first."}, {"classified_as": "enhancement", "text": "I am using v0.11.2 on OSX. I was transferring a file of 25GB size, and the transfer had started during the creation of the file. The file size of the original file as well of the transferred file are identical, but the content has another md5 sum. How can this happen? Is there any way of how to prevent this?\nThanks!\n"}, {"classified_as": "bug", "text": "<!--\r\nHello \ud83d\udc4b Thank you for submitting an issue.\r\n\r\nBefore you start, please make sure your issue is understandable and reproducible.\r\nTo make your issue readable make sure you use valid Markdown syntax.\r\n\r\nhttps://guides.github.com/features/mastering-markdown/\r\n-->\r\n\r\n**Describe the bug**\r\nWhen editing content of an entry through the Admin panel, if the user **accidentally** navigates to another page without saving the change, there is no prompt to warn them that the unsaved change will be lost. \r\n\r\n**Accidentally navigating to another page can easily happen, and it would be disappointing if a user has entered a lot of content, and losing them by this simple mistake.**\r\n\r\n**Steps to reproduce the behavior**\r\n1. Assuming the content type Restaurant exists, with a field called description for rich text description\r\n2. On the Admin Panel, navigate to \"Create an Entry\" for Restaurant\r\n3. Enter text to the description field, but **without clicking on the \"Save\" button**\r\n4. Navigate to another page within the Admin Panel, such as browsing to another content type through the sidebar. \r\n5. Observe that no warning or prompt is shown, but when coming back to \"Create an (restaurant) Entry\", the previously entered description is lost. \r\n\r\n**Expected behavior**\r\nA prompt is shown, such as \"Your unsaved content will be lost.\" With option to 1) \"Discard un-saved change\" (and proceed to where the user intended to go) or 2) \"Stay on the page\".\r\n\r\n**Screenshots**\r\nN/A.\r\n\r\n**Code snippets**\r\nN/A\r\n\r\n**System**\r\nDocker for Mac, Docker version 19.03.1, build 74b1e89\r\n\r\n**Additional context**\r\nN/A\r\n"}, {"classified_as": "enhancement", "text": "When saving a new PFUser on iOS, the SDK(?) throws this error:\n\nCaught \"NSInternalInconsistencyException\" with reason \"User cannot be saved unless they are already signed up. Call signUp first.\"\nWhen saving a new PFUser via Cloud Code, it does not throw that error but simply mimics a \"signUp\", which creates a session token for the server... in Cloud Code! (actually, read #3 as this may be a bug with the pfuser handling)\n\nFor sake of flexibility and consistency (with PFObjects), I think there should be an option to \"save\" a PFUser without having a session token created, or restricting (iOS) apps to always use PFUser.signUp. There are many use-cases for such a feature, and I feel that it is a meaningless restriction.\n\nPersonal use-case: I have some special logic to replace the standard \"signUp\" flow, which has me creating a PFUser via Cloud Code + MasterKey. But with how the \"save\" function is behaving, it's creating a session token for the server!\n\nRef #1490 \n"}, {"classified_as": "bug", "text": "**Informations**\r\n- **Node.js version**: Node v10\r\n- **NPM version**: NPM v6\r\n- **Strapi version**: 3.0.0-alpha.17\r\n- **Database**: MariaDB 10.2\r\n- **Operating system**: Ubuntu 18.04\r\n- **(Optional) Link to your Project**: [Link](https://github.com/canonn-science/CAPIv2-Strapi/tree/update/autoDocsUpdate)\r\n\r\n\r\n**What is the current behavior?**\r\n\r\nCurrently the model level overrides generate the openapi schema file based on their alphabetical ordering (model name), this can make for an \"ugly\" view on the swaggerUI because even if you define the tags in the core override for the docs the models will force the listing to follow their order. (confused yet?)\r\n\r\n**Steps to reproduce the problem**\r\n\r\nDifficult to describe on reproduction, you can follow my project to see what I'm doing.\r\n\r\nExample image:\r\n\r\n![image](https://user-images.githubusercontent.com/8593673/50218033-c7228380-0347-11e9-9317-7c1799c8599c.png)\r\n\r\nAs you can see in the image above two of my models aren't following the rest because the model Guardian Beacons ranks higher in the alphabetical sorting system than the related Report model.\r\n\r\n**What is the expected behavior?**\r\n\r\nSee Suggestion\r\n\r\n**Suggested solutions**\r\n\r\nIn addition to the core documentation settings.json file I think another should be included basically like tags.json. The order in which the overrides should happen:\r\n\r\n1. Core settings.json\r\n2. Model overrides\r\n3. Core tags.json\r\n\r\nIn this case the user can define the \"sort\" order of how the swagger/openapi doc file is laid out."}, {"classified_as": "enhancement", "text": "javascript\r\napi.queryMulti([\r\n  [api.query.session.nextKeyFor, controllerId],\r\n  [api.query.staking.ledger, controllerId],\r\n], callback)\r\n\r\n\r\nFirst result: [something1, something2],\r\n\r\n**Expected:** \r\n\r\nsecond result: [something1, something3]\r\n\r\n**Actual:**\r\n\r\nsecond result: [null, something3]\r\n\r\n"}, {"classified_as": "enhancement", "text": "SwaggerResource object strips out \".{format}\" when setting \"this.name\".\n\nAs these files are JSON files, \".json\" is the correct extension to use (to get colored syntax and error highlighting from your IDE). But the \".json\" extension should be stripped from the resource heading (section name) in the same way that \".{format}\" already is.\n"}, {"classified_as": "enhancement", "text": "When playing a game and pressing alt+enter to enter fullscreen mode the enter button for example is used as input.\r\nThis can lead to skipped cutszenes and other unintended actions."}, {"classified_as": "bug", "text": "**Node.js version**: 8.9.0\r\n**npm version**: 5.5.1\r\n**Strapi version**: 3.0.0-alpha.8.3\r\n**Operating system**: Windows 7 (Enterprise)\r\n\r\nAfter creating my first content type, the homepage still displays the below message.\r\n\r\n![image](https://user-images.githubusercontent.com/1525669/35304968-7c01bf8a-008f-11e8-9a00-0c04ccf1b0c2.png)\r\n\r\n"}, {"classified_as": "enhancement", "text": "With https://crrev.com/683391, chrome no longer throws exceptions when not executing inline script tags due to CSP.\r\n\r\nWe can fix this with probing runtime first - checking if inline scripts have any power. Alternatively, we might want to check current page CSP policy."}, {"classified_as": "enhancement", "text": "If we fail to rename a file (the last step when pulling it), the temp file is removed. It should instead be kept around as usual so we can reuse it.\n"}]